CLASS LHC_ZI_PM_PRIDE_ROUTE__TEMP_M DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_PM_PRIDE_ROUTE__TEMP_M RESULT RESULT.
    METHODS GET_INSTANCE_FEATURES FOR INSTANCE FEATURES
      IMPORTING KEYS REQUEST REQUESTED_FEATURES FOR ZI_PM_PRIDE_ROUTE__TEMP_M RESULT RESULT.

    METHODS SENDROUTE FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE__TEMP_M~SENDROUTE RESULT RESULT.

    METHODS STOPROUTE FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE__TEMP_M~STOPROUTE RESULT RESULT.
    METHODS ROUTEFIELD FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR ZI_PM_PRIDE_ROUTE__TEMP_M~ROUTEFIELD.
    METHODS MOVEACTUALDATE FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR ZI_PM_PRIDE_ROUTE__TEMP_M~MOVEACTUALDATE.
    METHODS EARLYNUMBERING_CREATE FOR NUMBERING
      IMPORTING ENTITIES FOR CREATE ZI_PM_PRIDE_ROUTE__TEMP_M.
*    METHODS COPYROUTE FOR MODIFY
*      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE__TEMP_M~COPYROUTE.


ENDCLASS.

CLASS LHC_ZI_PM_PRIDE_ROUTE__TEMP_M IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.



*  METHOD copyRoute.
*  ENDMETHOD.

  METHOD EARLYNUMBERING_CREATE.
    DATA(LT_ENTITIES) = ENTITIES.
    DATA LT_ROUTES_M TYPE TABLE FOR MAPPED EARLY ZI_PM_PRIDE_ROUTE__TEMP_M.
    DATA LS_ROUTES_M LIKE LINE OF LT_ROUTES_M.
    DATA LV_ROUTE TYPE ZPM_PRD_RID.

    DELETE LT_ENTITIES WHERE ROUTEID IS NOT INITIAL.
    TRY.
        CL_NUMBERRANGE_RUNTIME=>NUMBER_GET(
          EXPORTING
*           IGNORE_BUFFER     = IGNORE_BUFFER
            NR_RANGE_NR       = '01'
            OBJECT            = 'ZPM_ROUTE'
            QUANTITY          = CONV #( LINES( LT_ENTITIES ) )
*           SUBOBJECT         = SUBOBJECT
*           TOYEAR            = TOYEAR
          IMPORTING
            NUMBER            = DATA(LV_NUM)
            RETURNCODE        = DATA(LV_CODE)
            RETURNED_QUANTITY = DATA(LV_QTY)
        ).
      CATCH CX_NR_OBJECT_NOT_FOUND.
      CATCH CX_NUMBER_RANGES INTO DATA(LO_NUMRANGE).

        LOOP AT LT_ENTITIES INTO DATA(LS_EXT).
          APPEND VALUE #( %CID = LS_EXT-%CID
                          %KEY = LS_EXT-%KEY
                            ) TO FAILED-ZI_PM_PRIDE_ROUTE__TEMP_M.

          APPEND VALUE #( %CID = LS_EXT-%CID
                          %KEY = LS_EXT-%KEY
                          %MSG = LO_NUMRANGE  ) TO REPORTED-ZI_PM_PRIDE_ROUTE__TEMP_M.

        ENDLOOP.
        EXIT.
    ENDTRY.

    ASSERT LV_QTY = LINES( LT_ENTITIES ).

    DATA(LV_CURR_COUNT) = LV_NUM - LV_QTY.

    LOOP AT LT_ENTITIES INTO DATA(LS_ENTITY).
      LV_CURR_COUNT = LV_CURR_COUNT + 1.

      LV_ROUTE = LV_CURR_COUNT.
      CONDENSE LV_ROUTE.
      UNPACK LV_ROUTE TO LV_ROUTE.
      LS_ROUTES_M = VALUE #( %CID = LS_ENTITY-%CID
                              ROUTEID = LV_ROUTE

                               ).

      APPEND LS_ROUTES_M TO MAPPED-ZI_PM_PRIDE_ROUTE__TEMP_M.
      CLEAR LV_ROUTE.
    ENDLOOP.
  ENDMETHOD.

  METHOD GET_INSTANCE_FEATURES.

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M  IN LOCAL MODE
   ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M ALL FIELDS WITH CORRESPONDING #( KEYS )
   RESULT DATA(LT_RESULT_DET).

    RESULT = VALUE #( FOR LS_RESULT IN LT_RESULT_DET ( %TKY = LS_RESULT-%TKY
                                                        %ACTION-STOPROUTE = COND #( WHEN LS_RESULT-ACTIVE = 'S'
                                                                                     THEN  IF_ABAP_BEHV=>MK-OFF
                                                                                     WHEN LS_RESULT-ACTIVE = 'X'
                                                                                     THEN  IF_ABAP_BEHV=>MK-OFF
                                                                                     WHEN LS_RESULT-ACTIVE NE 'S'
                                                                                     THEN IF_ABAP_BEHV=>MK-ON
                                                                                    )
                                                        %ACTION-SENDROUTE = COND #( WHEN LS_RESULT-ACTIVE = 'S'
                                                                                     THEN  IF_ABAP_BEHV=>MK-ON
                                                                                     WHEN LS_RESULT-ACTIVE = 'X'
                                                                                     THEN  IF_ABAP_BEHV=>MK-ON
                                                                                     WHEN LS_RESULT-ACTIVE NE 'S'
                                                                                     THEN IF_ABAP_BEHV=>MK-OFF
                                                                                    ) ) ).

  ENDMETHOD.

  METHOD SENDROUTE.
    DATA LT_RT_MP_UP TYPE TABLE FOR UPDATE ZI_PM_PRIDE_ROUTE__TEMP_M.
    DATA LS_RT_MP_UP LIKE LINE OF LT_RT_MP_UP.

*    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
*    ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M BY \_details
*        ALL FIELDS WITH CORRESPONDING #( KEYS )
*        RESULT DATA(LT_RT_DET).
*    LOOP AT LT_RT_DET ASSIGNING FIELD-SYMBOL(<FS_RT_MP_DT>) WHERE IsActive = 'X'.
*      MOVE-CORRESPONDING <FS_RT_MP_DT> TO LS_RT_MP_UP.
*      LS_RT_MP_UP-ACTIVE = 'E'.
*      LS_RT_MP_UP-%CONTROL-ACTIVE = IF_ABAP_BEHV=>MK-ON.
*      APPEND LS_RT_MP_UP TO LT_RT_MP_UP.
*    ENDLOOP..
    READ ENTITY IN LOCAL MODE ZI_PM_PRIDE_ROUTE__TEMP_M
 ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RT_DET) .

*    RESULT = VALUE #( FOR LS_RT_DET IN LT_RT_DET ( %TKY = LS_RT_DET-%TKY
*    %PARAM = LS_RT_DET ) ).

    LOOP AT LT_RT_DET ASSIGNING FIELD-SYMBOL(<FS_ROUTES>).
      ZCL_PM_PRIDE=>CREATE_WITH_TEMPLATE(
        EXPORTING
          ROUTE_ID     = <FS_ROUTES>-ROUTEID
          START_DATE   = <FS_ROUTES>-SDATE
          SCHEDULE     = <FS_ROUTES>-ROUTESCHEDULE
          START_TIME   = <FS_ROUTES>-STIME
        IMPORTING
          NEW_ROUTE_ID = DATA(NEW_ROUTE_ID)
      ).

      APPEND VALUE #( %TKY = <FS_ROUTES>-%TKY
      %MSG        = NEW_MESSAGE(
                               ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                           NUMBER = '010'
                           V1 = NEW_ROUTE_ID
                         SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-SUCCESS )

      %ELEMENT-ROUTEID = IF_ABAP_BEHV=>MK-ON   ) TO REPORTED-ZI_PM_PRIDE_ROUTE__TEMP_M.

    ENDLOOP.

    MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M UPDATE FIELDS ( ACTIVE )
      WITH VALUE #( FOR LV_KEY IN KEYS ( %TKY = LV_KEY-%TKY
                                         ACTIVE = 'S') )
    FAILED FAILED
    REPORTED REPORTED
    MAPPED MAPPED .

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RT_DET_UP).

    RESULT = VALUE #( FOR LS_RT_DET IN LT_RT_DET_UP ( %TKY = LS_RT_DET-%TKY
    %PARAM = LS_RT_DET ) ).
  ENDMETHOD.

  METHOD STOPROUTE.
    DATA LT_RT_MP_UP TYPE TABLE FOR UPDATE ZI_PM_PRIDE_ROUTE__TEMP_M.
    DATA LS_RT_MP_UP LIKE LINE OF LT_RT_MP_UP.

*    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
*    ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M BY \_details
*        ALL FIELDS WITH CORRESPONDING #( KEYS )
*        RESULT DATA(LT_RT_DET).
*    LOOP AT LT_RT_DET ASSIGNING FIELD-SYMBOL(<FS_RT_MP_DT>) WHERE IsActive = 'X'.
*      MOVE-CORRESPONDING <FS_RT_MP_DT> TO LS_RT_MP_UP.
*      LS_RT_MP_UP-ACTIVE = 'E'.
*      LS_RT_MP_UP-%CONTROL-ACTIVE = IF_ABAP_BEHV=>MK-ON.
*      APPEND LS_RT_MP_UP TO LT_RT_MP_UP.
*    ENDLOOP..

    MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M UPDATE FIELDS ( ACTIVE )
      WITH VALUE #( FOR LV_KEY IN KEYS ( %TKY = LV_KEY-%TKY
                                         ACTIVE = 'P') )
*    ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M UPDATE FIELDS ( ACTIVE )
*    WITH   LT_RT_MP_UP
    FAILED FAILED
    REPORTED REPORTED
    MAPPED MAPPED .

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RT_DET_UP).

    RESULT = VALUE #( FOR LS_RT_DET IN LT_RT_DET_UP ( %TKY = LS_RT_DET-%TKY
    %PARAM = LS_RT_DET ) ).
  ENDMETHOD.

  METHOD ROUTEFIELD.
    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
 ENTITY ZI_PM_PRIDE_ROUTE__TEMP_M
 ALL FIELDS WITH CORRESPONDING #( KEYS )
 RESULT DATA(LT_RESULTS).

    LOOP AT LT_RESULTS ASSIGNING FIELD-SYMBOL(<FS_RESULT_ROUTE>).

      IF <FS_RESULT_ROUTE>-ROUTENAME IS INITIAL.
        APPEND VALUE #( %TKY = <FS_RESULT_ROUTE>-%TKY %MSG = NEW_MESSAGE(
                               ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                           NUMBER = '006'
                           V1 = <FS_RESULT_ROUTE>-SDATE
                           V2 = <FS_RESULT_ROUTE>-STIME
                         SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                         %ELEMENT-ROUTENAME = IF_ABAP_BEHV=>MK-ON ) TO REPORTED-ZI_PM_PRIDE_ROUTE__TEMP_M.

      ELSEIF <FS_RESULT_ROUTE>-ROUTESCHEDULE IS INITIAL.

        APPEND VALUE #( %TKY = <FS_RESULT_ROUTE>-%TKY %MSG = NEW_MESSAGE(
                               ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                           NUMBER = '008'
                           V1 = <FS_RESULT_ROUTE>-SDATE
                           V2 = <FS_RESULT_ROUTE>-STIME
                         SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                         %ELEMENT-ROUTESCHEDULE = IF_ABAP_BEHV=>MK-ON ) TO REPORTED-ZI_PM_PRIDE_ROUTE__TEMP_M.

      ELSEIF <FS_RESULT_ROUTE>-SDATE IS INITIAL.
        APPEND VALUE #( %TKY = <FS_RESULT_ROUTE>-%TKY %MSG = NEW_MESSAGE(
                         ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                     NUMBER = '022'
                     V1 = <FS_RESULT_ROUTE>-SDATE
                     V2 = <FS_RESULT_ROUTE>-STIME
                   SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                   %ELEMENT-SDATE = IF_ABAP_BEHV=>MK-ON ) TO REPORTED-ZI_PM_PRIDE_ROUTE__TEMP_M.

      ELSEIF <FS_RESULT_ROUTE>-LOCATION IS INITIAL.
        APPEND VALUE #( %TKY = <FS_RESULT_ROUTE>-%TKY %MSG = NEW_MESSAGE(
                               ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                           NUMBER = '011'
                           V1 = <FS_RESULT_ROUTE>-SDATE
                           V2 = <FS_RESULT_ROUTE>-STIME
                         SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                         %ELEMENT-LOCATION = IF_ABAP_BEHV=>MK-ON ) TO REPORTED-ZI_PM_PRIDE_ROUTE__TEMP_M.

      ELSEIF <FS_RESULT_ROUTE>-PLANT IS INITIAL.

        APPEND VALUE #( %TKY = <FS_RESULT_ROUTE>-%TKY %MSG = NEW_MESSAGE(
                               ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                           NUMBER = '007'
                           V1 = <FS_RESULT_ROUTE>-SDATE
                           V2 = <FS_RESULT_ROUTE>-STIME
                         SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                         %ELEMENT-PLANT = IF_ABAP_BEHV=>MK-ON ) TO REPORTED-ZI_PM_PRIDE_ROUTE__TEMP_M.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.

  METHOD MOVEACTUALDATE.
    READ ENTITY IN LOCAL MODE ZI_PM_PRIDE_ROUTE__TEMP_M
   ALL FIELDS WITH CORRESPONDING #( KEYS )
   RESULT DATA(LT_RT_DET) .

    LOOP AT LT_RT_DET ASSIGNING FIELD-SYMBOL(<FS_RT_DET>).
      DATA LV_TIME_CHAR TYPE CHAR6.

      LV_TIME_CHAR =  <FS_RT_DET>-ETIMEEVEN && '0000'.
      MOVE LV_TIME_CHAR TO <FS_RT_DET>-STime.
    ENDLOOP.

    MODIFY ENTITY  IN LOCAL MODE ZI_PM_PRIDE_ROUTE__TEMP_M
        UPDATE FIELDS ( STime )
        WITH VALUE #( FOR LV_KEY IN LT_RT_DET ( %TKY = LV_KEY-%TKY
                                      STime = LV_KEY-STime ) ) .
  ENDMETHOD.

ENDCLASS.
