CLASS LHC_ZI_PM_PRIDE_ROUTE_DET_TEMP DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.

  PRIVATE SECTION.

*    METHODS ADDEQUIPMENT FOR MODIFY
*      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_DET_TEMP_M~ADDEQUIPMENT RESULT RESULT.
    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_PM_PRIDE_ROUTE_DET_TEMP_M RESULT RESULT.
    METHODS VALIDATEEQUIPMENT FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR ZI_PM_PRIDE_ROUTE_DET_TEMP_M~VALIDATEEQUIPMENT.
    METHODS SETINITIALAPPROVALS FOR DETERMINE ON MODIFY
      IMPORTING KEYS FOR ZI_PM_PRIDE_ROUTE_DET_TEMP_M~SETINITIALAPPROVALS.
    METHODS GET_INSTANCE_FEATURES FOR INSTANCE FEATURES
      IMPORTING KEYS REQUEST REQUESTED_FEATURES FOR ZI_PM_PRIDE_ROUTE_DET_TEMP_M RESULT RESULT.

    METHODS ACTIVEEQ FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_DET_TEMP_M~ACTIVEEQ RESULT RESULT.

    METHODS INACTIVEEQ FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_DET_TEMP_M~INACTIVEEQ RESULT RESULT.
    METHODS UPDATEMP FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_DET_TEMP_M~UPDATEMP RESULT RESULT.

ENDCLASS.

CLASS LHC_ZI_PM_PRIDE_ROUTE_DET_TEMP IMPLEMENTATION.

*  METHOD ADDEQUIPMENT.
*    DATA LS_CREATE TYPE STRUCTURE FOR CREATE ZI_PM_PRIDE_ROUTE_DET_TEMP_M\_DETAILSMP.
*    DATA LT_CREATE_MP LIKE LS_CREATE-%TARGET.
*    DATA LS_CREATE_MP LIKE LINE OF LT_CREATE_MP.
*    DATA LT_GET_RESULT  TYPE TABLE FOR ACTION RESULT ZI_PM_PRIDE_ROUTE_DET_TEMP_M~ADDEQUIPMENT.
*    DATA LS_GET_RESULT LIKE LINE OF LT_GET_RESULT.
*    CLEAR: LT_CREATE_MP[].
*
*    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
*       ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
*       FIELDS ( EQUIPMENT ) WITH CORRESPONDING #( KEYS )
*       RESULT DATA(LT_EQUIPMENT)
*       BY \_DETAILSMP ALL FIELDS  WITH CORRESPONDING #( KEYS )
*       RESULT DATA(LT_MP)
*        FAILED FAILED.
*    .
**RESULT = CORRESPONDING VALUE #(  )
*    "MOVE-CORRESPONDING KEYS to RESULT.
*
*    LOOP AT LT_EQUIPMENT ASSIGNING FIELD-SYMBOL(<FS_ONCALL>).
*
*      SELECT EQUNR,MPOBJ,POINT,MRNGU FROM IMPTT
*        JOIN EQUI ON EQUI~OBJNR = IMPTT~MPOBJ
*        INTO TABLE @DATA(LT_MPOINT)
*        FOR ALL ENTRIES IN @LT_EQUIPMENT
*      WHERE EQUNR = @LT_EQUIPMENT-EQUIPMENT
*        .
**MOVE-CORRESPONDING KEYS to RESULT.
*
*      LS_GET_RESULT-%KEY = <FS_ONCALL>-%KEY.
*      MOVE-CORRESPONDING <FS_ONCALL> TO LS_GET_RESULT-%PARAM.
*      APPEND LS_GET_RESULT TO RESULT.
*
*      LOOP AT LT_MPOINT ASSIGNING FIELD-SYMBOL(<FS_MP>).
**        READ ENTITY IN LOCAL MODE ZI_PM_PRIDE_ROUTE_MP_TEMP_M
**          FIELDS ( MEASUREPOINT )
**          WITH VALUE #( %KEY-MeasurePoint = <FS_MP>-POINT %KEY-Equipment = <FS_ONCALL>-Equipment %KEY-FuncLoc = <FS_ONCALL>-FuncLoc %KEY-RouteId = <FS_ONCALL>-RouteId )
**          RESULT DATA(LS_MP).
**
**        IF LS_MP IS INITIAL.
*        READ TABLE LT_MP ASSIGNING FIELD-SYMBOL(<FS_MP_CHK>) WITH KEY MEASUREPOINT = <FS_MP>-POINT.
*        IF SY-SUBRC = 0.
*        ELSE.
*
*          LS_CREATE_MP =  VALUE #( %CID = <FS_MP>-POINT
*                                            MEASUREPOINT = <FS_MP>-POINT
*                                            VALUE = '0'
*                                            UOM = <FS_MP>-MRNGU
*                                          %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
*                                          %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON
*                                          %CONTROL-UOM = IF_ABAP_BEHV=>MK-ON
*
*                                          ) .
*          MOVE <FS_ONCALL>-EQUIPMENT TO LS_CREATE_MP-EQUIPMENT.
*          MOVE <FS_ONCALL>-FUNCLOC TO LS_CREATE_MP-FUNCLOC.
*          MOVE <FS_ONCALL>-ROUTEID TO LS_CREATE_MP-ROUTEID.
*          APPEND LS_CREATE_MP  TO  LT_CREATE_MP.
*        ENDIF.
*        "        ENDIF.
*      ENDLOOP..
*      IF LT_CREATE_MP IS NOT INITIAL.
*        MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
*
*           ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
*           CREATE BY \_DETAILSMP
*                    FROM VALUE #( ( %KEY = <FS_ONCALL>-%KEY
*                    %TARGET = LT_CREATE_MP   ) )
**                  %TARGET = VALUE #( ( %CID = 'CID_DUMMY'
**                                    MEASUREPOINT = 'USER01'
**                                  %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
**                                  VALUE = '0'
**                                  %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON ) ) ) )
*        MAPPED MAPPED
*        "MAPPED DATA(LT_MAPPED)
*        FAILED FAILED "
*       "FAILED DATA(LT_FAILED)
*       "REPORTED DATA(LT_REPORTED).
*        REPORTED REPORTED.
*        . "DATA(LT_REPORTED).
*        "MAPPED = LT_MAPPED.
*      ENDIF.
*    ENDLOOP.
*  ENDMETHOD.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD VALIDATEEQUIPMENT.
*    DATA LT_EQUI TYPE SORTED TABLE OF EQUI WITH UNIQUE KEY EQUNR.

    READ ENTITY IN LOCAL MODE ZI_PM_PRIDE_ROUTE_DET_TEMP_M
    FIELDS ( EQUIPMENT )
    WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_ROUTE_DET).

    DATA(LT_EQUI) = LT_ROUTE_DET[].

*    LT_EQUI = CORRESPONDING #( LT_ROUTE_DET DISCARDING DUPLICATES MAPPING EQUNR = EQUIPMENT ).
    SORT LT_EQUI BY EQUIPMENT DESCENDING.
    DELETE ADJACENT DUPLICATES FROM LT_EQUI COMPARING EQUIPMENT.

    IF LT_EQUI IS NOT INITIAL.

*      SELECT FROM EQUI
*      FIELDS ( EQUNR )
*      FOR ALL ENTRIES IN @LT_EQUI
*      WHERE EQUNR = @LT_EQUI-EQUNR
*      INTO TABLE @DATA(LT_EQUIP).

      SELECT FROM ZICDS_PM_FUNCLOCATION_DET
        FIELDS ( TECHOBJECT  )
            FOR ALL ENTRIES IN @LT_EQUI
    WHERE TECHOBJECT = @LT_EQUI-EQUIPMENT
    INTO TABLE @DATA(LT_EQUIP).
*                INTO TABLE @DATA(LT_MPOINT_FL).

    ENDIF.

    LOOP AT LT_ROUTE_DET ASSIGNING FIELD-SYMBOL(<FS_ROUTE_DET>).

      IF <FS_ROUTE_DET>-EQUIPMENT IS INITIAL OR NOT
      LINE_EXISTS( LT_EQUIP[ TECHOBJECT = <FS_ROUTE_DET>-EQUIPMENT ] ).
        APPEND VALUE #( %TKY = <FS_ROUTE_DET>-%TKY ) TO FAILED-ZI_PM_PRIDE_ROUTE_DET_TEMP_M.
        APPEND VALUE #( %TKY = <FS_ROUTE_DET>-%TKY
        %MSG        = NEW_MESSAGE(
                                 ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                             NUMBER = '000'
                             V1 = <FS_ROUTE_DET>-EQUIPMENT
                           SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
        %ELEMENT-EQUIPMENT = IF_ABAP_BEHV=>MK-ON   ) TO REPORTED-ZI_PM_PRIDE_ROUTE_DET_TEMP_M.

      ELSEIF <FS_ROUTE_DET>-FREQUENCY IS INITIAL.
        APPEND VALUE #( %TKY = <FS_ROUTE_DET>-%TKY ) TO FAILED-ZI_PM_PRIDE_ROUTE_DET_TEMP_M.
        APPEND VALUE #( %TKY = <FS_ROUTE_DET>-%TKY
        %MSG        = NEW_MESSAGE(
                                 ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                             NUMBER = '012'
                             V1 = <FS_ROUTE_DET>-FREQUENCY
                           SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
        %ELEMENT-FREQUENCY = IF_ABAP_BEHV=>MK-ON   ) TO REPORTED-ZI_PM_PRIDE_ROUTE_DET_TEMP_M.
      ELSE.
*        READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
*            ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
*            FIELDS ( EQUIPMENT ) WITH CORRESPONDING #( KEYS )
*            RESULT DATA(LT_EQUIPMENT).
*        LOOP AT LT_EQUIPMENT ASSIGNING FIELD-SYMBOL(<FS_ONCALL>).
*
*          MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
*
*             ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
*             CREATE BY \_DETAILSMP
*                      FROM VALUE #( ( %KEY = <FS_ONCALL>-%KEY
*                      %TARGET = VALUE #( ( %CID = 'CID_DUMMY'
*                                        MEASUREPOINT = 'USER01'
*                                      %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
*                                      VALUE = '0'
*                                      %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON ) ) ) )
*             MAPPED DATA(LT_MAPPED)
*             FAILED DATA(LT_FAILED)
*             REPORTED DATA(LT_REPORTED).
*             ENDLOOP.
      ENDIF.

    ENDLOOP.




  ENDMETHOD.

  METHOD SETINITIALAPPROVALS.
    DATA LS_CREATE TYPE STRUCTURE FOR CREATE ZI_PM_PRIDE_ROUTE_DET_TEMP_M\_DETAILSMP.
    DATA LT_CREATE_MP LIKE LS_CREATE-%TARGET.
    DATA LS_CREATE_MP LIKE LINE OF LT_CREATE_MP.
    DATA LT_ROUTE_DET TYPE TABLE FOR UPDATE ZI_PM_PRIDE_ROUTE_DET_TEMP_M.
    DATA LS_ROUTE_DET LIKE LINE OF LT_ROUTE_DET.
    CLEAR: LT_CREATE_MP[].

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
       ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
       FIELDS ( EQUIPMENT ) WITH CORRESPONDING #( KEYS )
       RESULT DATA(LT_EQUIPMENT).

    LOOP AT LT_EQUIPMENT ASSIGNING FIELD-SYMBOL(<FS_ONCALL>).

      IF <FS_ONCALL>-EQUIPMENT = '' OR <FS_ONCALL>-EQUIPMENT IS INITIAL.
*        SELECT EQUI~EQUNR,MPOBJ,POINT,MRNGU,FL~TPLNR FROM IMPTT
*          JOIN EQUI ON EQUI~OBJNR = IMPTT~MPOBJ
*          LEFT OUTER JOIN ZI_PM_EQUIPMENT_TXT_R AS FL ON FL~EQUNR = EQUI~EQUNR
*          FOR ALL ENTRIES IN @LT_EQUIPMENT
*        WHERE EQUI~EQUNR = @LT_EQUIPMENT-Equipment
*                INTO TABLE @DATA(LT_MPOINT)
        .
      ELSE.

        SELECT TECHOBJECT,TEXT,MPOBJ,POINT,MRNGU,OBJECT FROM ZICDS_PM_FUNCLOCATION_DET
        WHERE TECHOBJECT = @<FS_ONCALL>-EQUIPMENT
                INTO TABLE @DATA(LT_MPOINT_FL).

        SELECT SINGLE * FROM ZPM_PRIDE_RDET_T
        INTO @DATA(LS_EQUI)
        WHERE EQUIPMENT = @<FS_ONCALL>-EQUIPMENT
        AND ACTIVE = 'X'.
        IF SY-SUBRC = 0.
*          APPEND VALUE #( %TKY = <FS_ONCALL>-%TKY ) TO FAILED-ZI_PM_PRIDE_ROUTE_DET_TEMP_M.
          APPEND VALUE #( %TKY = <FS_ONCALL>-%TKY
          %MSG        = NEW_MESSAGE(
                                   ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
                               NUMBER = '014'
                               V1 = LS_EQUI-EQUIPMENT
                               V2 = LS_EQUI-ROUTE_ID
                             SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
          %ELEMENT-FREQUENCY = IF_ABAP_BEHV=>MK-ON   ) TO REPORTED-ZI_PM_PRIDE_ROUTE_DET_TEMP_M.

          CONTINUE.
        ENDIF.

      ENDIF.
      CLEAR LT_CREATE_MP.
      CLEAR LT_ROUTE_DET.
      LOOP AT LT_MPOINT_FL ASSIGNING FIELD-SYMBOL(<FS_MP>).

        DATA(LV_FL) = <FS_MP>-TECHOBJECT.

        LS_CREATE_MP =  VALUE #( %CID = SY-TABIX
                                          MEASUREPOINT = <FS_MP>-POINT
                                          VALUE = '0'
                                          UOM = <FS_MP>-MRNGU
                                          ISACTIVE = 'X'
                                          FUNCLOC = <FS_MP>-TECHOBJECT
                                        %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
                                        %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON
                                        %CONTROL-UOM = IF_ABAP_BEHV=>MK-ON
                                        %CONTROL-ISACTIVE = IF_ABAP_BEHV=>MK-ON
                                        %CONTROL-FUNCLOC = IF_ABAP_BEHV=>MK-ON
                                        ) .
        APPEND LS_CREATE_MP  TO  LT_CREATE_MP.
      ENDLOOP..
      LOOP AT KEYS ASSIGNING FIELD-SYMBOL(<FS_KEY>).
        MOVE-CORRESPONDING  LS_CREATE_MP TO LS_ROUTE_DET.
        MOVE-CORRESPONDING  <FS_KEY> TO LS_ROUTE_DET.
        LS_ROUTE_DET-FUNCLOC = LV_FL.
        LS_ROUTE_DET-ISACTIVE = 'X'.
        "        LS_ROUTE_DET-%KEY-FuncLoc = LS_ROUTE_DET-FUNCLOC.
        APPEND LS_ROUTE_DET TO LT_ROUTE_DET.
      ENDLOOP.
      CLEAR LV_FL.

      MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE

         ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
         UPDATE FIELDS ( FUNCLOC ISACTIVE ) WITH LT_ROUTE_DET
         CREATE BY \_DETAILSMP
                  FROM VALUE #( ( %KEY = <FS_ONCALL>-%KEY "LS_CREATE_MP-%KEY
                  %TARGET = LT_CREATE_MP   ) )
*                  %TARGET = VALUE #( ( %CID = 'CID_DUMMY'
*                                    MEASUREPOINT = 'USER01'
*                                  %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
*                                  VALUE = '0'
*                                  %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON ) ) ) )
      MAPPED DATA(LT_MAPPED)
      FAILED DATA(LT_FAILED)
      REPORTED DATA(LT_REPORTED).
    ENDLOOP.
  ENDMETHOD.

  METHOD GET_INSTANCE_FEATURES.

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
    FIELDS ( EQUIPMENT ISACTIVE ) WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RESULT).

    RESULT  = VALUE #( FOR LV_RT_D IN LT_RESULT (  %TKY = LV_RT_D-%TKY
                                                   %FEATURES-%ACTION-ACTIVEEQ = COND #( WHEN LV_RT_D-ISACTIVE = ' '
                                                                                        THEN IF_ABAP_BEHV=>MK-OFF
                                                                                        WHEN LV_RT_D-ISACTIVE = 'X'
                                                                                        THEN IF_ABAP_BEHV=>MK-ON   )
                                                   %FEATURES-%ACTION-INACTIVEEQ = COND #( WHEN LV_RT_D-ISACTIVE = 'X'
                                                                                        THEN IF_ABAP_BEHV=>MK-OFF
                                                                                        WHEN LV_RT_D-ISACTIVE = ' '
                                                                                        THEN IF_ABAP_BEHV=>MK-ON   )                                                                                           ) ).

  ENDMETHOD.

  METHOD ACTIVEEQ.

    MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M UPDATE FIELDS ( ISACTIVE )
    WITH VALUE #( FOR LV_KEY IN KEYS ( %TKY = LV_KEY-%TKY
                                        ISACTIVE = 'X') ).

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RT_DET).

    RESULT = VALUE #( FOR LS_RT_DET IN LT_RT_DET ( %TKY = LS_RT_DET-%TKY
    %PARAM = LS_RT_DET ) ).

  ENDMETHOD.

  METHOD INACTIVEEQ.
    MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
  ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M UPDATE FIELDS ( ISACTIVE )
  WITH VALUE #( FOR LV_KEY IN KEYS ( %TKY = LV_KEY-%TKY
                                      ISACTIVE = ' ') ).

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RT_DET).

    RESULT = VALUE #( FOR LS_RT_DET IN LT_RT_DET ( %TKY = LS_RT_DET-%TKY
    %PARAM = LS_RT_DET ) ).
  ENDMETHOD.

  METHOD UPDATEMP.
    DATA LS_CREATE TYPE STRUCTURE FOR CREATE ZI_PM_PRIDE_ROUTE_DET_TEMP_M\_DETAILSMP.
    DATA LT_CREATE_MP LIKE LS_CREATE-%TARGET.
    DATA LS_CREATE_MP LIKE LINE OF LT_CREATE_MP.
    DATA LT_GET_RESULT  TYPE TABLE FOR ACTION RESULT ZI_PM_PRIDE_ROUTE_DET_TEMP_M~UPDATEMP.
    DATA LS_GET_RESULT LIKE LINE OF LT_GET_RESULT.
    CLEAR: LT_CREATE_MP[].

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
       ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
       FIELDS ( EQUIPMENT FUNCLOC ) WITH CORRESPONDING #( KEYS )
       RESULT DATA(LT_EQUIPMENT)
       BY \_DETAILSMP ALL FIELDS  WITH CORRESPONDING #( KEYS )
       RESULT DATA(LT_MP)
        FAILED FAILED.

    LOOP AT LT_EQUIPMENT ASSIGNING FIELD-SYMBOL(<FS_ONCALL>).

*      SELECT EQUNR,MPOBJ,POINT,MRNGU,MRMIN,MRMINI,MRMAX,MRMAXI,DECIM FROM IMPTT
*        JOIN EQUI ON EQUI~OBJNR = IMPTT~MPOBJ
*        INTO TABLE @DATA(LT_MPOINT)
*        FOR ALL ENTRIES IN @LT_EQUIPMENT
*        WHERE EQUNR = @LT_EQUIPMENT-EQUIPMENT.

      SELECT TECHOBJECT,TEXT,MPOBJ,POINT,MRNGU,OBJECT,MRMIN,MRMAX,DECIM,MRMINI,MRMAXI
      FROM ZICDS_PM_FUNCLOCATION_DET
      WHERE TECHOBJECT = @<FS_ONCALL>-EQUIPMENT
              INTO TABLE @DATA(LT_MPOINT).

      LS_GET_RESULT-%KEY = <FS_ONCALL>-%KEY.
      MOVE-CORRESPONDING <FS_ONCALL> TO LS_GET_RESULT-%PARAM.
      APPEND LS_GET_RESULT TO RESULT.

      LOOP AT LT_MPOINT ASSIGNING FIELD-SYMBOL(<FS_MP>).

        READ TABLE LT_MP ASSIGNING FIELD-SYMBOL(<FS_MP_CHK>) WITH KEY MEASUREPOINT = <FS_MP>-POINT.
        IF SY-SUBRC = 0.
        ELSE.

          ZCL_PM_PRIDE=>CONVERT_READING(
            EXPORTING
              IV_MIN    = <FS_MP>-MRMIN
              IV_MRNGU  = <FS_MP>-MRNGU
              IV_DECIM  = <FS_MP>-DECIM
              IV_VALUEI = <FS_MP>-MRMINI
            IMPORTING
              EV_VALUE  = DATA(LV_LOW)
          ).

          ZCL_PM_PRIDE=>CONVERT_READING(
            EXPORTING
              IV_MIN    = <FS_MP>-MRMAX
              IV_MRNGU  = <FS_MP>-MRNGU
              IV_DECIM  = <FS_MP>-DECIM
              IV_VALUEI = <FS_MP>-MRMAXI
            IMPORTING
              EV_VALUE  = DATA(LV_HIGH)
          ).

          CLEAR: LV_LOW,LV_HIGH.

          LS_CREATE_MP =  VALUE #( %CID = <FS_MP>-POINT
                                            MEASUREPOINT = <FS_MP>-POINT
                                            VALUE = '0'
                                            UOM = <FS_MP>-MRNGU
                                            ISACTIVE = 'X'
                                            HIGHLIMIT = LV_HIGH
                                            LOWLIMIT = LV_LOW
                                          %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
                                          %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON
                                          %CONTROL-UOM = IF_ABAP_BEHV=>MK-ON
                                          %CONTROL-ISACTIVE = IF_ABAP_BEHV=>MK-ON
                                          %CONTROL-HIGHLIMIT = IF_ABAP_BEHV=>MK-ON
                                          %CONTROL-LOWLIMIT = IF_ABAP_BEHV=>MK-ON
                                          %CONTROL-FUNCLOC = IF_ABAP_BEHV=>MK-ON
                                          ) .
          MOVE <FS_ONCALL>-EQUIPMENT TO LS_CREATE_MP-EQUIPMENT.
          MOVE <FS_ONCALL>-FUNCLOC TO LS_CREATE_MP-FUNCLOC.
          MOVE <FS_ONCALL>-ROUTEID TO LS_CREATE_MP-ROUTEID.
          APPEND LS_CREATE_MP  TO  LT_CREATE_MP.
        ENDIF.
        "        ENDIF.
      ENDLOOP..
      IF LT_CREATE_MP IS NOT INITIAL.
        MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE

           ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
           CREATE BY \_DETAILSMP
                    FROM VALUE #( ( %KEY = <FS_ONCALL>-%KEY
                    %TARGET = LT_CREATE_MP   ) )

        MAPPED MAPPED
        FAILED FAILED
        REPORTED REPORTED.

      ENDIF.
    ENDLOOP.
  ENDMETHOD.

ENDCLASS.

*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations
