CLASS LHC_ZI_PM_PRIDE_ROUTE_MP_TEMP_ DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.

  PRIVATE SECTION.

*    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
*      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_PM_PRIDE_ROUTE_MP_TEMP_M RESULT RESULT.

*    METHODS ACTIVEMP FOR MODIFY
*      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_MP_TEMP_M~ACTIVEMP RESULT RESULT.
*
*    METHODS INACTIVEMP FOR MODIFY
*      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_MP_TEMP_M~INACTIVEMP RESULT RESULT.

*    METHODS UPDATEMP FOR MODIFY
*      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_MP_TEMP_M~UPDATEMP RESULT RESULT.
*    METHODS SETINITIALAPPROVALS FOR DETERMINE ON MODIFY
*      IMPORTING KEYS FOR ZI_PM_PRIDE_ROUTE_MP_TEMP_M~SETINITIALAPPROVALS.
    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_PM_PRIDE_ROUTE_MP_TEMP_M RESULT RESULT.

    METHODS ACTIVEMP FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_MP_TEMP_M~ACTIVEMP RESULT RESULT.
    METHODS GET_INSTANCE_FEATURES FOR INSTANCE FEATURES
      IMPORTING KEYS REQUEST REQUESTED_FEATURES FOR ZI_PM_PRIDE_ROUTE_MP_TEMP_M RESULT RESULT.

    METHODS INACTIVEMP FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_MP_TEMP_M~INACTIVEMP RESULT RESULT.
    METHODS REQUIREDMP FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_PM_PRIDE_ROUTE_MP_TEMP_M~REQUIREDMP RESULT RESULT.

ENDCLASS.

CLASS LHC_ZI_PM_PRIDE_ROUTE_MP_TEMP_ IMPLEMENTATION.

*  METHOD GET_INSTANCE_AUTHORIZATIONS.
*  ENDMETHOD.
**
*  METHOD ACTIVEMP.
*    DATA LT_EQUI TYPE SORTED TABLE OF EQUI WITH UNIQUE KEY EQUNR.
*
*    READ ENTITY IN LOCAL MODE ZI_PM_PRIDE_ROUTE_DET_TEMP_M
*    FIELDS ( EQUIPMENT )
*    WITH CORRESPONDING #( KEYS )
*    RESULT DATA(LT_ROUTE_DET).
*
*    LT_EQUI = CORRESPONDING #( LT_ROUTE_DET DISCARDING DUPLICATES MAPPING EQUNR = EQUIPMENT ).
*
*    IF LT_EQUI IS NOT INITIAL.
*
*      SELECT FROM EQUI
*      FIELDS ( EQUNR )
*      FOR ALL ENTRIES IN @LT_EQUI
*      WHERE EQUNR = @LT_EQUI-EQUNR
*      INTO TABLE @DATA(LT_EQUIP).
*    ENDIF.
*
*    LOOP AT LT_ROUTE_DET ASSIGNING FIELD-SYMBOL(<FS_ROUTE_DET>).
*
*      IF <FS_ROUTE_DET>-EQUIPMENT IS INITIAL OR NOT
*      LINE_EXISTS( LT_EQUIP[ EQUNR = <FS_ROUTE_DET>-EQUIPMENT ] ).
*        APPEND VALUE #( %TKY = <FS_ROUTE_DET>-%TKY ) TO FAILED-ZI_PM_PRIDE_ROUTE_DET_TEMP_M.
*        APPEND VALUE #( %TKY = <FS_ROUTE_DET>-%TKY
*        %MSG        = NEW_MESSAGE(
*                                 ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
*                             NUMBER = '000'
*                             V1 = <FS_ROUTE_DET>-EQUIPMENT
*                           SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
*        %ELEMENT-EQUIPMENT = IF_ABAP_BEHV=>MK-ON   ) TO REPORTED-ZI_PM_PRIDE_ROUTE_DET_TEMP_M.
*
*      ELSE.
**        READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
**            ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
**            FIELDS ( EQUIPMENT ) WITH CORRESPONDING #( KEYS )
**            RESULT DATA(LT_EQUIPMENT).
**        LOOP AT LT_EQUIPMENT ASSIGNING FIELD-SYMBOL(<FS_ONCALL>).
**
**          MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
**
**             ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
**             CREATE BY \_DETAILSMP
**                      FROM VALUE #( ( %KEY = <FS_ONCALL>-%KEY
**                      %TARGET = VALUE #( ( %CID = 'CID_DUMMY'
**                                        MEASUREPOINT = 'USER01'
**                                      %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
**                                      VALUE = '0'
**                                      %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON ) ) ) )
**             MAPPED DATA(LT_MAPPED)
**             FAILED DATA(LT_FAILED)
**             REPORTED DATA(LT_REPORTED).
**             ENDLOOP.
*      ENDIF.
*
*    ENDLOOP.
*  ENDMETHOD.
*
*  METHOD INACTIVEMP.
*  ENDMETHOD.
*
*  METHOD UPDATEMP.
*  ENDMETHOD.

*  METHOD SETINITIALAPPROVALS.
*    DATA LS_CREATE TYPE STRUCTURE FOR CREATE ZI_PM_PRIDE_ROUTE_DET_TEMP_M\_DETAILSMP.
*    DATA LT_CREATE_MP LIKE LS_CREATE-%TARGET.
*    DATA LS_CREATE_MP LIKE LINE OF LT_CREATE_MP.
*
*    CLEAR: LT_CREATE_MP[].
*
*    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
*       ENTITY ZI_PM_PRIDE_ROUTE_DET_TEMP_M
*       FIELDS ( EQUIPMENT ) WITH CORRESPONDING #( KEYS )
*       RESULT DATA(LT_EQUIPMENT).
*    LOOP AT LT_EQUIPMENT ASSIGNING FIELD-SYMBOL(<FS_ONCALL>).
*
*      SELECT EQUNR,MPOBJ,POINT,MRNGU FROM IMPTT
*        JOIN EQUI ON EQUI~OBJNR = IMPTT~MPOBJ
*        INTO TABLE @DATA(LT_MPOINT)
*        FOR ALL ENTRIES IN @LT_EQUIPMENT
*      WHERE EQUNR = @LT_EQUIPMENT-EQUIPMENT
*        .
*
*
*      LOOP AT LT_MPOINT ASSIGNING FIELD-SYMBOL(<FS_MP>).
*        LS_CREATE_MP =  VALUE #( %CID = SY-TABIX
*                                          MEASUREPOINT = <FS_MP>-POINT
*                                          VALUE = '0'
*                                          UOM = <FS_MP>-MRNGU
*                                        %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
*                                        %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON
*                                        %CONTROL-UOM = IF_ABAP_BEHV=>MK-ON
*
*                                        ) .
*        APPEND LS_CREATE_MP  TO  LT_CREATE_MP.
*      ENDLOOP..
*      MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
*
*         ENTITY  ZI_PM_PRIDE_ROUTE_MP_TEMP_M
* "        CREATE BY \_DETAILSMP
*         UPDATE FIELDS ( VALUE ) WITH VALUE #( FOR <WA_NAME> IN KEYS ( %TKY = <WA_NAME>-%TKY VALUE = ' ' ) )
**                  %TARGET = VALUE #( ( %CID = 'CID_DUMMY'
**                                    MEASUREPOINT = 'USER01'
**                                  %CONTROL-MEASUREPOINT = IF_ABAP_BEHV=>MK-ON
**                                  VALUE = '0'
**                                  %CONTROL-VALUE = IF_ABAP_BEHV=>MK-ON ) ) ) )
*      MAPPED DATA(LT_MAPPED)
*      FAILED DATA(LT_FAILED)
*      REPORTED DATA(LT_REPORTED).
*
*
*
*      REPORTED-ZI_PM_PRIDE_ROUTE_MP_TEMP_M = VALUE #( FOR LS_KEY IN KEYS ( %TKY = LS_KEY-%TKY %MSG = NEW_MESSAGE(
*                                   ID = ZCL_PM_PRIDE_CONSTANTS=>C_MESSAGEID
*                               NUMBER = '000'
*                               V1 = LS_KEY-MeasurePoint
*                             SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-SUCCESS ) %ELEMENT-%FIELD-MeasurePoint = IF_ABAP_BEHV=>MK-ON )  ).
*
*      MOVE-CORRESPONDING LT_REPORTED-ZI_PM_PRIDE_ROUTE_MP_TEMP_M TO REPORTED-ZI_PM_PRIDE_ROUTE_MP_TEMP_M.
*
*    ENDLOOP.
*  ENDMETHOD.

  METHOD GET_INSTANCE_AUTHORIZATIONS.

  ENDMETHOD.

  METHOD ACTIVEMP.
    MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
  ENTITY ZI_PM_PRIDE_ROUTE_MP_TEMP_M UPDATE FIELDS ( ISACTIVE )
  WITH VALUE #( FOR LV_KEY IN KEYS ( %TKY = LV_KEY-%TKY
                                      ISACTIVE = 'X') ).

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE_MP_TEMP_M
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RT_DET).

    RESULT = VALUE #( FOR LS_RT_DET IN LT_RT_DET ( %TKY = LS_RT_DET-%TKY
    %PARAM = LS_RT_DET ) ).
  ENDMETHOD.


  METHOD GET_INSTANCE_FEATURES.
    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
   ENTITY ZI_PM_PRIDE_ROUTE_MP_TEMP_M
   FIELDS ( MEASUREPOINT ISACTIVE ) WITH CORRESPONDING #( KEYS )
   RESULT DATA(LT_RESULT).

    RESULT  = VALUE #( FOR LV_RT_D IN LT_RESULT (  %TKY = LV_RT_D-%TKY
                                                   %FEATURES-%ACTION-ACTIVEMP = COND #( WHEN LV_RT_D-ISACTIVE = ' '
                                                                                        THEN IF_ABAP_BEHV=>MK-OFF
                                                                                        WHEN LV_RT_D-ISACTIVE = 'R'
                                                                                        THEN IF_ABAP_BEHV=>MK-OFF
                                                                                        WHEN LV_RT_D-ISACTIVE = 'X'
                                                                                        THEN IF_ABAP_BEHV=>MK-ON   )
                                                   %FEATURES-%ACTION-INACTIVEMP = COND #( WHEN LV_RT_D-ISACTIVE = 'X'
                                                                                        THEN IF_ABAP_BEHV=>MK-OFF
                                                                                        WHEN LV_RT_D-ISACTIVE = 'R'
                                                                                        THEN IF_ABAP_BEHV=>MK-OFF
                                                                                        WHEN LV_RT_D-ISACTIVE = ' '
                                                                                        THEN IF_ABAP_BEHV=>MK-ON   )                                                                                           ) ).

  ENDMETHOD.

  METHOD INACTIVEMP.
    MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
ENTITY ZI_PM_PRIDE_ROUTE_MP_TEMP_M UPDATE FIELDS ( ISACTIVE )
WITH VALUE #( FOR LV_KEY IN KEYS ( %TKY = LV_KEY-%TKY
                                    ISACTIVE = ' ') ).

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE_MP_TEMP_M
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RT_DET).

    RESULT = VALUE #( FOR LS_RT_DET IN LT_RT_DET ( %TKY = LS_RT_DET-%TKY
    %PARAM = LS_RT_DET ) ).
  ENDMETHOD.

  METHOD REQUIREDMP.
    MODIFY ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
ENTITY ZI_PM_PRIDE_ROUTE_MP_TEMP_M UPDATE FIELDS ( ISACTIVE )
WITH VALUE #( FOR LV_KEY IN KEYS ( %TKY = LV_KEY-%TKY
                                    ISACTIVE = 'R') ).

    READ ENTITIES OF ZI_PM_PRIDE_ROUTE__TEMP_M IN LOCAL MODE
    ENTITY ZI_PM_PRIDE_ROUTE_MP_TEMP_M
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_RT_DET).

    RESULT = VALUE #( FOR LS_RT_DET IN LT_RT_DET ( %TKY = LS_RT_DET-%TKY
    %PARAM = LS_RT_DET ) ).
  ENDMETHOD.

ENDCLASS.

*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations
