CLASS ZCL_BDL_READ_PRACTICE DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES IF_OO_ADT_CLASSRUN.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_BDL_READ_PRACTICE IMPLEMENTATION.

  METHOD IF_OO_ADT_CLASSRUN~MAIN.
*/ Read Entity
    READ ENTITY ZI_PM_PRIDE_ROUTE_M ALL FIELDS WITH VALUE #( ( %KEY-ROUTENAME = 'ROUTE_BADIN_1'
    %KEY-ROUTEID = '1'
    %KEY-LOCATION = 'BD'
    %KEY-SDATE = '20240802'
    %KEY-STIME = '120000'
    %KEY-EDATE = '20240802'
    %KEY-ETIME = '120000'

    ) )
    RESULT DATA(LT_RESULT_SORT)
    FAILED DATA(LT_FAILED_SORT).

    IF LT_FAILED_SORT IS NOT INITIAL.
      OUT->WRITE( 'Read Failed' ).
      OUT->WRITE( LT_FAILED_SORT ).
    ELSE.
      OUT->WRITE( LT_RESULT_SORT ).
    ENDIF.

  ENDMETHOD.

ENDCLASS.
