class ZCL_IBAPI_ALM_ORD_MODIFY definition
  public
  final
  create public .

public section.

  interfaces IF_BADI_INTERFACE .
  interfaces IF_EX_IBAPI_ALM_ORD_MODIFY .
protected section.
private section.
ENDCLASS.



CLASS ZCL_IBAPI_ALM_ORD_MODIFY IMPLEMENTATION.


  METHOD IF_EX_IBAPI_ALM_ORD_MODIFY~MODIFY_INPUT_DATA.
    DATA LS_STRUC TYPE EAM_ORD_MASS_CHANGE.
    DATA LV_LIFNR TYPE LIFNR.
    MOVE EXTENSION_IN-VALUEPART1 TO LS_STRUC.
    BREAK AMAHMOOD.
    IF LS_STRUC-FIELDNAME = 'ZWEEK_CODE'.
      LV_LIFNR = LS_STRUC-NEW_VALUE.
    ENDIF.

    DATA: LS_HEADER_INT     TYPE CAUFVD,
          LC_CUORDER_HEADER TYPE DDOBJNAME VALUE 'EAM_ORD_MASS_CHANGE'.

    IF EXTENSION_IN-STRUCTURE = LC_CUORDER_HEADER.
      CHECK NOT CT_HEADER_INT[] IS INITIAL.
      CLEAR LS_HEADER_INT.
      READ TABLE CT_HEADER_INT INTO LS_HEADER_INT INDEX 1.
      IF SY-SUBRC IS INITIAL.
        DATA(LV_TABIX) = SY-TABIX.

        READ TABLE CT_HEADER_INT_UP ASSIGNING FIELD-SYMBOL(<LS_OPERATION_UP>) INDEX LV_TABIX.
        CHECK SY-SUBRC EQ 0.
        MOVE: LV_LIFNR TO LS_HEADER_INT-ZWEEK_CODE.
        select SINGLE ZWEEK_DESC from ZTPM0005 into LS_HEADER_INT-ZWEEK_DESC WHERE ZWEEK_CODE = LS_HEADER_INT-ZWEEK_CODE.
        <LS_OPERATION_UP>-ZWEEK_CODE = ABAP_TRUE.
        <LS_OPERATION_UP>-ZWEEK_DESC = ABAP_TRUE.

*              EXTENSION_IN-VALUEPART2 TO LS_HEADER_INT-/CUM/CMNUM,
*              EXTENSION_IN-VALUEPART3 TO LS_HEADER_INT-/CUM/DESNUM,
*              EXTENSION_IN-VALUEPART4 TO LS_HEADER_INT-/CUM/AUEST.
        MODIFY CT_HEADER_INT FROM LS_HEADER_INT INDEX SY-TABIX.
        REFRESH CT_MESSAGES[].
      ENDIF.
    ENDIF.
  ENDMETHOD.
ENDCLASS.
