CLASS ZCL_PM_PRIDE DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    TYPES:
      BEGIN OF TY_MP.
        INCLUDE TYPE ZI_PM_PRIDE_ROUTE_MP_M.
  TYPES END OF TY_MP .

    TYPES:
      TT_MP TYPE TABLE OF TY_MP .

    TYPES:
      TT_DET TYPE TABLE OF ZI_PM_PRIDE_ROUTE_DET_M .

*    TYPES:
*      TT_MP TYPE TABLE OF TY_MP .

    CLASS-METHODS CREATE_WITH_REF
      IMPORTING
        !ROUTE_ID     TYPE ZPM_PRD_RID
        !START_DATE   TYPE ZPM_PRD_SDATE
        !SCHEDULE     TYPE ZPM_PRD_SCHD
        !START_TIME   TYPE ZPM_PRD_STIME
      EXPORTING
        !NEW_ROUTE_ID TYPE ZPM_PRD_RID .
    CLASS-METHODS GET_NEW_NUMBER
      RETURNING
        VALUE(NUMBER) TYPE NR_NUMBER .
    CLASS-METHODS CREATE_WITH_TEMPLATE
      IMPORTING
        !ROUTE_ID     TYPE ZPM_PRD_RID
        !START_DATE   TYPE ZPM_PRD_SDATE
        !SCHEDULE     TYPE ZPM_PRD_SCHD
        !START_TIME   TYPE ZPM_PRD_STIME
      EXPORTING
        !NEW_ROUTE_ID TYPE ZPM_PRD_RID .
    CLASS-METHODS CONVERT_READING
      IMPORTING
        !IV_MIN    TYPE IMRC_MRMIN
        !IV_MRNGU  TYPE IMRC_MRNGU
        !IV_DECIM  TYPE IMRC_DECIM
        !IV_VALUEI TYPE IVALU
      EXPORTING
        !EV_VALUE  TYPE ZPM_PRD_MAX .
    CLASS-METHODS CALCULATE_SCHEDULE_MIN
      IMPORTING
        VALUE(SCHEDULE)   TYPE ZPM_PRD_SCHD
      EXPORTING
        VALUE(EV_MINUTES) TYPE INT4 .
    CLASS-METHODS GET_MP_FORMULA
      IMPORTING
        VALUE(IV_ROUTEID) TYPE ZPM_PRD_RID
        VALUE(IV_VALUE)   TYPE CHAR16
        VALUE(IV_MP)      TYPE IMRC_POINT
      EXPORTING
        VALUE(EV_VALUE)   TYPE CHAR16 .
    CLASS-METHODS GET_FORMULA_TEXT
      IMPORTING
        !IV_DATE         TYPE DATUM
        !IV_TIME         TYPE UZEIT
        !IV_EQUIPMENT    TYPE EQUNR
      EXPORTING
        !EV_FORMULA_TEXT TYPE ZPM_PRD_FTEXT .
    CLASS-METHODS CHANGE_DATA_AFTER_DATE_CHANGE
      IMPORTING
        !IS_ROUTE_HEADER TYPE ZI_PM_PRIDE_ROUTE_M
      EXPORTING
        !ET_MP           TYPE TT_MP
        !ET_DET          TYPE TT_DET.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_PM_PRIDE IMPLEMENTATION.


  METHOD CREATE_WITH_REF.
    DATA: LS_PRIDE_ROUTES TYPE ZPM_PRIDE_ROUTES. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_ROUTES_T TYPE ZPM_PRIDE_HIER_T. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_ROUTES LIKE TABLE OF LS_PRIDE_ROUTES. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_ROUTES_T LIKE TABLE OF LS_PRIDE_ROUTES_T. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_DATA TYPE ZPM_PRIDE_HIER_T. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_DATA LIKE TABLE OF LS_PRIDE_DATA. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_MP_DATA TYPE ZPM_PRIDE_HIER_M. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_MP_DATA LIKE TABLE OF LS_PRIDE_MP_DATA. "Work Area for LS_IMRG table"
    DATA: END_DATE TYPE DATUM,
          END_TIME TYPE UZEIT.
    DATA LV_NUMBER TYPE NR_NUMBER.
    DATA LV_EQUNR TYPE EQUNR.
    DATA LV_MOD_RES TYPE I.

    SELECT SINGLE * FROM ZPM_PRIDE_ROUTES INTO @DATA(LS_ROUTE)
      WHERE  ROUTE_ID = @ROUTE_ID.

    SELECT *  FROM ZPM_PRIDE_ROUTES UP TO 1 ROWS
    INTO @DATA(LS_ROUTE_LAST)
      WHERE  ROUTE_REF_ID = @LS_ROUTE-ROUTE_REF_ID
      ORDER BY E_DATE DESCENDING.

      SELECT MAX( E_TIME )  FROM ZPM_PRIDE_ROUTES
      INTO @DATA(LS_ROUTE_TIME)
        WHERE
        ROUTE_REF_ID = @LS_ROUTE-ROUTE_REF_ID
        AND E_DATE = @LS_ROUTE_LAST-E_DATE .

    ENDSELECT.
    SELECT SINGLE * FROM ZPM_PRIDE_ROUT_T INTO @DATA(LS_ROUTE_MAIN)
      WHERE  ROUTE_ID = @LS_ROUTE-ROUTE_REF_ID AND ACTIVE = 'S'.

    IF SY-SUBRC = 0.
      IF START_DATE IS NOT INITIAL.
        ZCL_PM_PRIDE=>CALCULATE_SCHEDULE_MIN(
          EXPORTING
            SCHEDULE   = LS_ROUTE_MAIN-SECHEDULE
          IMPORTING
            EV_MINUTES = DATA(LV_MINUTES)
        ).


*          CL_BS_PERIOD_TOOLSET_BASICS=>ADD_MINUTES_TO_DATE(
*            EXPORTING
*              IV_DATE    = START_DATE
*              IV_TIME    = START_TIME
*              IV_MINUTES = LV_MINUTES
*            IMPORTING
*              EV_DATE    = END_DATE
*              EV_TIME    = END_TIME ).
        TRY.
            CL_BS_PERIOD_TOOLSET_BASICS=>ADD_MINUTES_TO_DATE(
              EXPORTING
                IV_DATE    = LS_ROUTE_LAST-E_DATE
                IV_TIME    = LS_ROUTE_TIME
                IV_MINUTES = LV_MINUTES
              IMPORTING
                EV_DATE    = END_DATE
                EV_TIME    = END_TIME ).
          CATCH CX_BS_PERIOD_TOOLSET_BASICS. " Period Toolset - Exceptions for Basic Functions
            MESSAGE 'Error in Conversion - Muntes' TYPE 'S' DISPLAY LIKE 'E'.
            EXIT.
        ENDTRY.

      ENDIF.
      MOVE-CORRESPONDING LS_ROUTE_MAIN TO LS_PRIDE_DATA.

      SELECT * FROM ZPM_PRIDE_RDET_T
        INTO TABLE @DATA(LT_ROUTE_DETAILS)
        WHERE ROUTE_ID = @LS_PRIDE_DATA-ROUTE_ID
        AND ACTIVE = 'X'.

      IF LT_ROUTE_DETAILS[] IS NOT INITIAL.

        SELECT MP~* FROM ZPM_PRIDE_ROMP_T AS MP
          JOIN ZPM_PRIDE_RDET_T AS DET ON MP~EQUIPMENT = DET~EQUIPMENT AND MP~ROUTE_ID = DET~ROUTE_ID AND DET~ACTIVE = 'X'
          INTO TABLE @DATA(LT_ROUTE_MP)
          FOR ALL ENTRIES IN @LT_ROUTE_DETAILS
          WHERE MP~ROUTE_ID = @LT_ROUTE_DETAILS-ROUTE_ID
          AND MP~ACTIVE IN ( 'X' , 'R' ).

        SELECT EQUNR,MPOBJ,POINT,MRNGU,MRMIN,MRMINI,MRMAX,MRMAXI,DECIM FROM IMPTT
          JOIN EQUI ON EQUI~OBJNR = IMPTT~MPOBJ
          INTO TABLE @DATA(LT_MPOINT)
          FOR ALL ENTRIES IN @LT_ROUTE_MP
        WHERE IMPTT~POINT = @LT_ROUTE_MP-MEASURE_POINT.
      ENDIF.
    ELSE.
      MESSAGE 'Please select correct RouteID' TYPE 'S' DISPLAY LIKE 'E'.
      EXIT.
    ENDIF.

    LV_NUMBER =  ZCL_PM_PRIDE=>GET_NEW_NUMBER( ).
*    LOOP AT LT_PRIDE_DATA ASSIGNING FIELD-SYMBOL(<FS_PRIDE_DATA>) .
*
*      CLEAR LS_PRIDE_ROUTES.
*      MOVE-CORRESPONDING <FS_PRIDE_DATA> TO LS_PRIDE_ROUTES.
    LS_PRIDE_ROUTES-ROUTE_ID = LV_NUMBER+12(8).
    NEW_ROUTE_ID = LS_PRIDE_ROUTES-ROUTE_ID.
    LS_PRIDE_ROUTES-ROUTE_REF_ID = LS_ROUTE-ROUTE_REF_ID.
    LS_PRIDE_ROUTES-S_DATE = END_DATE.
    LS_PRIDE_ROUTES-E_DATE = END_DATE.
    LS_PRIDE_ROUTES-S_TIME = END_TIME.
    LS_PRIDE_ROUTES-E_TIME = END_TIME.
    LS_PRIDE_ROUTES-LOCATION = LS_ROUTE_MAIN-LOCATION .
    LS_PRIDE_ROUTES-ROUTE_NAME = LS_ROUTE_MAIN-ROUTE_NAME.
    LS_PRIDE_ROUTES-PLANT = LS_ROUTE_MAIN-PLANT.
    LS_PRIDE_ROUTES-ACTIVE = 'X'..
    LS_PRIDE_ROUTES-E_TIME_EVEN = END_TIME(2) .
*        LS_PRIDE_ROUTES-LOCATION = P_LOC.
    LS_PRIDE_ROUTES-SECHEDULE = LS_ROUTE-SECHEDULE.
    MODIFY ZPM_PRIDE_ROUTES FROM LS_PRIDE_ROUTES.

    CLEAR LS_PRIDE_ROUTES_T.
    REFRESH LT_PRIDE_ROUTES_T[].
    REFRESH LT_PRIDE_MP_DATA[].
*      MOVE-CORRESPONDING LT_ROUTE_DETAILS[] TO LT_PRIDE_ROUTES_T[] .
    LOOP AT LT_ROUTE_DETAILS ASSIGNING FIELD-SYMBOL(<FS_RT_DET>).
      MOVE-CORRESPONDING <FS_RT_DET> TO LS_PRIDE_ROUTES_T.
      LS_PRIDE_ROUTES_T-ROUTE_ID = LS_PRIDE_ROUTES-ROUTE_ID.
      LS_PRIDE_ROUTES_T-ACTIVE = 'X'.
      DATA(LV_HR) = END_TIME(2).
      IF <FS_RT_DET>-FREQUENCY IS INITIAL OR <FS_RT_DET>-FREQUENCY = '0' .
        <FS_RT_DET>-FREQUENCY = '2'.
      ENDIF.
      LV_MOD_RES = LV_HR MOD <FS_RT_DET>-FREQUENCY.
      IF LV_MOD_RES = 0 OR LV_HR = '00'.
        APPEND LS_PRIDE_ROUTES_T TO LT_PRIDE_ROUTES_T.
      ELSE.
        CONTINUE.
      ENDIF.
*      ENDIF.


      LOOP AT LT_ROUTE_MP ASSIGNING FIELD-SYMBOL(<FS_RT_DET_MP>) WHERE EQUIPMENT = <FS_RT_DET>-EQUIPMENT.
        MOVE-CORRESPONDING <FS_RT_DET_MP> TO LS_PRIDE_MP_DATA.
        LS_PRIDE_MP_DATA-ROUTE_ID = LS_PRIDE_ROUTES-ROUTE_ID.
        LS_PRIDE_MP_DATA-FUNC_LOC = <FS_RT_DET_MP>-FUNC_LOC.
        LS_PRIDE_MP_DATA-VALUE = ''.
        LS_PRIDE_MP_DATA-VALUE_CHAR = ''.

*      LS_PRIDE_MP_DATA-ACTIVE = LS_PRIDE_MP_DATA-.
        READ TABLE LT_MPOINT ASSIGNING FIELD-SYMBOL(<FS_MPOINT>) WITH KEY POINT = <FS_RT_DET_MP>-MEASURE_POINT.
        IF SY-SUBRC = 0.
          ZCL_PM_PRIDE=>CONVERT_READING(
            EXPORTING
              IV_MIN    = <FS_MPOINT>-MRMIN
              IV_MRNGU  = <FS_MPOINT>-MRNGU
              IV_DECIM  = <FS_MPOINT>-DECIM
              IV_VALUEI = <FS_MPOINT>-MRMINI
            IMPORTING
              EV_VALUE  = LS_PRIDE_MP_DATA-LOW
          ).

          ZCL_PM_PRIDE=>CONVERT_READING(
            EXPORTING
              IV_MIN    = <FS_MPOINT>-MRMAX
              IV_MRNGU  = <FS_MPOINT>-MRNGU
              IV_DECIM  = <FS_MPOINT>-DECIM
              IV_VALUEI = <FS_MPOINT>-MRMAXI
            IMPORTING
              EV_VALUE  = LS_PRIDE_MP_DATA-HIGH
          ).

        ENDIF.
        APPEND LS_PRIDE_MP_DATA TO LT_PRIDE_MP_DATA.
      ENDLOOP.
    ENDLOOP.
*    ENDLOOP.
    LOOP AT LT_PRIDE_ROUTES_T ASSIGNING FIELD-SYMBOL(<FS_DET>) WHERE FORMULA_TYP IS NOT INITIAL.
      CLEAR LV_EQUNR.
      LV_EQUNR = <FS_DET>-EQUIPMENT.
      IF LV_EQUNR IS NOT INITIAL.
        ZCL_PM_PRIDE=>GET_FORMULA_TEXT(
          EXPORTING
            IV_DATE         = LS_PRIDE_ROUTES-E_DATE
            IV_TIME         = LS_PRIDE_ROUTES-E_TIME
            IV_EQUIPMENT    = LV_EQUNR
          IMPORTING
            EV_FORMULA_TEXT = <FS_DET>-FOR_TEXT
        ).
      ENDIF.
*      SELECT  * FROM ZPM_PRD_CONSTANT
*      INTO TABLE @DATA(LT_CONSTANT_CD) " WHERE FOR_TYPE = @LC_COF_DIFF
*      WHERE EQUNR = @<FS_DET>-EQUIPMENT
*      AND BEGDA LE @LS_PRIDE_ROUTES-E_DATE
*      AND ENDDA GE @LS_PRIDE_ROUTES-E_DATE.
*
*      DATA(LT_CONSTANT_DIST) = LT_CONSTANT_CD[].
*      SORT LT_CONSTANT_DIST BY FOR_TYPE.
*      DELETE ADJACENT DUPLICATES FROM LT_CONSTANT_DIST COMPARING FOR_TYPE.
*
*      LOOP AT LT_CONSTANT_DIST INTO DATA(LS_CONSTANT).
*        LOOP AT LT_CONSTANT_CD INTO DATA(LS_CONSTANT_CD) WHERE FOR_TYPE = LS_CONSTANT-FOR_TYPE.
*          DATA(LV_ROUTE_ENDDATE) = LS_PRIDE_ROUTES-E_DATE && LS_PRIDE_ROUTES-E_TIME.
*          DATA(LV_CONST_STARTDATE) = LS_CONSTANT_CD-BEGDA && LS_CONSTANT_CD-BEDGT.
*          DATA(LV_CONST_ENDDATE) = LS_CONSTANT_CD-ENDDA && LS_CONSTANT_CD-ENDT.
*
*          IF LV_CONST_STARTDATE LE LV_ROUTE_ENDDATE AND LV_CONST_ENDDATE GE LV_ROUTE_ENDDATE.
*            DATA(LV_CONSTANT) = LS_CONSTANT_CD-FOR_TYPE && ` : ` && LS_CONSTANT_CD-VALUE.
*            IF <FS_DET>-FOR_TEXT IS INITIAL.
*              <FS_DET>-FOR_TEXT = LV_CONSTANT.
**                    CONCATENATE <FS_DET>-FOR_TEXT LV_CONSTANT INTO <FS_DET>-FOR_TEXT SEPARATED BY CL_ABAP_CHAR_UTILITIES=>NEWLINE.
*            ELSE.
*              CONCATENATE <FS_DET>-FOR_TEXT LV_CONSTANT INTO <FS_DET>-FOR_TEXT SEPARATED BY CL_ABAP_CHAR_UTILITIES=>NEWLINE.
*            ENDIF.
*            EXIT.
*          ENDIF.
*        ENDLOOP.
*      ENDLOOP.
    ENDLOOP..


    IF LT_PRIDE_ROUTES_T[] IS NOT INITIAL.
      MODIFY ZPM_PRIDE_HIER_T FROM TABLE LT_PRIDE_ROUTES_T.
    ENDIF.
    IF LT_PRIDE_MP_DATA[] IS NOT INITIAL.
      MODIFY ZPM_PRIDE_HIER_M FROM TABLE LT_PRIDE_MP_DATA.
    ENDIF.
  ENDMETHOD.


  METHOD GET_NEW_NUMBER.
    TRY.
        CL_NUMBERRANGE_RUNTIME=>NUMBER_GET(
          EXPORTING
*           IGNORE_BUFFER     = IGNORE_BUFFER
            NR_RANGE_NR       = '01'
            OBJECT            = 'ZPM_ROUTE'
*           QUANTITY          = 1
*           SUBOBJECT         = SUBOBJECT
*           TOYEAR            = TOYEAR
          IMPORTING
            NUMBER            = DATA(LV_NUM)
            RETURNCODE        = DATA(LV_CODE)
            RETURNED_QUANTITY = DATA(LV_QTY)
        ).
        NUMBER = LV_NUM.
      CATCH CX_NR_OBJECT_NOT_FOUND.
      CATCH CX_NUMBER_RANGES INTO DATA(LO_NUMRANGE).
    ENDTRY.
  ENDMETHOD.


  METHOD CREATE_WITH_TEMPLATE.
    DATA: LS_PRIDE_ROUTES TYPE ZPM_PRIDE_ROUTES. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_ROUTES_T TYPE ZPM_PRIDE_HIER_T. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_ROUTES LIKE TABLE OF LS_PRIDE_ROUTES. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_ROUTES_T LIKE TABLE OF LS_PRIDE_ROUTES_T. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_DATA TYPE ZPM_PRIDE_HIER_T. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_DATA LIKE TABLE OF LS_PRIDE_DATA. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_MP_DATA TYPE ZPM_PRIDE_HIER_M. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_MP_DATA LIKE TABLE OF LS_PRIDE_MP_DATA. "Work Area for LS_IMRG table"
    DATA: END_DATE TYPE DATUM,
          END_TIME TYPE UZEIT.
    DATA LV_NUMBER TYPE NR_NUMBER.
    SELECT SINGLE * FROM ZPM_PRIDE_ROUTES INTO @DATA(DUP_ROUTE) WHERE ROUTE_REF_ID = @ROUTE_ID AND ACTIVE = 'X'.
    IF SY-SUBRC = 0.
    ELSE.
      SELECT SINGLE * FROM ZPM_PRIDE_ROUT_T INTO @DATA(LS_ROUTE)
        WHERE  ROUTE_ID = @ROUTE_ID.

      SELECT SINGLE * FROM ZPM_PRIDE_ROUT_T INTO @DATA(LS_ROUTE_MAIN)
        WHERE  ROUTE_ID = @ROUTE_ID." and ACTIVE = 'S'.

      IF SY-SUBRC = 0.
        IF START_DATE IS NOT INITIAL.
          ZCL_PM_PRIDE=>CALCULATE_SCHEDULE_MIN(
            EXPORTING
              SCHEDULE   = SCHEDULE
            IMPORTING
              EV_MINUTES = DATA(LV_MINUTES)
          ).
          TRY.
              CL_BS_PERIOD_TOOLSET_BASICS=>ADD_MINUTES_TO_DATE(
                EXPORTING
                  IV_DATE    = START_DATE
                  IV_TIME    = START_TIME
                  IV_MINUTES = LV_MINUTES
                IMPORTING
                  EV_DATE    = END_DATE
                  EV_TIME    = END_TIME ).
            CATCH CX_BS_PERIOD_TOOLSET_BASICS.
              MESSAGE 'Conversion Error in Minute' TYPE 'S' DISPLAY LIKE 'E'.
              EXIT.
          ENDTRY.
        ENDIF.
        MOVE-CORRESPONDING LS_ROUTE_MAIN TO LS_PRIDE_DATA.

        SELECT * FROM ZPM_PRIDE_RDET_T
          INTO TABLE @DATA(LT_ROUTE_DETAILS)
          WHERE ROUTE_ID = @LS_PRIDE_DATA-ROUTE_ID
          AND ACTIVE = 'X'.

        IF LT_ROUTE_DETAILS[] IS NOT INITIAL.

          SELECT MP~* FROM ZPM_PRIDE_ROMP_T AS MP
            JOIN ZPM_PRIDE_RDET_T AS DET ON MP~EQUIPMENT = DET~EQUIPMENT AND MP~ROUTE_ID = DET~ROUTE_ID AND DET~ACTIVE = 'X'
            INTO TABLE @DATA(LT_ROUTE_MP)
            FOR ALL ENTRIES IN @LT_ROUTE_DETAILS
            WHERE MP~ROUTE_ID = @LT_ROUTE_DETAILS-ROUTE_ID
            AND MP~ACTIVE IN ( 'X' , 'R' ).

          SELECT EQUNR,MPOBJ,POINT,MRNGU,MRMIN,MRMINI,MRMAX,MRMAXI,DECIM FROM IMPTT
            JOIN EQUI ON EQUI~OBJNR = IMPTT~MPOBJ
            INTO TABLE @DATA(LT_MPOINT)
            FOR ALL ENTRIES IN @LT_ROUTE_MP
          WHERE IMPTT~POINT = @LT_ROUTE_MP-MEASURE_POINT.
*          AND INACT NE 'X'.

        ENDIF.
      ELSE.
        MESSAGE 'Please select correct RouteID' TYPE 'S' DISPLAY LIKE 'E'.
        EXIT.
      ENDIF.

      LV_NUMBER =  ZCL_PM_PRIDE=>GET_NEW_NUMBER( ).
*    LOOP AT LT_PRIDE_DATA ASSIGNING FIELD-SYMBOL(<FS_PRIDE_DATA>) .
*
*      CLEAR LS_PRIDE_ROUTES.
*      MOVE-CORRESPONDING <FS_PRIDE_DATA> TO LS_PRIDE_ROUTES.
      LS_PRIDE_ROUTES-ROUTE_ID = LV_NUMBER+12(8).
      NEW_ROUTE_ID = LS_PRIDE_ROUTES-ROUTE_ID.
      LS_PRIDE_ROUTES-ROUTE_REF_ID = LS_ROUTE-ROUTE_ID.
      LS_PRIDE_ROUTES-S_DATE = END_DATE.
      LS_PRIDE_ROUTES-E_DATE = END_DATE.
      LS_PRIDE_ROUTES-S_TIME = END_TIME.
      LS_PRIDE_ROUTES-E_TIME = END_TIME.
      LS_PRIDE_ROUTES-LOCATION = LS_ROUTE_MAIN-LOCATION .
      LS_PRIDE_ROUTES-ROUTE_NAME = LS_ROUTE_MAIN-ROUTE_NAME.
      LS_PRIDE_ROUTES-ACTIVE = 'X'.
*        LS_PRIDE_ROUTES-LOCATION = P_LOC.
      LS_PRIDE_ROUTES-SECHEDULE = LS_ROUTE-SECHEDULE.
      MODIFY ZPM_PRIDE_ROUTES FROM LS_PRIDE_ROUTES.

      CLEAR LS_PRIDE_ROUTES_T.
      REFRESH LT_PRIDE_ROUTES_T[].
*      MOVE-CORRESPONDING LT_ROUTE_DETAILS[] TO LT_PRIDE_ROUTES_T[] .
      LOOP AT LT_ROUTE_DETAILS ASSIGNING FIELD-SYMBOL(<FS_RT_DET>).
        MOVE-CORRESPONDING <FS_RT_DET> TO LS_PRIDE_ROUTES_T.
        LS_PRIDE_ROUTES_T-ROUTE_ID = LS_PRIDE_ROUTES-ROUTE_ID.
        LS_PRIDE_ROUTES_T-ACTIVE = 'X'.
        APPEND LS_PRIDE_ROUTES_T TO LT_PRIDE_ROUTES_T.
      ENDLOOP.

      REFRESH LT_PRIDE_MP_DATA[].
      LOOP AT LT_ROUTE_MP ASSIGNING FIELD-SYMBOL(<FS_RT_DET_MP>).
        MOVE-CORRESPONDING <FS_RT_DET_MP> TO LS_PRIDE_MP_DATA.
        READ TABLE LT_MPOINT ASSIGNING FIELD-SYMBOL(<FS_MPOINT>) WITH KEY POINT = <FS_RT_DET_MP>-MEASURE_POINT.
        IF SY-SUBRC = 0.
          ZCL_PM_PRIDE=>CONVERT_READING(
            EXPORTING
              IV_MIN    = <FS_MPOINT>-MRMIN
              IV_MRNGU  = <FS_MPOINT>-MRNGU
              IV_DECIM  = <FS_MPOINT>-DECIM
              IV_VALUEI = <FS_MPOINT>-MRMINI
            IMPORTING
              EV_VALUE  = LS_PRIDE_MP_DATA-LOW
          ).

          ZCL_PM_PRIDE=>CONVERT_READING(
            EXPORTING
              IV_MIN    = <FS_MPOINT>-MRMAX
              IV_MRNGU  = <FS_MPOINT>-MRNGU
              IV_DECIM  = <FS_MPOINT>-DECIM
              IV_VALUEI = <FS_MPOINT>-MRMAXI
            IMPORTING
              EV_VALUE  = LS_PRIDE_MP_DATA-HIGH
          ).

        ENDIF.
        LS_PRIDE_MP_DATA-ROUTE_ID = LS_PRIDE_ROUTES-ROUTE_ID.
        LS_PRIDE_MP_DATA-FUNC_LOC = <FS_RT_DET_MP>-FUNC_LOC.
*      LS_PRIDE_MP_DATA-ACTIVE = 'X'.
        APPEND LS_PRIDE_MP_DATA TO LT_PRIDE_MP_DATA.
      ENDLOOP.
*    ENDLOOP.

      IF LT_PRIDE_ROUTES_T[] IS NOT INITIAL.
        MODIFY ZPM_PRIDE_HIER_T FROM TABLE LT_PRIDE_ROUTES_T.
      ENDIF.
      IF LT_PRIDE_MP_DATA[] IS NOT INITIAL.
        MODIFY ZPM_PRIDE_HIER_M FROM TABLE LT_PRIDE_MP_DATA.
      ENDIF.
    ENDIF.
  ENDMETHOD.


  METHOD CONVERT_READING.

    DATA LV_CHAR TYPE EAML_START_POINT.
    CLEAR LV_CHAR.
    CALL FUNCTION 'FLTP_CHAR_CONVERSION_FROM_SI'
      EXPORTING
        CHAR_UNIT        = IV_MRNGU
        UNIT_IS_OPTIONAL = ' '
        DECIMALS         = IV_DECIM
        EXPONENT         = 0
        FLTP_VALUE_SI    = IV_MIN
        INDICATOR_VALUE  = IV_VALUEI
        MASC_SYMBOL      = ' '
      IMPORTING
        CHAR_VALUE       = LV_CHAR
      EXCEPTIONS
        NO_UNIT_GIVEN    = 1
        UNIT_NOT_FOUND   = 2
        OTHERS           = 3.

    CONDENSE LV_CHAR.
    MOVE LV_CHAR TO EV_VALUE.
  ENDMETHOD.


  METHOD CALCULATE_SCHEDULE_MIN.
    CASE SCHEDULE.
      WHEN 1.
        EV_MINUTES = 240.

      WHEN 2.
        EV_MINUTES = 120.

      WHEN 3.
        EV_MINUTES = 480.

      WHEN OTHERS.
        EV_MINUTES = 0.
    ENDCASE.

  ENDMETHOD.


  METHOD GET_MP_FORMULA.
    DATA COUNT TYPE I.
    DATA REM TYPE I.
    DATA SIGN TYPE CHAR1.
    DATA VALUE TYPE I.
    DATA MP TYPE IMRC_POINT.
    DATA LV_TYPE TYPE DD01V-DATATYPE.
    DATA LV_STR_OUT TYPE STRING.
    SELECT SINGLE ROUTE_REF_ID  FROM ZPM_PRIDE_ROUTES INTO @DATA(LV_MAIN_ROUTE) WHERE ROUTE_ID = @IV_ROUTEID.

    IF LV_MAIN_ROUTE IS NOT INITIAL.
      SELECT * FROM ZTPM004
        INTO TABLE @DATA(LT_FORMULA)
        WHERE ROUTEID = @LV_MAIN_ROUTE AND MEASURE_POINT = @IV_MP.

      CLEAR COUNT.
      SORT LT_FORMULA BY SNO ASCENDING.
      CLEAR VALUE .


      LOOP AT LT_FORMULA FROM 3 ASSIGNING FIELD-SYMBOL(<FS_FORMUAL>).
        COUNT  = COUNT + 1.

        REM = COUNT MOD 2 .
        IF REM NE 0.
          DATA(LEN) =  STRLEN( <FS_FORMUAL>-FOR_VALUE ).
          IF LEN = 12.
*      SELECT
            CLEAR MP.
            MP = <FS_FORMUAL>-FOR_VALUE.
            SELECT SINGLE VALUE_CHAR FROM  ZPM_PRIDE_HIER_M
              INTO @DATA(LV_VALUE)
              WHERE ROUTE_ID = @IV_ROUTEID AND MEASURE_POINT = @MP.

            CALL FUNCTION 'NUMERIC_CHECK'
              EXPORTING
                STRING_IN  = LV_VALUE
              IMPORTING
                HTYPE      = LV_TYPE
                STRING_OUT = LV_STR_OUT.

            IF LV_TYPE = 'NUMC'.
              CASE SIGN.

                WHEN '-'.
                  VALUE = VALUE - LV_VALUE.
                WHEN '+'.
                  VALUE = VALUE + LV_VALUE.
                WHEN '/'.
                  VALUE = VALUE / LV_VALUE.
                WHEN '*'.
                  VALUE = VALUE * LV_VALUE.
                WHEN OTHERS.
                  VALUE = VALUE + LV_VALUE.
              ENDCASE.
            ENDIF.
            CLEAR LV_VALUE.
          ELSE.


          ENDIF.

        ELSE.
          CLEAR SIGN.
          SIGN = <FS_FORMUAL>-FOR_VALUE.

        ENDIF.

      ENDLOOP.

    ENDIF.
    EV_VALUE = VALUE.
    CLEAR: VALUE,LV_VALUE.
  ENDMETHOD.


  METHOD GET_FORMULA_TEXT.

    SELECT  * FROM ZPM_PRD_CONSTANT
          INTO TABLE @DATA(LT_CONSTANT_CD) " WHERE FOR_TYPE = @LC_COF_DIFF
          WHERE EQUNR = @IV_EQUIPMENT
          AND BEGDA LE @IV_DATE
          AND ENDDA GE @IV_DATE.

    DATA(LT_CONSTANT_DIST) = LT_CONSTANT_CD[].
    SORT LT_CONSTANT_DIST BY FOR_TYPE.
    DELETE ADJACENT DUPLICATES FROM LT_CONSTANT_DIST COMPARING FOR_TYPE.

    LOOP AT LT_CONSTANT_DIST INTO DATA(LS_CONSTANT).
      LOOP AT LT_CONSTANT_CD INTO DATA(LS_CONSTANT_CD) WHERE FOR_TYPE = LS_CONSTANT-FOR_TYPE.
        DATA(LV_ROUTE_ENDDATE) = IV_DATE && IV_TIME.
        DATA(LV_CONST_STARTDATE) = LS_CONSTANT_CD-BEGDA && LS_CONSTANT_CD-BEDGT.
        DATA(LV_CONST_ENDDATE) = LS_CONSTANT_CD-ENDDA && LS_CONSTANT_CD-ENDT.

        IF LV_CONST_STARTDATE LE LV_ROUTE_ENDDATE AND LV_CONST_ENDDATE GE LV_ROUTE_ENDDATE.
          DATA(LV_CONSTANT) = LS_CONSTANT_CD-FOR_TYPE && ` : ` && LS_CONSTANT_CD-VALUE.
          IF EV_FORMULA_TEXT IS INITIAL.
            EV_FORMULA_TEXT = LV_CONSTANT.
*                    CONCATENATE <FS_DET>-FOR_TEXT LV_CONSTANT INTO <FS_DET>-FOR_TEXT SEPARATED BY CL_ABAP_CHAR_UTILITIES=>NEWLINE.
          ELSE.
            CONCATENATE EV_FORMULA_TEXT LV_CONSTANT INTO EV_FORMULA_TEXT SEPARATED BY CL_ABAP_CHAR_UTILITIES=>NEWLINE.
          ENDIF.
          EXIT.
        ENDIF.
      ENDLOOP.
    ENDLOOP.
  ENDMETHOD.


  METHOD CHANGE_DATA_AFTER_DATE_CHANGE.
*    DATA: LS_PRIDE_ROUTES TYPE ZPM_PRIDE_ROUTES. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_ROUTES_T TYPE ZI_PM_PRIDE_ROUTE_DET_M. "Work Area for LS_IMRG table"
*    DATA: LT_PRIDE_ROUTES LIKE TABLE OF LS_PRIDE_ROUTES. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_ROUTES_T LIKE TABLE OF LS_PRIDE_ROUTES_T. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_DATA TYPE ZPM_PRIDE_HIER_T. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_DATA LIKE TABLE OF LS_PRIDE_DATA. "Work Area for LS_IMRG table"
    DATA: LS_PRIDE_MP_DATA TYPE ZI_PM_PRIDE_ROUTE_MP_M. "Work Area for LS_IMRG table"
    DATA: LT_PRIDE_MP_DATA LIKE TABLE OF LS_PRIDE_MP_DATA. "Work Area for LS_IMRG table"
    DATA: END_DATE TYPE DATUM,
          END_TIME TYPE UZEIT.
    DATA LV_NUMBER TYPE NR_NUMBER.
    DATA LV_EQUNR TYPE EQUNR.
    DATA LV_MOD_RES TYPE I.

    IF IS_ROUTE_HEADER-ROUTEID IS NOT INITIAL.

*      DELETE FROM ZPM_PRIDE_HIER_T WHERE ROUTE_ID = IS_ROUTE_HEADER-ROUTEID.
*      DELETE FROM ZPM_PRIDE_HIER_M WHERE ROUTE_ID = IS_ROUTE_HEADER-ROUTEID.
*      COMMIT WORK.

      SELECT SINGLE * FROM ZPM_PRIDE_ROUT_T INTO @DATA(LS_ROUTE_MAIN)
        WHERE  ROUTE_ID = @IS_ROUTE_HEADER-ROUTEREFID AND ACTIVE = 'S'.
      IF SY-SUBRC = 0.

        SELECT * FROM ZI_PM_PRIDE_ROUTE_DET_TEMP_M
          INTO TABLE @DATA(LT_ROUTE_DETAILS)
          WHERE ROUTEID = @LS_ROUTE_MAIN-ROUTE_ID
          AND IsActive = 'X'.

        IF LT_ROUTE_DETAILS[] IS NOT INITIAL.
          SELECT MP~* FROM ZI_PM_PRIDE_ROUTE_MP_TEMP_M AS MP
            JOIN ZI_PM_PRIDE_ROUTE_DET_TEMP_M AS DET ON MP~EQUIPMENT = DET~EQUIPMENT
                                                        AND MP~ROUTEID = DET~ROUTEID
                                                        AND DET~IsActive = 'X'
            INTO TABLE @DATA(LT_ROUTE_MP)
            FOR ALL ENTRIES IN @LT_ROUTE_DETAILS
            WHERE MP~ROUTEID = @LT_ROUTE_DETAILS-ROUTEID
            AND MP~IsActive IN ( 'X' , 'R' ).

          SELECT EQUNR,MPOBJ,POINT,MRNGU,MRMIN,MRMINI,MRMAX,MRMAXI,DECIM FROM IMPTT
            JOIN EQUI ON EQUI~OBJNR = IMPTT~MPOBJ
            INTO TABLE @DATA(LT_MPOINT)
            FOR ALL ENTRIES IN @LT_ROUTE_MP
          WHERE IMPTT~POINT = @LT_ROUTE_MP-MEASUREPOINT.

          LOOP AT LT_ROUTE_DETAILS ASSIGNING FIELD-SYMBOL(<FS_RT_DET>).
            MOVE-CORRESPONDING <FS_RT_DET> TO LS_PRIDE_ROUTES_T.
            LS_PRIDE_ROUTES_T-RouteId = IS_ROUTE_HEADER-ROUTEID.
            LS_PRIDE_ROUTES_T-isActive = 'X'.
            DATA(LV_HR) = IS_ROUTE_HEADER-ETime(2).
            IF <FS_RT_DET>-FREQUENCY IS INITIAL OR <FS_RT_DET>-FREQUENCY = '0' .
              <FS_RT_DET>-FREQUENCY = '2'.
            ENDIF.
            LV_MOD_RES = LV_HR MOD <FS_RT_DET>-FREQUENCY.
            IF LV_MOD_RES = 0 OR LV_HR = '00'.
              APPEND LS_PRIDE_ROUTES_T TO LT_PRIDE_ROUTES_T.
            ELSE.
              CONTINUE.
            ENDIF.

            LOOP AT LT_ROUTE_MP ASSIGNING FIELD-SYMBOL(<FS_RT_DET_MP>) WHERE EQUIPMENT = <FS_RT_DET>-EQUIPMENT.
              MOVE-CORRESPONDING <FS_RT_DET_MP>  TO LS_PRIDE_MP_DATA.
              LS_PRIDE_MP_DATA-RouteId = IS_ROUTE_HEADER-ROUTEID.
              LS_PRIDE_MP_DATA-FuncLoc = <FS_RT_DET_MP>-FUNCLOC.
              LS_PRIDE_MP_DATA-VALUE = ''.
              LS_PRIDE_MP_DATA-VALUE_CHAR = ''.

*      LS_PRIDE_MP_DATA-ACTIVE = LS_PRIDE_MP_DATA-.
              READ TABLE LT_MPOINT ASSIGNING FIELD-SYMBOL(<FS_MPOINT>) WITH KEY POINT = <FS_RT_DET_MP>-MEASUREPOINT.
              IF SY-SUBRC = 0.
                ZCL_PM_PRIDE=>CONVERT_READING(
                  EXPORTING
                    IV_MIN    = <FS_MPOINT>-MRMIN
                    IV_MRNGU  = <FS_MPOINT>-MRNGU
                    IV_DECIM  = <FS_MPOINT>-DECIM
                    IV_VALUEI = <FS_MPOINT>-MRMINI
                  IMPORTING
                    EV_VALUE  = LS_PRIDE_MP_DATA-LowLimit
                ).

                ZCL_PM_PRIDE=>CONVERT_READING(
                  EXPORTING
                    IV_MIN    = <FS_MPOINT>-MRMAX
                    IV_MRNGU  = <FS_MPOINT>-MRNGU
                    IV_DECIM  = <FS_MPOINT>-DECIM
                    IV_VALUEI = <FS_MPOINT>-MRMAXI
                  IMPORTING
                    EV_VALUE  = LS_PRIDE_MP_DATA-HighLimit
                ).

              ENDIF.
              APPEND LS_PRIDE_MP_DATA TO LT_PRIDE_MP_DATA.
            ENDLOOP.
          ENDLOOP.
*    ENDLOOP.
          LOOP AT LT_PRIDE_ROUTES_T ASSIGNING FIELD-SYMBOL(<FS_DET>) WHERE FORMULA_TYP IS NOT INITIAL.
            CLEAR LV_EQUNR.
            LV_EQUNR = <FS_DET>-EQUIPMENT.
            IF LV_EQUNR IS NOT INITIAL.
              ZCL_PM_PRIDE=>GET_FORMULA_TEXT(
                EXPORTING
                  IV_DATE         = IS_ROUTE_HEADER-EDATE
                  IV_TIME         = IS_ROUTE_HEADER-ETIME
                  IV_EQUIPMENT    = LV_EQUNR
                IMPORTING
                  EV_FORMULA_TEXT = <FS_DET>-FormulaText
              ).
            ENDIF.
          ENDLOOP.
          IF LT_PRIDE_ROUTES_T[] IS NOT INITIAL.
            MOVE-CORRESPONDING LT_PRIDE_ROUTES_T TO ET_DET.
          ENDIF.
          IF LT_PRIDE_MP_DATA[] IS NOT INITIAL.
            MOVE-CORRESPONDING LT_PRIDE_MP_DATA TO ET_MP.
*            MODIFY ZPM_PRIDE_HIER_M FROM TABLE LT_PRIDE_MP_DATA.
          ENDIF.
*          COMMIT WORK.
        ENDIF.


      ENDIF.
    ENDIF.


  ENDMETHOD.
ENDCLASS.
