*&---------------------------------------------------------------------*
*& Include          ZPM_JOB_CARD_REPORT_T01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
DATA:GT_MAIN TYPE ZPM_JOB_CARD_REPORT_TT,
     GS_MAIN LIKE LINE OF GT_MAIN.


*Dynamic Call
DATA: LS_DATA TYPE REF TO DATA.
DATA: GV_FLAG TYPE CHAR1..
FIELD-SYMBOLS: <LT_DATA> TYPE TABLE.

*For Long Text



DATA: HEADER           TYPE THEAD,
      OLD_LINE_COUNTER TYPE THEAD-TDTXTLINES,
      LINES            TYPE STANDARD TABLE OF TLINE,
      NAME             TYPE THEAD-TDNAME.


*Global Parameter

DATA:REPORT_DATE   TYPE DATS,
     PERIOD_FROM   TYPE DATS,
     PERIOD_TO     TYPE DATS,
     BANKA         TYPE BNKA-BANKA,
     BANKN         TYPE T012K-BANKN,
     BRNCH         TYPE BNKA-BRNCH,
     WAERS         TYPE T012K-WAERS,
     TOTAL         TYPE FAGL_CURRVAL_10,
     PRIORITY_TEXT TYPE CHAR100,
     P_DATE        TYPE DATS,
*     P_DATE        TYPE DATS,
     GV_LOGO       TYPE ZHCM_XTRING,
     GV_COMP_NAME  TYPE char100,
     ORDER         TYPE CHAR100.


*For Bapi
DATA NUMBER                   TYPE BAPI_ALM_ORDER_HEADER_E-ORDERID.
DATA ES_HEADER                TYPE BAPI_ALM_ORDER_HEADER_E.
DATA ES_SRVDATA               TYPE BAPI_ALM_ORDER_SRVDAT_E.
DATA ES_REFORDER_ITEM         TYPE BAPI_REFORDER_ITEM.
DATA ES_JVA_DATA              TYPE BAPI_ALM_ORDER_JVA.
DATA ET_PARTNER               TYPE STANDARD TABLE OF BAPI_ALM_ORDER_PARTNER.
DATA ET_OPERATIONS            TYPE STANDARD TABLE OF BAPI_ALM_ORDER_OPERATION_E.
DATA ET_COMPONENTS            TYPE STANDARD TABLE OF BAPI_ALM_ORDER_COMPONENT_E.
DATA ET_RELATIONS             TYPE STANDARD TABLE OF BAPI_ALM_ORDER_RELATION_EXPORT.
DATA ET_SRULES                TYPE STANDARD TABLE OF BAPI_ALM_ORDER_SRULE_E.
DATA ET_OLIST                 TYPE STANDARD TABLE OF BAPI_ALM_ORDER_OBJECTLIST.
DATA ET_OPROL                 TYPE STANDARD TABLE OF BAPI_ALM_OLIST_RELATION.
DATA ET_TEXTS                 TYPE STANDARD TABLE OF BAPI_ALM_TEXT.
DATA ET_TEXT_LINES            TYPE STANDARD TABLE OF BAPI_ALM_TEXT_LINES.
DATA ET_PRTS                  TYPE STANDARD TABLE OF BAPI_ALM_ORDER_PRT_E.
DATA ET_COSTS_SUM             TYPE STANDARD TABLE OF BAPI_ALM_ORDER_COSTS_SUM_E.
DATA ET_COSTS_DETAILS         TYPE STANDARD TABLE OF BAPI_ALM_ORDER_COSTS_DETAIL_E.
DATA RETURN                   TYPE STANDARD TABLE OF BAPIRET2.
DATA EXTENSION_IN             TYPE STANDARD TABLE OF BAPIPAREX.
DATA EXTENSION_OUT            TYPE STANDARD TABLE OF BAPIPAREX.
DATA ET_REFORDER_SERNO_OLIST  TYPE STANDARD TABLE OF BAPI_REFORDER_SERNO_OLIST.
DATA ET_SERVICEOUTLINE        TYPE STANDARD TABLE OF BAPI_ALM_SRV_OUTLINE.
DATA ET_SERVICELINES          TYPE STANDARD TABLE OF BAPI_ALM_SRV_SERVICE_LINE.
DATA ET_SERVICELIMIT          TYPE STANDARD TABLE OF BAPI_ALM_SRV_LIMIT_DATA.
DATA ET_SERVICECONTRACTLIMITS TYPE STANDARD TABLE OF BAPI_ALM_SRV_CONTRACT_LIMITS.
DATA ET_PERMIT                TYPE STANDARD TABLE OF BAPI_ALM_ORDER_PERMIT_READ.
DATA ET_PERMIT_ISSUE          TYPE STANDARD TABLE OF BAPI_ALM_ORDER_PER_ISSUE_R.
DATA ET_ADDITIONAL_TEXTS      TYPE STANDARD TABLE OF BAPI_ALM_CC4_ADDITIONAL_TEXT.
