*&---------------------------------------------------------------------*
*& Include          ZPM_CRF_UPDATION_FORM_F01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Form GET_DATA
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM GET_DATA .

*break-point.
  DATA:ZRSNUM TYPE RESB-AUFNR.
  GET PARAMETER ID 'ZRSNUM' FIELD ZRSNUM.
  BREAK AC_ADNAN.

  SELECT * FROM ZPM_AS_BUILD_CDS
    INTO TABLE @DATA(LT_RESB)
    WHERE AUFNR = @ZRSNUM.

  IF LT_RESB IS NOT INITIAL.

*    SELECT * FROM ZPM_AS_BUILD_MSEG_CDS
*       INTO TABLE @DATA(LT_MSEG)
*      FOR ALL ENTRIES IN @LT_RESB
*      WHERE
*      RSNUM = @LT_RESB-RSNUM
*      AND MATNR = @LT_RESB-MATNR
*      AND AUFNR = @LT_RESB-AUFNR.
    SELECT * FROM ZPM_AS_BUILD_MSEG_CDS
       INTO TABLE @DATA(LT_MSEG)
      FOR ALL ENTRIES IN @LT_RESB
      WHERE
       ( RSNUM = @LT_RESB-RSNUM OR  AUFNR = @LT_RESB-AUFNR )
      AND MATNR = @LT_RESB-MATNR.
*      AND AUFNR = @LT_RESB-AUFNR..


    SELECT * FROM ZPM_AS_BUILD_PM_BUILT_CDS
      INTO TABLE @DATA(LT_BUILD)
     FOR ALL ENTRIES IN @LT_RESB
      WHERE RSNUM = @LT_RESB-RSNUM
     AND MATNR = @LT_RESB-MATNR
     AND AUFNR = @LT_RESB-AUFNR.
  ENDIF.

  SORT LT_RESB BY MATNR ASCENDING.
*BOC by Adnan Khan from Return Qty
  IF NOT LT_RESB IS INITIAL.
    SELECT * FROM ZPM_AS_BUILD_MSEG_RET_CDS
      INTO TABLE @DATA(LT_MSEG_262)
      FOR ALL ENTRIES IN @LT_RESB
      WHERE ( RSNUM = @LT_RESB-RSNUM OR  AUFNR = @LT_RESB-AUFNR ).
  ENDIF.
  SORT LT_MSEG BY MATNR ASCENDING.
*EOC by Adnan Khan from Return Qty
  LOOP AT LT_RESB INTO DATA(LS_RESB).


    MOVE-CORRESPONDING LS_RESB TO GS_MAIN.

*BOC by Adnan Khan from PM:AS build from MSGES
    GS_MAIN-CHARG = VALUE #( LT_MSEG[ RSNUM = LS_RESB-RSNUM MATNR = LS_RESB-MATNR AUFNR = LS_RESB-AUFNR ]-CHARG OPTIONAL ).
    DATA(LV_MSEG) = REDUCE DMSHB( INIT VAL TYPE FAGL_CURRVAL_10 FOR WA_ISSUE IN  LT_MSEG
                  WHERE ( MATNR = LS_RESB-MATNR  AND ( RSNUM = LS_RESB-RSNUM OR AUFNR = LS_RESB-AUFNR ) )  NEXT VAL = VAL + WA_ISSUE-ISSUED_QTY  ).
*    DATA(LV_MSEG) = VALUE #( LT_MSEG[ RSNUM = LS_RESB-RSNUM MATNR = LS_RESB-MATNR AUFNR = LS_RESB-AUFNR ]-ISSUED_QTY OPTIONAL ).
    IF LV_MSEG IS NOT INITIAL.
      GS_MAIN-ISSUED_QTY = LV_MSEG.
      CLEAR LV_MSEG.
    ENDIF.
*EOC by Adnan Khan from PM:AS build from MSGES

*BOC by Adnan Khan from PM:AS build ZPM_BUILT Custom Table
    DATA(LS_PM_BUILT) = VALUE #( LT_BUILD[ RSNUM = LS_RESB-RSNUM MATNR = LS_RESB-MATNR AUFNR = LS_RESB-AUFNR ] OPTIONAL ).
    IF LS_PM_BUILT IS NOT INITIAL.
      GS_MAIN-ASBUILT_QTY = LS_PM_BUILT-ASBUILT_QTY.
      GS_MAIN-ASBUILT_DATE = LS_PM_BUILT-ASBUILT_DATE.
      GS_MAIN-CPUDT   = LS_PM_BUILT-CPUDT.
      GS_MAIN-CPUTM   = LS_PM_BUILT-CPUTM.
      GS_MAIN-UNAME   = LS_PM_BUILT-UNAME.

    ENDIF.
*EOC by Adnan Khan from PM:AS build Custom Table

    GS_MAIN-RETURN_QTY = REDUCE DMSHB( INIT VAL TYPE FAGL_CURRVAL_10 FOR WA IN  LT_MSEG_262
                  WHERE ( MATNR = LS_RESB-MATNR )  NEXT VAL = VAL + WA-RETURN_QTY  ).


    GS_MAIN-BALANCE_QTY = GS_MAIN-ISSUED_QTY - GS_MAIN-RETURN_QTY.

    DATA MATERIAL_GENERAL_DATA TYPE BAPIMATDOA.
    DATA RETURN                TYPE BAPIRETURN.
    DATA MATERIALPLANTDATA     TYPE BAPIMATDOC.
    DATA MATERIALVALUATIONDATA TYPE BAPIMATDOBEW.
    DATA MATERIAL TYPE  MATNR18.

    MATERIAL = LS_RESB-MATNR.
    CALL FUNCTION 'BAPI_MATERIAL_GET_DETAIL'
      EXPORTING
        MATERIAL              = MATERIAL
        PLANT                 = LS_RESB-WERKS
        VALUATIONAREA         = LS_RESB-WERKS
*       VALUATIONTYPE         = VALUATIONTYPE
*       MATERIAL_EVG          = MATERIAL_EVG
*       MATERIAL_LONG         = MATERIAL_LONG
      IMPORTING
        MATERIAL_GENERAL_DATA = MATERIAL_GENERAL_DATA
        RETURN                = RETURN
        MATERIALPLANTDATA     = MATERIALPLANTDATA
        MATERIALVALUATIONDATA = MATERIALVALUATIONDATA.

    IF MATERIALVALUATIONDATA-PRICE_UNIT IS NOT INITIAL.
      GS_MAIN-UNIT_COST = MATERIALVALUATIONDATA-MOVING_PR / MATERIALVALUATIONDATA-PRICE_UNIT.
      GS_MAIN-WAERS = MATERIALVALUATIONDATA-CURRENCY .
    ELSE.
      GS_MAIN-UNIT_COST = MATERIALVALUATIONDATA-MOVING_PR.
      GS_MAIN-WAERS = MATERIALVALUATIONDATA-CURRENCY .
    ENDIF.


    GS_MAIN-ASBUILT_COST = GS_MAIN-ASBUILT_QTY *  GS_MAIN-UNIT_COST.
    GS_MAIN-OUTSTANDING_QTY = GS_MAIN-BALANCE_QTY -  GS_MAIN-ASBUILT_QTY.
    GS_MAIN-OUTSTANDING_COST = GS_MAIN-OUTSTANDING_QTY *  GS_MAIN-UNIT_COST.

    IF GS_MAIN-ASBUILT_DATE IS  INITIAL.
      GS_MAIN-ASBUILT_DATE =  SY-DATUM.
    ENDIF.

    APPEND GS_MAIN TO GT_MAIN.
    CLEAR: GS_MAIN,MATERIAL_GENERAL_DATA,
                   RETURN,
                   MATERIALPLANTDATA,
                   MATERIALVALUATIONDATA,
                   MATERIAL.
  ENDLOOP.
  GT_MAIN_TMP = GT_MAIN.
  SET PARAMETER ID 'ZRSNUM' FIELD SPACE.
*
ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  SET_OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM SET_OUTPUT.

  CLEAR IT_FIELDCAT.
  CREATE DATA LR_DATA LIKE LINE OF GT_MAIN.

*Create Field Cathlog From Internal Table
  LR_TABDESCR ?= CL_ABAP_STRUCTDESCR=>DESCRIBE_BY_DATA_REF( LR_DATA ).

  LT_DFIES = CL_SALV_DATA_DESCR=>READ_STRUCTDESCR( LR_TABDESCR ).


  LOOP AT LT_DFIES INTO LS_DFIES.
    CLEAR LS_FIELDCAT.
    MOVE-CORRESPONDING LS_DFIES TO LS_FIELDCAT.
    LS_FIELDCAT-REPTEXT_DDIC   = LS_DFIES-FIELDTEXT.
    LS_FIELDCAT-SELTEXT_L = LS_DFIES-FIELDTEXT.
    LS_FIELDCAT-SELTEXT_M = LS_DFIES-FIELDTEXT.
    LS_FIELDCAT-SELTEXT_L = LS_DFIES-FIELDTEXT.
    LS_FIELDCAT-OUTPUTLEN = 12.
    IF LS_DFIES-FIELDNAME = 'UNIT_COST'.
      LS_FIELDCAT-REPTEXT_DDIC      = 'Unit Cost '.
      LS_FIELDCAT-SELTEXT_S    = 'Unit Cost '.
      LS_FIELDCAT-SELTEXT_L    = 'Unit Cost '.
      LS_FIELDCAT-SELTEXT_M    = 'Unit Cost '.
      LS_FIELDCAT-OUTPUTLEN = 10.
    ELSEIF LS_DFIES-FIELDNAME = 'PLANNED_QTY'.
      LS_FIELDCAT-REPTEXT_DDIC      = 'Planned qty'.
      LS_FIELDCAT-SELTEXT_S    = 'Planned qty'.
      LS_FIELDCAT-SELTEXT_L    = 'Planned qty'.
      LS_FIELDCAT-SELTEXT_M    = 'Planned qty'.
      LS_FIELDCAT-OUTPUTLEN = 12.
    ELSEIF LS_DFIES-FIELDNAME = 'RETURN_QTY'.
      LS_FIELDCAT-REPTEXT_DDIC      = 'Return  qty'.
      LS_FIELDCAT-SELTEXT_S    = 'Return  qty'.
      LS_FIELDCAT-SELTEXT_L    = 'Return  qty'.
      LS_FIELDCAT-SELTEXT_M    = 'Return  qty'.
      LS_FIELDCAT-OUTPUTLEN = 10.
    ELSEIF LS_DFIES-FIELDNAME = 'BALANCE_QTY'.
      LS_FIELDCAT-REPTEXT_DDIC      = 'Balance qty '.
      LS_FIELDCAT-SELTEXT_S    = 'Balance qty '.
      LS_FIELDCAT-SELTEXT_L    = 'Balance qty '.
      LS_FIELDCAT-SELTEXT_M    = 'Balance qty '.
      LS_FIELDCAT-OUTPUTLEN = 10.
    ELSEIF LS_DFIES-FIELDNAME = 'OUTSTANDING_QTY'.
      LS_FIELDCAT-REPTEXT_DDIC      = 'Outstanding QTY'.
      LS_FIELDCAT-SELTEXT_S    = 'Outstanding QTY'.
      LS_FIELDCAT-SELTEXT_L    = 'Outstanding QTY'.
      LS_FIELDCAT-SELTEXT_M    = 'Outstanding QTY'.
      LS_FIELDCAT-OUTPUTLEN = 14.
    ELSEIF LS_DFIES-FIELDNAME = 'OUTSTANDING_COST'.
      LS_FIELDCAT-REPTEXT_DDIC      = 'Outstanding Cost'.
      LS_FIELDCAT-SELTEXT_S    = 'Outstanding Cost'.
      LS_FIELDCAT-SELTEXT_L    = 'Outstanding Cost'.
      LS_FIELDCAT-SELTEXT_M    = 'Outstanding Cost'.
      LS_FIELDCAT-OUTPUTLEN = 14..
    ELSEIF LS_DFIES-FIELDNAME = 'ISSUED_QTY'.
      LS_FIELDCAT-REPTEXT_DDIC      = 'Issued qty'.
      LS_FIELDCAT-SELTEXT_S    = 'Issued qty'.
      LS_FIELDCAT-SELTEXT_L    = 'Issued qty'.
      LS_FIELDCAT-SELTEXT_M    = 'Issued qty'.
      LS_FIELDCAT-OUTPUTLEN = 14.
    ELSEIF LS_DFIES-FIELDNAME = 'ASBUILT_COST'.
      LS_FIELDCAT-REPTEXT_DDIC = 'As Build Cost '.
      LS_FIELDCAT-SELTEXT_S    = 'As Build Cost '.
      LS_FIELDCAT-SELTEXT_L    = 'As Build Cost '.
      LS_FIELDCAT-SELTEXT_M    = 'As Build Cost '.
      LS_FIELDCAT-OUTPUTLEN = 14.
    ELSEIF LS_DFIES-FIELDNAME = 'ASBUILT_DATE'.
*      LS_FIELDCAT-EDIT      = ABAP_TRUE.
      LS_FIELDCAT-REF_TABNAME      = 'ZPM_BUILT'.
      LS_FIELDCAT-REF_FIELDNAME      = 'ASBUILT_DATE'.
      LS_FIELDCAT-OUTPUTLEN = 10.
    ELSEIF LS_DFIES-FIELDNAME     = 'ASBUILT_QTY'.
      LS_FIELDCAT-EDIT            = ABAP_TRUE.
      LS_FIELDCAT-REF_TABNAME     = 'ZPM_BUILT'.
      LS_FIELDCAT-REF_FIELDNAME   = 'ASBUILT_QTY'.
      LS_FIELDCAT-DATATYPE   = 'QUAN'.
      LS_FIELDCAT-NO_ZERO =  SPACE..
    ELSEIF LS_DFIES-FIELDNAME     = 'WAERS'.
      LS_FIELDCAT-REPTEXT_DDIC = 'Currency'.
      LS_FIELDCAT-SELTEXT_S    = 'Currency'.
      LS_FIELDCAT-SELTEXT_L    = 'Currency'.
      LS_FIELDCAT-SELTEXT_M    = 'Currency'.
*      LS_FIELDCAT-EDIT            = ABAP_TRUE.
*      LS_FIELDCAT-REF_TABNAME     = 'BKPF'.
*      LS_FIELDCAT-REF_FIELDNAME   = 'WAERS'.
    ENDIF.

*    LS_FIELDCAT-REF_FIELDNAME   = 'WAERS'.
    IF LS_DFIES-FIELDNAME     <> 'CHARG'.
      LS_FIELDCAT-NO_ZERO = 'X'.
    ENDIF.

*    DATA LV_LENGTH TYPE I .
*    IF LS_DFIES-FIELDTEXT IS INITIAL.
*      LV_LENGTH = STRLEN( LS_FIELDCAT-REPTEXT_DDIC ).
*    ELSE.
*      LV_LENGTH = STRLEN( LS_DFIES-FIELDTEXT ).
*    ENDIF.

    APPEND LS_FIELDCAT TO IT_FIELDCAT.
    CLEAR: LS_FIELDCAT,LS_DFIES.
  ENDLOOP.


*Display ALV Report
  CONSTANTS LC_SAVE_ALL TYPE C VALUE 'A'.
*  LS_LAYO-EDIT = 'X'.
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM       = SY-REPID
      I_CALLBACK_TOP_OF_PAGE   = 'TOP_OF_PAGE'
      I_CALLBACK_USER_COMMAND  = 'USER_COMMAND'   "see FORM
      IT_FIELDCAT              = IT_FIELDCAT[]
      I_SAVE                   = LC_SAVE_ALL
      IS_LAYOUT                = LS_LAYO
      I_CALLBACK_PF_STATUS_SET = 'PFSTAT'
*     I_SAVE                   = 'A'
*     IS_VARIANT               = GX_VARIANT
   "  IT_SORT_LVC              = IT_SORT
    TABLES
      T_OUTTAB                 = GT_MAIN "Global Table for output
    EXCEPTIONS
      PROGRAM_ERROR            = 1
      OTHERS                   = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here

  ENDIF.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  TOP_OF_PAGE
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM TOP_OF_PAGE.

  DATA: LT_HEADER TYPE SLIS_T_LISTHEADER,
        LS_HEADER TYPE SLIS_LISTHEADER.

* Set Header in the ALV
  LS_HEADER-TYP  = 'H'.                                                                 "#EC-NOTEXT
  LS_HEADER-INFO = TEXT-001.
  APPEND LS_HEADER TO LT_HEADER.
  CLEAR LS_HEADER.

  LS_HEADER-TYP  = 'S'.
  LS_HEADER-KEY  = TEXT-002.
  LS_HEADER-INFO = SY-DATUM+6(2) && '.' && SY-DATUM+4(2) && '.' && SY-DATUM+0(4).
  APPEND LS_HEADER TO LT_HEADER.
  CLEAR LS_HEADER.


* Set List Comment Output
  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = LT_HEADER.

  CLEAR: LS_HEADER, LT_HEADER[].

ENDFORM.

FORM USER_COMMAND USING R_UCOMM LIKE SY-UCOMM
                  RS_SELFIELD TYPE SLIS_SELFIELD.
* Check function code

  RS_SELFIELD-REFRESH = 'X' .
  DATA REF1 TYPE REF TO CL_GUI_ALV_GRID.

  CALL FUNCTION 'GET_GLOBALS_FROM_SLVC_FULLSCR'
    IMPORTING
      E_GRID = REF1.

  CALL METHOD REF1->CHECK_CHANGED_DATA.
  CASE R_UCOMM.
*    break-point..
    WHEN '&IC1'.

    WHEN 'UPDATE_LST'.
      LOOP AT GT_MAIN ASSIGNING FIELD-SYMBOL(<FS>).
*        IF <FS>-ASBUILT_QTY IS NOT INITIAL.
        <FS>-ASBUILT_COST = <FS>-ASBUILT_QTY *  <FS>-UNIT_COST.
        <FS>-OUTSTANDING_QTY = <FS>-BALANCE_QTY -  <FS>-ASBUILT_QTY.
        <FS>-OUTSTANDING_COST = <FS>-OUTSTANDING_QTY *  <FS>-UNIT_COST.
*        ENDIF.
      ENDLOOP.
    WHEN 'SAVE'.
      BREAK AC_ADNAN.
      DATA:LV_CHECK(1).
      CLEAR LV_CHECK.
      LOOP AT GT_MAIN ASSIGNING FIELD-SYMBOL(<FS_UPD>).
*        IF <FS>-ASBUILT_QTY IS NOT INITIAL.
        <FS_UPD>-ASBUILT_COST = <FS_UPD>-ASBUILT_QTY *  <FS_UPD>-UNIT_COST.
        <FS_UPD>-OUTSTANDING_QTY = <FS_UPD>-BALANCE_QTY -  <FS_UPD>-ASBUILT_QTY.
        <FS_UPD>-OUTSTANDING_COST = <FS_UPD>-OUTSTANDING_QTY *  <FS_UPD>-UNIT_COST.
*        ENDIF.
      ENDLOOP.
*      BREAK-POINT.
      DATA:LV_CHECK_CHANGES(1).

      LOOP AT GT_MAIN ASSIGNING FIELD-SYMBOL(<FS_CHECK>).
        READ TABLE GT_MAIN_TMP INTO DATA(LS_CHECK_UPDATE) WITH KEY AUFNR = <FS_CHECK>-AUFNR MATNR =  <FS_CHECK>-MATNR.
        IF SY-SUBRC = 0.
          IF <FS_CHECK>-ASBUILT_QTY <> LS_CHECK_UPDATE-ASBUILT_QTY.
            LV_CHECK_CHANGES = 'X'.
          ENDIF.
        ENDIF.
        MOVE-CORRESPONDING <FS_CHECK> TO GS_PM_BUILT.
        IF LV_CHECK_CHANGES = 'X'.
          GS_PM_BUILT-ASBUILT_DATE  = SY-DATUM.
          GS_PM_BUILT-UNAME = SY-UNAME.
          GS_PM_BUILT-CPUDT = SY-DATUM.
          GS_PM_BUILT-CPUTM  = SY-UZEIT.
        ELSE.
          GS_PM_BUILT-ASBUILT_DATE  = LS_CHECK_UPDATE-ASBUILT_DATE.
          GS_PM_BUILT-UNAME = LS_CHECK_UPDATE-UNAME.
          GS_PM_BUILT-CPUDT =  LS_CHECK_UPDATE-CPUDT.
          GS_PM_BUILT-CPUTM  = LS_CHECK_UPDATE-CPUTM.
        ENDIF.
**        IF <FS_CHECK>-ASBUILT_QTY IS INITIAL .
**          LV_CHECK = 'X'.
**          MESSAGE 'Fill As Built Qty!' TYPE 'S' DISPLAY LIKE 'E'.
**        ENDIF.
**        IF <FS_CHECK>-ASBUILT_DATE IS INITIAL .
**          LV_CHECK = 'X'.
**          MESSAGE 'Fill As Built Date!' TYPE 'S' DISPLAY LIKE 'E'.
**        ENDIF.
*        IF <FS_CHECK>-ASBUILT_DATE IS NOT INITIAL.
*          "IF  <FS_CHECK>-ASBUILT_COST IS INITIAL OR  <FS_CHECK>-OUTSTANDING_QTY IS INITIAL  OR <FS_CHECK>-OUTSTANDING_COST IS INITIAL.
*          LV_CHECK = 'X'.
*         " MESSAGE 'Field should not be black! Press Update list button to update list'  TYPE 'S' DISPLAY LIKE 'E'.
*          "  ENDIF.
*        ENDIF.



        APPEND GS_PM_BUILT TO GT_PM_BUILT.
        CLEAR GS_PM_BUILT.
        CLEAR LV_CHECK_CHANGES.
      ENDLOOP.
      IF GT_PM_BUILT IS NOT INITIAL.
        MODIFY ZPM_BUILT FROM TABLE GT_PM_BUILT .
        IF SY-SUBRC = 0.
          MESSAGE 'Data Update' TYPE 'S'.
        ENDIF.
      ENDIF.

      CALL FUNCTION 'GET_GLOBALS_FROM_SLVC_FULLSCR'
        IMPORTING
          E_GRID = REF1.

      CALL METHOD REF1->CHECK_CHANGED_DATA.
  ENDCASE.

ENDFORM.
FORM PFSTAT USING P_EXTAB TYPE SLIS_T_EXTAB.

*- Pf status
  SET PF-STATUS 'ZSTANDARD'. "this is we copied
  "it is having all you want
ENDFORM.
