*&---------------------------------------------------------------------*
*& Include          ZPM_PRIDE_TEMPLATE_UPLOAD_S01
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-003.
  PARAMETERS: P_LOAD TYPE  RLGRAP-FILENAME OBLIGATORY. "OBLIGATORY DEFAULT 'D:\Users\nouman.butt\Desktop\testload.xls'.
  PARAMETERS: P_ROUTE TYPE   ZPM_PRIDE_ROUT_T-ROUTE_NAME OBLIGATORY. "OBLIGATORY DEFAULT 'D:\Users\nouman.butt\Desktop\testload.xls'.
  PARAMETERS: P_SDATE TYPE   ZPM_PRIDE_ROUT_T-S_DATE OBLIGATORY. "OBLIGATORY DEFAULT 'D:\Users\nouman.butt\Desktop\testload.xls'.
  PARAMETERS: P_TIME TYPE   ZPM_PRIDE_ROUT_T-S_TIME OBLIGATORY. "OBLIGATORY DEFAULT 'D:\Users\nouman.butt\Desktop\testload.xls'.
*  PARAMETERS: P_EDATE TYPE   ZPM_PRIDE_ROUT_T-S_DATE OBLIGATORY. "OBLIGATORY DEFAULT 'D:\Users\nouman.butt\Desktop\testload.xls'.
*  PARAMETERS: P_ETIME TYPE   ZPM_PRIDE_ROUT_T-S_TIME OBLIGATORY. "OBLIGATORY DEFAULT 'D:\Users\nouman.butt\Desktop\testload.xls'.
  PARAMETERS: P_LOC TYPE   ZPM_PM_PLANT AS LISTBOX VISIBLE LENGTH 10 OBLIGATORY. "OBLIGATORY DEFAULT 'D:\Users\nouman.butt\Desktop\testload.xls'.
  PARAMETERS: P_SCH TYPE  ZPM_PRIDE_ROUT_T-SECHEDULE AS LISTBOX VISIBLE LENGTH 10 OBLIGATORY. "OBLIGATORY DEFAULT 'D:\Users\nouman.butt\Desktop\testload.xls'.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 1.
    SELECTION-SCREEN COMMENT 10(50) TEXT-001.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 10(48) TEXT-002.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B1 .
