*&---------------------------------------------------------------------*
*& Include          ZPM_JOB_CARD_REPORT_F01
*&---------------------------------------------------------------------*
FORM GET_DATA.
  DATA: LOGO    TYPE XSTRING.
*  BREAK-POINT.
*For All Document
  SELECT * FROM AUFK
    INTO TABLE @DATA(LT_AUFK)
    WHERE AUFNR IN @S_AUFNR..


  SORT LT_AUFK BY AUFNR ASCENDING.
  "break AC_ADNAN.
  IF LT_AUFK IS NOT INITIAL.
    SELECT * FROM AFIH
      INTO TABLE @DATA(LT_AFIH)
      FOR ALL ENTRIES IN @LT_AUFK
      WHERE AUFNR = @LT_AUFK-AUFNR.

    SORT LT_AFIH BY AUFNR ASCENDING.

*For Workcenter Text

    SELECT * FROM M_CRAMA
        INTO TABLE @DATA(LT_M_CRAMA)
        FOR ALL ENTRIES IN @LT_AUFK
        WHERE WERKS = @LT_AUFK-WERKS.

    SORT LT_M_CRAMA BY WERKS ASCENDING.



*Get User Status
    SELECT * FROM JCDS
      INTO TABLE @DATA(LT_JCDS)
      FOR ALL ENTRIES IN @LT_AUFK
      WHERE OBJNR = @LT_AUFK-OBJNR
      AND INACT <> 'X'.


*FOr System Status

    SELECT * FROM ZPM_SYSTEM_STAT
     INTO TABLE @DATA(LT_ZPM_SYSTEM_STAT)
     FOR ALL ENTRIES IN @LT_AUFK
     WHERE AUFNR = @LT_AUFK-AUFNR.
    SORT LT_ZPM_SYSTEM_STAT BY UDATE UTIME DESCENDING.
    DELETE LT_ZPM_SYSTEM_STAT WHERE TXT04 <> 'CRTD' AND TXT04 <> 'REL' AND TXT04 <> 'TECO' AND TXT04 <> 'SETT' AND TXT04 <> 'CLSD' AND TXT04 <> 'DLFL'.
    SORT LT_ZPM_SYSTEM_STAT BY UDATE DESCENDING UTIME DESCENDING.
    DELETE ADJACENT DUPLICATES FROM LT_ZPM_SYSTEM_STAT COMPARING OBJNR.

***    BREAK AC_OWAIS.
***    DATA(LV_COUNT) = REDUCE I( INIT I = 0 FOR WA IN LT_ZPM_SYSTEM_STAT NEXT I = I + 1 ).
***    LV_COUNT = LV_COUNT - 1.
****    DELETE LT_ZPM_SYSTEM_STAT INDEX 1
***    DO LV_COUNT TIMES.
***      IF LT_ZPM_SYSTEM_STAT[] IS NOT INITIAL.
***        DELETE LT_ZPM_SYSTEM_STAT INDEX 1.
***      ENDIF.
***    ENDDO.

*    SORT LT_ZPM_SYSTEM_STAT DESCENDING.
*
*    DELETE ADJACENT DUPLICATES FROM LT_ZPM_SYSTEM_STAT COMPARING AUFNR UDATE.



    IF LT_AFIH IS NOT INITIAL.
      SELECT QMNUM, QMNAM,OBJNR,ABCKZ, LACD_DATE
        FROM VIQMEL
        INTO TABLE @DATA(LT_VIQMEL)
        FOR ALL ENTRIES IN @LT_AFIH
        WHERE QMNUM = @LT_AFIH-QMNUM.

      SORT LT_VIQMEL BY QMNUM ASCENDING.

      IF LT_VIQMEL IS NOT INITIAL.
*Get User Status
        SELECT * FROM JCDS
         APPENDING CORRESPONDING FIELDS OF TABLE @LT_JCDS
          FOR ALL ENTRIES IN @LT_VIQMEL
          WHERE OBJNR = @LT_VIQMEL-OBJNR
          AND   INACT <> 'X'.

*Get User Status
        SELECT * FROM T370C_T
         INTO TABLE @DATA(LT_T370C_T)
          FOR ALL ENTRIES IN @LT_VIQMEL
          WHERE ABCKZ = @LT_VIQMEL-ABCKZ."ABCTX

        SORT LT_T370C_T BY ABCKZ ASCENDING.

      ENDIF.
    ENDIF.
    SELECT * FROM T003P
      INTO TABLE @DATA(LT_T003P)
      FOR ALL ENTRIES IN @LT_AUFK
      WHERE AUART = @LT_AUFK-AUART
      AND SPRAS = @SY-LANGU.

    SORT LT_T003P BY AUART ASCENDING.


    SELECT * FROM EQUZ
      INTO TABLE @DATA(LT_EQUZ_MAIN_EQPT)
      FOR ALL ENTRIES IN @LT_AFIH
      WHERE EQUNR = @LT_AFIH-EQUNR
      AND DATBI = '99991231'.
    SORT LT_EQUZ_MAIN_EQPT BY HEQUI ASCENDING.

    SELECT * FROM EQUZ
      INTO TABLE @DATA(LT_EQUZ)
*      FOR ALL ENTRIES IN @LT_AFIH
*      WHERE EQUNR = @LT_AFIH-EQUNR
      WHERE DATBI = '99991231'.

    SORT LT_EQUZ BY HEQUI ASCENDING.

  ENDIF.
  SORT LT_AFIH BY AUFNR ASCENDING.

*For Rev Text
  IF LT_AFIH IS NOT INITIAL.
    SELECT * FROM T352R
      INTO TABLE @DATA(LT_T352R)
      FOR ALL ENTRIES IN @LT_AFIH
      WHERE IWERK = @LT_AFIH-IWERK
      AND REVNR = @LT_AFIH-REVNR.

    SORT LT_T352R BY IWERK REVNR ASCENDING.

**    SELECT * FROM MPLA
**      INTO TABLE @DATA(LT_MPLA)
**      FOR ALL ENTRIES IN @LT_AFIH
**      WHERE WARPL = @LT_AFIH-WARPL
**      AND   ABNUM = @LT_AFIH-ABNUM
**      AND   WAPOS = @LT_AFIH-WAPOS.
**
**
**
**    SORT LT_MPLA BY WARPL ASCENDING.
**                     ABNUM
**                     WAPOS.
**
***MPLA

*For Plaining Planr and descprition

    SELECT * FROM T024I
      INTO TABLE @DATA(LT_T024I)
      FOR ALL ENTRIES IN @LT_AFIH
      WHERE IWERK = @LT_AFIH-IWERK
      AND INGRP = @LT_AFIH-INGPR.
  ENDIF.

  SORT LT_T024I BY IWERK INGRP ASCENDING.


  SELECT * FROM TJ02T
    INTO TABLE @DATA(LT_TJ02T)
    WHERE SPRAS = @SY-LANGU.

  SORT LT_TJ02T BY ISTAT ASCENDING.

*For User Status
  IF LT_VIQMEL IS NOT INITIAL.
    SELECT * FROM JSTO
         INTO TABLE @DATA(LT_JSTO)
         FOR ALL ENTRIES IN @LT_VIQMEL
         WHERE OBJNR = @LT_VIQMEL-OBJNR.
    SORT LT_JSTO  BY OBJNR  ASCENDING.

    SELECT * FROM TJ30T
      INTO TABLE @DATA(LT_TJ30T)
      FOR ALL ENTRIES IN @LT_JSTO
      WHERE STSMA = @LT_JSTO-STSMA
      AND SPRAS = @SY-LANGU.

    SORT LT_TJ30T  BY ESTAT  ASCENDING.

  ENDIF.

  SELECT * FROM T353I_T
    INTO TABLE @DATA(LT_T353I_T)
    WHERE SPRAS = @SY-LANGU.

  SORT LT_T353I_T BY ILART ASCENDING.


  SELECT EQUNR,EQKTX
    FROM EQKT INTO TABLE
    @DATA(LT_EQKTX)
    WHERE SPRAS = @SY-LANGU.

  SORT LT_EQKTX BY EQUNR ASCENDING.



  SORT LT_JCDS BY OBJNR  ASCENDING.
  SORT LT_JCDS BY UDATE DESCENDING UTIME DESCENDING.
*break-point.
  DELETE ADJACENT DUPLICATES FROM LT_JCDS COMPARING OBJNR STAT+(1).


*For Prority
  SELECT * FROM T356_T
    INTO TABLE @DATA(LT_T356_T)
    FOR ALL ENTRIES IN @LT_AFIH
    WHERE SPRAS = @SY-LANGU
      AND ARTPR = @LT_AFIH-ARTPR.

  SORT LT_T356_T BY PRIOK ASCENDING.

  LOOP AT LT_AUFK INTO DATA(LS_AUFK).
    CALL FUNCTION 'BAPI_ALM_ORDER_GET_DETAIL'
      EXPORTING
        NUMBER                   = LS_AUFK-AUFNR
      IMPORTING
        ES_HEADER                = ES_HEADER
        ES_SRVDATA               = ES_SRVDATA
        ES_REFORDER_ITEM         = ES_REFORDER_ITEM
        ES_JVA_DATA              = ES_JVA_DATA
      TABLES
        ET_PARTNER               = ET_PARTNER
        ET_OPERATIONS            = ET_OPERATIONS
        ET_COMPONENTS            = ET_COMPONENTS
        ET_RELATIONS             = ET_RELATIONS
        ET_SRULES                = ET_SRULES
        ET_OLIST                 = ET_OLIST
        ET_OPROL                 = ET_OPROL
        ET_TEXTS                 = ET_TEXTS
        ET_TEXT_LINES            = ET_TEXT_LINES
        ET_PRTS                  = ET_PRTS
        ET_COSTS_SUM             = ET_COSTS_SUM
        ET_COSTS_DETAILS         = ET_COSTS_DETAILS
        RETURN                   = RETURN
        EXTENSION_IN             = EXTENSION_IN
        EXTENSION_OUT            = EXTENSION_OUT
        ET_REFORDER_SERNO_OLIST  = ET_REFORDER_SERNO_OLIST
        ET_SERVICEOUTLINE        = ET_SERVICEOUTLINE
        ET_SERVICELINES          = ET_SERVICELINES
        ET_SERVICELIMIT          = ET_SERVICELIMIT
        ET_SERVICECONTRACTLIMITS = ET_SERVICECONTRACTLIMITS
        ET_PERMIT                = ET_PERMIT
        ET_PERMIT_ISSUE          = ET_PERMIT_ISSUE
        ET_ADDITIONAL_TEXTS      = ET_ADDITIONAL_TEXTS.

    MOVE-CORRESPONDING ES_HEADER TO GS_MAIN.
*/****** Get the company Code Data along with the LOGO.
    SELECT SINGLE * FROM ZCDS_GET_COMPANY_DATA INTO @DATA(LS_CC)
      WHERE COMPANYCODE = @ES_HEADER-COMP_CODE.

    CASE ES_HEADER-COMP_CODE.
      WHEN 'P060'.
        CALL FUNCTION 'ZABAP_LOGO_GET'
          EXPORTING
            IM_BUKRS = ES_HEADER-COMP_CODE
            IM_NAME  = 'HCM_P060'
            IM_TYPE  = 'HCM'
          IMPORTING
            EX_LOGO  = LOGO.
      WHEN OTHERS.
        CALL FUNCTION 'ZABAP_LOGO_GET'
          EXPORTING
            IM_BUKRS = ES_HEADER-COMP_CODE
            IM_TYPE  = 'HCM'
          IMPORTING
            EX_LOGO  = LOGO.
    ENDCASE.
    GV_LOGO = LOGO.
*    GS_MAIN-LOGO = LOGO.
*    GS_MAIN-COMPANY_NAME = LS_CC-SUPPLIERFULLNAME.
    GV_COMP_NAME = LS_CC-SUPPLIERFULLNAME.
*/*******

    GS_MAIN-PRINT_DATE = SY-DATUM.
*    GS_MAIN-FINISH_DATE = ES_HEADER-START_DATE.
    GS_MAIN-PRODUCTION_FINISH_DATE = ES_HEADER-START_DATE.
    IF LS_AUFK-AUART <> 'YBA4' AND LS_AUFK-AUART <> 'YBA9'.
      DATA(LV_QMNUM) = VALUE #( LT_AFIH[ AUFNR = LS_AUFK-AUFNR ]-QMNUM OPTIONAL ).
      GS_MAIN-PRODUCTION_FINISH_DATE = VALUE #( LT_VIQMEL[ QMNUM = LV_QMNUM ]-LACD_DATE OPTIONAL ).
    ENDIF.


*For System Status
*break-point.
    DATA(LS_SYSTEM_STATUS)  = VALUE #( LT_ZPM_SYSTEM_STAT[ AUFNR = ES_HEADER-ORDERID ] OPTIONAL ).
    GS_MAIN-STAT = LS_SYSTEM_STATUS-TXT04.
    GS_MAIN-TXT30 = LS_SYSTEM_STATUS-TXT30.
    GS_MAIN-UDATE =  LS_SYSTEM_STATUS-UDATE.
*Move Long Text conct

*For Order Type Text
    GS_MAIN-DESCRIPTION = VALUE #( LT_T003P[ AUART = ES_HEADER-ORDER_TYPE ]-TXT OPTIONAL ).
*REVISION

    GS_MAIN-REVISION = VALUE #( LT_T352R[ IWERK = ES_HEADER-PLANPLANT REVNR =  ES_HEADER-REVISION ]-REVTX OPTIONAL ).


    READ TABLE ET_OPERATIONS INTO DATA(LS_OPT) INDEX 1.
    IF SY-SUBRC = 0.
*    MOVE-CORRESPONDING LS_OPT TO GS_MAIN.
      MOVE LS_OPT-WORK_CNTR        TO GS_MAIN-WORK_CNTR.
      MOVE LS_OPT-PLANT            TO GS_MAIN-PLANPLANT.
      MOVE LS_OPT-DESCRIPTION      TO GS_MAIN-ACTIVITY_TXT.
      MOVE LS_OPT-ACTIVITY      TO GS_MAIN-ACTIVITY.
      MOVE LS_OPT-DURATION_NORMAL  TO GS_MAIN-DURATION_NORMAL.

*For Work Center Text
*For Order Type Text
      GS_MAIN-KTEXT = VALUE #( LT_M_CRAMA[ WERKS = ES_HEADER-PLANPLANT ARBPL = LS_OPT-WORK_CNTR  ]-KTEXT OPTIONAL ).

    ENDIF.
*For Priority Text
    READ TABLE LT_T356_T INTO DATA(LS_T356_T) WITH KEY PRIOK = GS_MAIN-PRIORITY ARTPR = ES_HEADER-PRIOTYPE BINARY SEARCH."ARTPR = ls
    IF SY-SUBRC = 0.
      MOVE LS_T356_T-PRIOKX        TO GS_MAIN-PRIORITY_TEXT.
    ENDIF.


*For Activity Type
    READ TABLE LT_T353I_T INTO DATA(LS_T353I_T) WITH KEY ILART = ES_HEADER-PMACTTYPE BINARY SEARCH.
    IF SY-SUBRC = 0.
      GS_MAIN-ACTTYPE = ES_HEADER-PMACTTYPE && |  | && '-' && |  | && LS_T353I_T-ILATX.
    ENDIF.

    DATA : BEGIN OF WA_TEMP,
             C1(20) TYPE C,
             C2(20) TYPE C,
             C3(20) TYPE C,
             C4(20) TYPE C,
             C5(20) TYPE C,
           END OF WA_TEMP.

    SPLIT GS_MAIN-FUNCT_LOC AT '-' INTO WA_TEMP-C1 WA_TEMP-C2 WA_TEMP-C3 WA_TEMP-C4 WA_TEMP-C5.

    GS_MAIN-FUNCLOC_DISP = WA_TEMP-C1 && '-' && WA_TEMP-C2 && '-' &&  WA_TEMP-C3 && '-' &&  WA_TEMP-C4.

    SELECT SINGLE PLTXT FROM IFLO INTO @DATA(FUNL_COM_DISP)
      WHERE TPLNR = @GS_MAIN-FUNCT_LOC.

    SELECT SINGLE PLTXT FROM IFLO INTO @GS_MAIN-FUNCLOC_DISP
      WHERE TPLNR = @GS_MAIN-FUNCLOC_DISP.
    IF GS_MAIN-FUNCT_LOC IS NOT INITIAL.
      GS_MAIN-FUNCLOC_DISP = FUNL_COM_DISP && '/' && GS_MAIN-FUNCLOC_DISP.
    ENDIF.

**    READ TABLE ET_OLIST INTO DATA(LS_OLIST) INDEX 1.
**    IF SY-SUBRC = 0.
**      MOVE-CORRESPONDING LS_OLIST TO GS_MAIN.
**      MOVE LS_OLIST-FUNCLDESCR TO GS_MAIN-FUNCLOC_DISP.
**    ENDIF.

    READ TABLE LT_T024I INTO DATA(LS_T024I) WITH KEY IWERK = ES_HEADER-PLANPLANT INGRP = ES_HEADER-PLANGROUP BINARY SEARCH.
    IF SY-SUBRC = 0.
      MOVE  LS_T024I-INNAM TO GS_MAIN-INNAM.
    ENDIF.

    DATA: LV_EQUNR TYPE EQUNR.
    DATA: LV_ROOT(1).

    CLEAR: LV_EQUNR, LV_ROOT.
    LV_EQUNR = ES_HEADER-EQUIPMENT.
    IF LV_EQUNR IS NOT INITIAL.
      WHILE ( LV_ROOT NE 'X' ).
        LOOP AT LT_EQUZ INTO DATA(LS_ROOT) WHERE EQUNR EQ LV_EQUNR.
          IF LS_ROOT-HEQUI EQ ''.
            LV_ROOT = 'X'.
          ELSE.
            LV_EQUNR = LS_ROOT-HEQUI.

          ENDIF.
        ENDLOOP.
        IF SY-SUBRC NE 0.
          LV_ROOT = 'X'.
        ENDIF.
      ENDWHILE.
    ENDIF.
    "break AC_ADNAN.
    GS_MAIN-HEQUI = LS_ROOT-TIDNR.
    GS_MAIN-HEQUI = LS_ROOT-TIDNR.
*    GS_MAIN-HEQUI = LV_EQUNR.
*    BREAK-POINT.
    READ TABLE LT_EQKTX INTO DATA(LS_EQKTX) WITH KEY EQUNR = LS_ROOT-EQUNR  BINARY SEARCH.
    IF SY-SUBRC = 0.
*      MOVE  LS_EQUZ-HEQUI TO GS_MAIN-HEQUI.
      MOVE  LS_EQKTX-EQKTX TO GS_MAIN-R_DESC.
    ENDIF.

    CLEAR LS_ROOT.

    READ TABLE LT_EQUZ_MAIN_EQPT INTO DATA(LS_EQUZ) WITH KEY EQUNR = ES_HEADER-EQUIPMENT  BINARY SEARCH.
    IF SY-SUBRC = 0.
*      MOVE  LS_EQUZ-HEQUI TO GS_MAIN-HEQUI.
      MOVE  LS_EQUZ-TIDNR TO GS_MAIN-TIDNR.
    ENDIF.

    READ TABLE LT_EQKTX INTO LS_EQKTX WITH KEY EQUNR = ES_HEADER-EQUIPMENT.
    IF SY-SUBRC EQ 0.
      MOVE LS_EQKTX-EQKTX TO GS_MAIN-EQUIDESCR.
    ENDIF.

*For Reported by
    READ TABLE LT_VIQMEL INTO DATA(LS_VIQMEL) WITH KEY QMNUM = ES_HEADER-NOTIF_NO  BINARY SEARCH.
    IF SY-SUBRC = 0.

*For Eq. Priority/ABC Ind
      GS_MAIN-ABCTX = LS_VIQMEL-ABCKZ && |  | && '-' && |  | && VALUE #( LT_T370C_T[ ABCKZ = LS_VIQMEL-ABCKZ ]-ABCTX OPTIONAL ).

      DATA: BNAME      TYPE USR03-BNAME,
            OKCODE     TYPE C,
            USER_USR03 TYPE USR03.

      BNAME      =   LS_VIQMEL-QMNAM.
      CALL FUNCTION 'SUSR_SHOW_USER_DETAILS'
        EXPORTING
          BNAME      = BNAME
          MANDT      = SY-MANDT
          NO_DISPLAY = 'X'
        IMPORTING
          OKCODE     = OKCODE
*         ADDR_USR   = ADDR_USR
        CHANGING
          USER_USR03 = USER_USR03.


      GS_MAIN-ENTERED_BY = USER_USR03-NAME1 && | | && USER_USR03-NAME2.
      CLEAR BNAME.
    ENDIF.


*For User Status

    IF ES_HEADER-ORDER_TYPE = 'YBA4' OR  ES_HEADER-ORDER_TYPE = 'YBA9'.

      READ TABLE LT_JCDS INTO DATA(LS_JCDS) WITH KEY OBJNR = ES_HEADER-OBJECT_NO STAT+0(1) = 'E'.
      IF SY-SUBRC = 0.
        MOVE  LS_JCDS-USNAM TO GS_MAIN-USNAM.
        MOVE  LS_JCDS-UDATE TO GS_MAIN-UDATE_2.

        READ TABLE LT_TJ02T INTO DATA(LS_TJ02T) WITH KEY ISTAT = LS_JCDS-STAT .
        IF SY-SUBRC = 0.
          MOVE  LS_JCDS-USNAM TO GS_MAIN-USER_STATUS.
        ENDIF.
      ENDIF.
    ELSE.
      READ TABLE LT_JCDS INTO LS_JCDS WITH KEY OBJNR = LS_VIQMEL-OBJNR STAT+0(1) = 'E'.
      IF SY-SUBRC = 0.
        MOVE  LS_JCDS-USNAM TO GS_MAIN-USNAM.
        MOVE  LS_JCDS-UDATE TO GS_MAIN-UDATE_2.
        READ TABLE LT_JSTO INTO DATA(LS_JSTO) WITH KEY OBJNR = LS_VIQMEL-OBJNR.
        IF SY-SUBRC = 0.
          READ TABLE LT_TJ30T INTO DATA(LS_TJ30T) WITH KEY ESTAT = LS_JCDS-STAT STSMA = LS_JSTO-STSMA .
          IF SY-SUBRC = 0.
            MOVE  LS_TJ30T-TXT30 TO GS_MAIN-USER_STATUS.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.


    DATA OPTIONS              TYPE STANDARD TABLE OF RFC_DB_OPT.
    DATA LS_OPTIONS              TYPE RFC_DB_OPT.
    DATA FIELDS               TYPE STANDARD TABLE OF RFC_DB_FLD.
    DATA LS_FIELDS               TYPE RFC_DB_FLD.
    DATA DATA                 TYPE STANDARD TABLE OF TAB512.

*BOC For Read WBS Desc
    LS_OPTIONS-TEXT = 'PSPNR EQ' && | | && '' && ES_HEADER-WBS_ELEM && ''.
    APPEND LS_OPTIONS TO OPTIONS.

    LS_FIELDS-FIELDNAME = 'POST1'.
    APPEND LS_FIELDS TO FIELDS.

    CALL FUNCTION 'RFC_READ_TABLE'
      EXPORTING
        QUERY_TABLE          = 'PRPS'
*       DELIMITER            = ' '
*       NO_DATA              = ' '
*       ROWSKIPS             = 0
*       ROWCOUNT             = 0
*       GET_SORTED           = GET_SORTED
*       USE_ET_DATA_4_RETURN = USE_ET_DATA_4_RETURN
* IMPORTING
*       ET_DATA              = ET_DATA
      TABLES
        OPTIONS              = OPTIONS
        FIELDS               = FIELDS
        DATA                 = DATA
      EXCEPTIONS
        TABLE_NOT_AVAILABLE  = 1
        TABLE_WITHOUT_DATA   = 2
        OPTION_NOT_VALID     = 3
        FIELD_NOT_VALID      = 4
        NOT_AUTHORIZED       = 5
        DATA_BUFFER_EXCEEDED = 6.

    GS_MAIN-POST1 = VALUE #( DATA[ 1 ]-WA OPTIONAL ).
    FREE:OPTIONS,
         FIELDS,
         DATA.

*EOC For Read WBS Desc

*BOC For Task List Text
    LS_OPTIONS-TEXT = 'PLNTY EQ' && | | && '''' && ES_HEADER-TASK_LIST_TYPE && ''''
    && | | && 'AND PLNNR EQ' && | | && '''' && ES_HEADER-TASK_LIST_GROUP && ''''
    && | | && 'AND PLNAL EQ' && | | && '''' && ES_HEADER-GROUP_COUNTER && ''''.
    APPEND LS_OPTIONS TO OPTIONS.

    LS_FIELDS-FIELDNAME = 'KTEXT'.
    APPEND LS_FIELDS TO FIELDS.

    CALL FUNCTION 'RFC_READ_TABLE'
      EXPORTING
        QUERY_TABLE          = 'PLKO'
*       DELIMITER            = ' '
*       NO_DATA              = ' '
*       ROWSKIPS             = 0
*       ROWCOUNT             = 0
*       GET_SORTED           = GET_SORTED
*       USE_ET_DATA_4_RETURN = USE_ET_DATA_4_RETURN
* IMPORTING
*       ET_DATA              = ET_DATA
      TABLES
        OPTIONS              = OPTIONS
        FIELDS               = FIELDS
        DATA                 = DATA
      EXCEPTIONS
        TABLE_NOT_AVAILABLE  = 1
        TABLE_WITHOUT_DATA   = 2
        OPTION_NOT_VALID     = 3
        FIELD_NOT_VALID      = 4
        NOT_AUTHORIZED       = 5
        DATA_BUFFER_EXCEEDED = 6.

    GS_MAIN-TASK_LIST_REXR = VALUE #( DATA[ 1 ]-WA OPTIONAL ).

*  ENDIF.
*For LOng Text
    NAME = SY-MANDT && ES_HEADER-ORDERID.

    CALL FUNCTION 'READ_TEXT'
      EXPORTING
*       CLIENT                  = SY-MANDT
        ID                      = 'KOPF'
        LANGUAGE                = SY-LANGU
        NAME                    = NAME
        OBJECT                  = 'AUFK'
*       ARCHIVE_HANDLE          = 0
*       LOCAL_CAT               = ' '
      IMPORTING
        HEADER                  = HEADER
        OLD_LINE_COUNTER        = OLD_LINE_COUNTER
      TABLES
        LINES                   = LINES
      EXCEPTIONS
        ID                      = 1
        LANGUAGE                = 2
        NAME                    = 3
        NOT_FOUND               = 4
        OBJECT                  = 5
        REFERENCE_CHECK         = 6
        WRONG_ACCESS_TO_ARCHIVE = 7.
    "break-POINT.
    GS_MAIN-LONG_TEXT =  REDUCE #( INIT TEXT = `` FOR <LINE1> IN LINES NEXT  TEXT = TEXT && | | && <LINE1>-TDLINE  ).
    CONDENSE GS_MAIN-LONG_TEXT.

*LOng Text Logic
    BREAK AC_ADNAN.
    DATA:LV_TASK_LIST TYPE C LENGTH 8.
    DATA : S TYPE C VALUE ' '.
    DATA LV_INT TYPE I.
    DATA LV_INT_COUNT_REMAINING TYPE I.
    CLEAR LV_INT_COUNT_REMAINING.
    CLEAR LV_INT.
    CLEAR LV_TASK_LIST.

    IF ES_HEADER-TASK_LIST_GROUP IS NOT INITIAL.
      LV_INT = STRLEN( ES_HEADER-TASK_LIST_GROUP ).
      LV_INT_COUNT_REMAINING = 8 - LV_INT.
      LV_TASK_LIST = ES_HEADER-TASK_LIST_GROUP.
      DO LV_INT_COUNT_REMAINING TIMES.
        CONCATENATE LV_TASK_LIST '&' INTO LV_TASK_LIST.
*        LV_TASK_LIST = LV_TASK_LIST && ''.
      ENDDO.
    ENDIF.

    SELECT  SINGLE AUFPL,
          APLZL,
          PLNFL,
          PLNKN,
          ZAEHL
      FROM AFVC
      INTO @DATA(LS_AFVC)
      WHERE AUFPL = @ES_HEADER-ROUTING_NO AND
      APLZL = '00000001' AND
      PLNNR = @ES_HEADER-TASK_LIST_GROUP
      AND PLNTY = @ES_HEADER-TASK_LIST_TYPE
      AND PLNAL = @ES_HEADER-GROUP_COUNTER.


    " LV_TASK_LIST = ES_HEADER-TASK_LIST_GROUP && LV_TASK_LIST.
    "break-POINT."110A000000320000000100000001              200100000017500000001
    NAME = SY-MANDT && ES_HEADER-TASK_LIST_TYPE && LV_TASK_LIST && LS_AFVC-PLNKN && LS_AFVC-ZAEHL.

    WHILE NAME CS '&'.

      NAME+SY-FDPOS(1) = SPACE.

    ENDWHILE.


*    REPLACE ALL OCCURRENCES OF '&' IN NAME WITH SPACE.
    FREE LINES.
    CALL FUNCTION 'READ_TEXT'
      EXPORTING
*       CLIENT                  = SY-MANDT
        ID                      = 'PLPO'
        LANGUAGE                = SY-LANGU
        NAME                    = NAME
        OBJECT                  = 'ROUTING'
*       ARCHIVE_HANDLE          = 0
*       LOCAL_CAT               = ' '
      IMPORTING
        HEADER                  = HEADER
        OLD_LINE_COUNTER        = OLD_LINE_COUNTER
      TABLES
        LINES                   = LINES
      EXCEPTIONS
        ID                      = 1
        LANGUAGE                = 2
        NAME                    = 3
        NOT_FOUND               = 4
        OBJECT                  = 5
        REFERENCE_CHECK         = 6
        WRONG_ACCESS_TO_ARCHIVE = 7.



    DATA IT_TLINE       TYPE IDMX_DI_T_TLINE.
    DATA LS_TLINE       TYPE TLINE.
    DATA EV_TEXT_STRING TYPE STRING.

    MOVE-CORRESPONDING LINES TO IT_TLINE.

*******************    LOOP AT GT_PO_SERVICES_TEXTS INTO DATA(LS_TEXT).
*******************
*******************      LS_TLINE-TDFORMAT = LS_TEXT-FORMAT_COL.
*******************      LS_TLINE-TDLINE = LS_TEXT-TEXT_LINE.
*******************      APPEND LS_TLINE TO IT_TLINE.
*******************      CLEAR LS_TLINE.
*******************
*******************    ENDLOOP.
    CALL FUNCTION 'IDMX_DI_TLINE_INTO_STRING'
      EXPORTING
        IT_TLINE       = IT_TLINE
      IMPORTING
        EV_TEXT_STRING = GS_MAIN-TDLINE.



**
**
**
**
**
**    GS_MAIN-TDLINE = REDUCE STRING( INIT LV_WHERE_CLAUSE TYPE STRING
**                                 FOR LS_WERKS  IN LINES
**                               NEXT LV_WHERE_CLAUSE = LV_WHERE_CLAUSE && LS_WERKS-TDLINE  ).


    SHIFT GS_MAIN-EQUIPMENT LEFT DELETING LEADING '0'.
    SHIFT GS_MAIN-TASK_LIST_GROUP LEFT DELETING LEADING '0'.
    APPEND GS_MAIN TO GT_MAIN.
    FREE:GS_MAIN,ET_OLIST,ET_OPERATIONS,ES_HEADER,LS_ROOT,LS_TJ02T,LS_JCDS,LS_T024I,LS_OPT,HEADER,OLD_LINE_COUNTER,LINES,NAME."LS_OLIST.




  ENDLOOP.


ENDFORM.

*&---------------------------------------------------------------------*
*& Include          ZFI_VOID_CHECK_REGISTER_F01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  SET_OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

FORM SET_OUTPUT .

  DATA: FM_NAME         TYPE RS38L_FNAM,
        FP_DOCPARAMS    TYPE SFPDOCPARAMS,
        FP_OUTPUTPARAMS TYPE SFPOUTPUTPARAMS.



  CALL FUNCTION 'FP_JOB_OPEN'
    CHANGING
      IE_OUTPUTPARAMS = FP_OUTPUTPARAMS
    EXCEPTIONS
      CANCEL          = 1
      USAGE_ERROR     = 2
      SYSTEM_ERROR    = 3
      INTERNAL_ERROR  = 4
      OTHERS          = 5.

  IF SY-SUBRC <> 0.
    " MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CALL FUNCTION 'FP_FUNCTION_MODULE_NAME'           "& Form Processing Generation
    EXPORTING
      I_NAME     = 'ZPM_JOB_CARD_FORM'
    IMPORTING
      E_FUNCNAME = FM_NAME.

  ORDER = S_AUFNR-LOW.
  SHIFT ORDER LEFT DELETING LEADING '0'.
  P_DATE = SY-DATUM.


  CALL FUNCTION FM_NAME
    EXPORTING
      /1BCDWB/DOCPARAMS = FP_DOCPARAMS
      P_DATE            = P_DATE
      ORDER             = ORDER
*     REPORT_DATE       = REPORT_DATE
*     PERIOD_FROM       = PERIOD_FROM
*     PERIOD_TO         = PERIOD_TO
*     BANKA             = BANKA
*     BANKN             = BANKN
*     BRNCH             = BRNCH
*     WAERS             = WAERS
*     TOTAL             = TOTAL
      GT_MAIN           = GT_MAIN
      LOGO              = GV_LOGO
      NAME              = GV_COMP_NAME
*    IMPORTING
*     /1BCDWB/FORMOUTPUT       =
    EXCEPTIONS
      USAGE_ERROR       = 1
      SYSTEM_ERROR      = 2
      INTERNAL_ERROR    = 3.

  IF SY-SUBRC <> 0.
    "MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CALL FUNCTION 'FP_JOB_CLOSE'
*    IMPORTING
*     E_RESULT             =
    EXCEPTIONS
      USAGE_ERROR    = 1
      SYSTEM_ERROR   = 2
      INTERNAL_ERROR = 3
      OTHERS         = 4.

  IF SY-SUBRC <> 0.
    " MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.
