*&---------------------------------------------------------------------*
*& Include          ZFI_VOID_CHECK_REGISTER_S01
*&---------------------------------------------------------------------*
TABLES:AUFK,DIAUFK,RIHEA.
SELECT-OPTIONS:AUFNR FOR AUFK-AUFNR.
SELECT-OPTIONS:AUART FOR AUFK-AUART .
SELECT-OPTIONS:STRNO FOR DIAUFK-STRNO .
SELECT-OPTIONS:EQUNR FOR DIAUFK-EQUNR .
SELECT-OPTIONS:SERMAT FOR DIAUFK-SERMAT .
SELECT-OPTIONS:QMNUM FOR DIAUFK-QMNUM .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 1(28) TEXT-003.
  SELECTION-SCREEN POSITION 35 .
  PARAMETERS:DATUV TYPE RIHEA-TERMAB DEFAULT SY-DATUM .
  SELECTION-SCREEN COMMENT 54(6) TEXT-004 FOR FIELD DATUB.
  PARAMETERS:DATUB TYPE RIHEA-TERMBI DEFAULT SY-DATUM .
SELECTION-SCREEN END OF LINE.
