*&---------------------------------------------------------------------*
*& Include          ZPM_JOB_CARD_REPORT_F01
*&---------------------------------------------------------------------*
FORM GET_DATA.


*For All Status text
  SELECT * FROM TJ02T
    INTO TABLE @DATA(LT_TJ02T)
    WHERE SPRAS = @SY-LANGU.

  SORT LT_TJ02T BY ISTAT ASCENDING.

  SELECT * FROM USER_ADDR
    INTO TABLE @DATA(LT_USER_ADDR).

  SORT LT_USER_ADDR BY BNAME ASCENDING.


*For Movement Type
  SELECT * FROM T353I_T
    INTO TABLE @DATA(LT_T353I_T)
    WHERE SPRAS = @SY-LANGU.

  SORT LT_T353I_T BY ILART ASCENDING.

*For Movement Type
  SELECT * FROM T001W
    INTO TABLE @DATA(LT_T001W).

  SORT LT_T001W BY WERKS ASCENDING.



*For All Document
  SELECT * FROM VIQMEL
    INTO TABLE @DATA(LT_VIQMEL)
    WHERE QMNUM IN @S_QMNUM
    AND QMART = 'M8'..

  SORT LT_VIQMEL BY QMNUM ASCENDING.


*For Concession type
  IF LT_VIQMEL IS NOT INITIAL.
*For Cuntional Localtion custom
    SELECT * FROM IFLO
      INTO TABLE @DATA(LT_IFLO)
      FOR ALL ENTRIES IN @LT_VIQMEL
      WHERE TPLNR = @LT_VIQMEL-ZQMTXT+0(30)
      AND SPRAS = @SY-LANGU.

    SORT LT_IFLO BY TPLNR ASCENDING.
*For Cuntional Localtion Standed
    SELECT * FROM IFLO
      APPENDING CORRESPONDING FIELDS OF TABLE @LT_IFLO
      FOR ALL ENTRIES IN @LT_VIQMEL
      WHERE TPLNR = @LT_VIQMEL-TPLNR
      AND SPRAS = @SY-LANGU.

    SORT LT_IFLO BY TPLNR ASCENDING.

    SELECT EQUNR,TIDNR FROM EQUZ
        INTO TABLE @DATA(LT_EQUZ)
        FOR ALL ENTRIES IN @LT_VIQMEL
        WHERE EQUNR = @LT_VIQMEL-EQUNR.


*For Code texts Asset Condition
    SELECT * FROM QPCT
     INTO TABLE  @DATA(LT_QPCT)
      FOR ALL ENTRIES IN @LT_VIQMEL
      WHERE KATALOGART = @LT_VIQMEL-QMKAT
       AND  CODEGRUPPE = @LT_VIQMEL-QMGRP
       AND  CODE = @LT_VIQMEL-QMCOD
        AND SPRACHE = @SY-LANGU.

    SORT LT_QPCT BY KATALOGART CODEGRUPPE CODE ASCENDING.
*For Movement Reason

    SELECT * FROM T352R
      INTO TABLE @DATA(LT_T352R)
      FOR ALL ENTRIES IN @LT_VIQMEL
      WHERE REVNR = @LT_VIQMEL-REVNR
      AND IWERK = @LT_VIQMEL-IWERK.

    SORT LT_T352R BY REVNR IWERK  ASCENDING.


*For Remakrs and singnature *Reciving Fac
    "break ac_Adnan.
    SELECT * FROM JCDS
    INTO TABLE @DATA(LT_JCDS)
          FOR ALL ENTRIES IN @LT_VIQMEL
          WHERE OBJNR = @LT_VIQMEL-OBJNR
          AND STAT LIKE 'E%'
          AND INACT <> 'X'.

    SORT LT_JCDS BY UDATE UTIME STAT DESCENDING.
    DELETE ADJACENT DUPLICATES FROM LT_JCDS COMPARING OBJNR UDATE STAT.

    SELECT * FROM JSTO
         INTO TABLE @DATA(LT_JSTO)
         FOR ALL ENTRIES IN @LT_VIQMEL
         WHERE OBJNR = @LT_VIQMEL-OBJNR .
    SORT LT_JSTO  BY OBJNR  ASCENDING.

    SELECT * FROM TJ30T
      INTO TABLE @DATA(LT_TJ30T)
      FOR ALL ENTRIES IN @LT_JSTO
      WHERE STSMA = @LT_JSTO-STSMA
     AND SPRAS = @SY-LANGU.

    SORT LT_TJ30T  BY ESTAT  ASCENDING.


    SELECT * FROM AUFK
      INTO TABLE @DATA(LT_AUFK)
      FOR ALL ENTRIES IN @LT_VIQMEL
      WHERE AUFNR = @LT_VIQMEL-AUFNR.
    "break-POINT.
    IF LT_AUFK IS NOT INITIAL.
      SELECT * FROM JCDS
      INTO TABLE @DATA(LT_JCDS_ORDER)
            FOR ALL ENTRIES IN @LT_VIQMEL
            WHERE OBJNR = @LT_VIQMEL-OBJNR
            AND STAT = 'I0045'
            AND INACT <> 'X'.
*Receiving Facility Representative
      SELECT * FROM JCDS
            INTO TABLE @DATA(LT_JCDS_ORDER_REC_FAC)
                  FOR ALL ENTRIES IN @LT_AUFK
                  WHERE OBJNR = @LT_AUFK-OBJNR
                   AND STAT = 'E0003'
                  AND INACT <> 'X'.
      SORT LT_JCDS_ORDER_REC_FAC BY UDATE UTIME  DESCENDING.
      DELETE ADJACENT DUPLICATES FROM LT_JCDS_ORDER_REC_FAC COMPARING OBJNR UDATE.



    ENDIF.
  ENDIF.



**  IF LT_AUFK IS NOT INITIAL.
**    SELECT * FROM AFIH
**      INTO TABLE @DATA(LT_AFIH)
**      FOR ALL ENTRIES IN @LT_AUFK
**      WHERE AUFNR = @LT_AUFK-AUFNR.
**
***Get User Status
**    SELECT * FROM JCDS
**      INTO TABLE @DATA(LT_JCDS)
**      FOR ALL ENTRIES IN @LT_AUFK
**      WHERE OBJNR = @LT_AUFK-OBJNR.
**
**    SORT LT_JCDS BY OBJNR ASCENDING.
**
**    SELECT * FROM EQUZ
**      INTO TABLE @DATA(LT_EQUZ)
**      FOR ALL ENTRIES IN @LT_AFIH
**      WHERE EQUNR = @LT_AFIH-EQUNR.
**
**    SORT LT_EQUZ BY HEQUI ASCENDING.
**
**  ENDIF.
**  SORT LT_AFIH BY AUFNR ASCENDING.
**
***For Rev Text
**  IF LT_AFIH IS NOT INITIAL.
**    SELECT * FROM T352R
**      INTO TABLE @DATA(LT_T352R)
**      FOR ALL ENTRIES IN @LT_AFIH
**      WHERE IWERK = @LT_AFIH-IWERK
**      AND REVNR = @LT_AFIH-REVNR.
**
**    SORT LT_T352R BY IWERK REVNR ASCENDING.
***For Plaining Planr and descprition
**
**    SELECT * FROM T024I
**      INTO TABLE @DATA(LT_T024I)
**      FOR ALL ENTRIES IN @LT_AFIH
**      WHERE IWERK = @LT_AFIH-IWERK
**      AND INGRP = @LT_AFIH-INGPR.
**  ENDIF.
**
**  SORT LT_T024I BY IWERK INGRP ASCENDING.
**
**
**  SELECT * FROM TJ02T
**    INTO TABLE @DATA(LT_TJ02T)
**    WHERE SPRAS = @SY-LANGU.
**
**  SORT LT_TJ02T BY ISTAT ASCENDING.

*  "break-POINT.
  LOOP AT LT_VIQMEL INTO DATA(LS_VIQMEL).
    "break ac_Adnan.
    CALL FUNCTION 'BAPI_ALM_NOTIF_GET_DETAIL'
      EXPORTING
        NUMBER             = LS_VIQMEL-QMNUM
        CLEAR_BUFFER       = 'X'
      IMPORTING
        NOTIFHEADER_EXPORT = NOTIFHEADER_EXPORT
        NOTIFHDTEXT        = NOTIFHDTEXT
        MAINTACTYTYPE      = MAINTACTYTYPE
      TABLES
        NOTLONGTXT         = NOTLONGTXT
        NOTITEM            = NOTITEM
        NOTIFCAUS          = NOTIFCAUS
        NOTIFACTV          = NOTIFACTV
        NOTIFTASK          = NOTIFTASK
        NOTIFPARTNR        = NOTIFPARTNR
        RETURN             = RETURN
        EXTENSIONOUT       = EXTENSIONOUT.



    MOVE-CORRESPONDING NOTIFHEADER_EXPORT TO GS_MAIN.


    GS_MAIN-STRMLFNDATE =  NOTIFHEADER_EXPORT-DESSTDATE.
    GS_MAIN-ENDMLFNDATE =    NOTIFHEADER_EXPORT-DESENDDATE.
    MOVE NOTIFHEADER_EXPORT-SORTFIELD TO GS_MAIN-FROM_ZONE.
    MOVE NOTIFHDTEXT-EQUIDESCR TO GS_MAIN-EQUIDESCR.

****    DATA:LT_SPLIT TYPE STRING.
****    SPLIT NOTIFHEADER_EXPORT-FUNCT_LOC AT '-' INTO LT_SPLIT.

    ""break-POINT.
    DATA: TEXT_TAB TYPE TABLE OF STRING.
    DATA: LV_TEXT TYPE STRING.
    CLEAR LV_ZONE.
    IF NOTIFHEADER_EXPORT-FUNCT_LOC IS NOT INITIAL.
      SPLIT NOTIFHEADER_EXPORT-FUNCT_LOC AT '-' INTO TABLE TEXT_TAB.
      DELETE  TEXT_TAB FROM 4 TO 99999.
      LV_ZONE  =  REDUCE #( INIT TEXT = `` FOR <LINE1> IN TEXT_TAB
                      NEXT  TEXT = TEXT && '-' &&  <LINE1>  ).
      SHIFT LV_ZONE LEFT DELETING LEADING  '-'.

      FUNCTLOCATION = LV_ZONE.

      CALL FUNCTION 'BAPI_FUNCLOC_GETDETAIL'
        EXPORTING
          FUNCTLOCATION             = FUNCTLOCATION
          REQUEST_INSTALLATION_DATA = 'X'
        IMPORTING
          DATA_GENERAL_EXP          = DATA_GENERAL_EXP
          DATA_SPECIFIC_EXP         = DATA_SPECIFIC_EXP
          RETURN                    = RETURN_ZONE
          DATA_INSTALLATION         = DATA_INSTALLATION
        TABLES
          EXTENSIONOUT              = EXTENSIONOUT_ZONE.
      GS_MAIN-FROM_ZONE = DATA_INSTALLATION-FUNCLOCSTRUCIDENTIFYINGOBJDESC.
    ENDIF.
    FREE TEXT_TAB.
    FREE LV_ZONE.
    IF LS_VIQMEL-ZQMTXT  IS NOT INITIAL.
      SPLIT LS_VIQMEL-ZQMTXT AT '-' INTO TABLE TEXT_TAB.
      DELETE  TEXT_TAB FROM 4 TO 99999.
      LV_ZONE  =  REDUCE #( INIT TEXT = `` FOR <LINE1> IN TEXT_TAB
                      NEXT  TEXT = TEXT && '-' &&  <LINE1>  ).
      SHIFT LV_ZONE LEFT DELETING LEADING  '-'.

      FUNCTLOCATION = LV_ZONE.
      CALL FUNCTION 'BAPI_FUNCLOC_GETDETAIL'
        EXPORTING
          FUNCTLOCATION             = FUNCTLOCATION
          REQUEST_INSTALLATION_DATA = 'X'
        IMPORTING
          DATA_GENERAL_EXP          = DATA_GENERAL_EXP
          DATA_SPECIFIC_EXP         = DATA_SPECIFIC_EXP
          RETURN                    = RETURN_ZONE
          DATA_INSTALLATION         = DATA_INSTALLATION
        TABLES
          EXTENSIONOUT              = EXTENSIONOUT_ZONE.
      GS_MAIN-TO_ZONE = DATA_INSTALLATION-FUNCLOCSTRUCIDENTIFYINGOBJDESC.
    ENDIF.

*    DATA(LV_LINES) = REDUCE I( INIT X = 0 FOR WA IN TEXT_TAB
*                  WHERE ( X = 3 )      NEXT X = X + 1 ).

*READ ASSET TAG (TECHNICAL IDN)
    GS_MAIN-ASSIT_TAG = VALUE #( LT_EQUZ[ EQUNR = NOTIFHEADER_EXPORT-EQUIPMENT ]-TIDNR OPTIONAL ).
    IF NOTIFHEADER_EXPORT-ENDMLFNDATE IS NOT INITIAL AND NOTIFHEADER_EXPORT-STRMLFNDATE IS NOT INITIAL.
      DATA:YEARS  TYPE  PEA_SCRYY,
           MONTHS TYPE  PEA_SCRMM,
           DAYS   TYPE  PEA_SCRDD.
      CALL FUNCTION 'HR_HK_DIFF_BT_2_DATES'
        EXPORTING
          DATE1         = NOTIFHEADER_EXPORT-ENDMLFNDATE
          DATE2         = NOTIFHEADER_EXPORT-STRMLFNDATE
          OUTPUT_FORMAT = '05'
        IMPORTING
          YEARS         = YEARS
          MONTHS        = MONTHS
          DAYS          = DAYS.


      GS_MAIN-DURATION =  MONTHS .
    ENDIF.
    DATA OBTYP       TYPE JSTO-OBTYP.
    DATA STSMA       TYPE JSTO-STSMA.
    DATA STONR       TYPE TJ30-STONR.
    DATA GT_STATUS      TYPE STANDARD TABLE OF JSTAT.

*For Status Text and code
    CALL FUNCTION 'STATUS_READ'
      EXPORTING
        CLIENT           = SY-MANDT
        OBJNR            = NOTIFHEADER_EXPORT-OBJECT_NO
        ONLY_ACTIVE      = 'X'
      IMPORTING
        OBTYP            = OBTYP
        STSMA            = STSMA
        STONR            = STONR
      TABLES
        STATUS           = GT_STATUS
      EXCEPTIONS
        OBJECT_NOT_FOUND = 1.

    SORT GT_STATUS BY STAT  DESCENDING.
    "break-POINT.
    DELETE GT_STATUS WHERE STAT+0(1) = 'E'.

    LOOP AT GT_STATUS INTO DATA(GS_STATUS) WHERE STAT = 'I0070' OR STAT = 'I0072' OR STAT = 'I0068' .
      READ TABLE LT_TJ02T INTO DATA(LS_TJ02T) WITH KEY ISTAT = GS_STATUS-STAT BINARY SEARCH.
      IF SY-SUBRC = 0.
        IF GS_MAIN-STAT IS  INITIAL .
          GS_MAIN-STAT = LS_TJ02T-TXT30.
        ENDIF.
      ENDIF.
    ENDLOOP.

*For Consession Type and To Zone
    READ TABLE LT_IFLO INTO DATA(LS_IFLO) WITH KEY TPLNR = LS_VIQMEL-ZQMTXT+0(30) BINARY SEARCH.
    IF SY-SUBRC = 0.
      "   MOVE LS_IFLO-EQFNR TO GS_MAIN-TO_ZONE.
      CLEAR GS_MAIN-MOV_LOC .
      IF LS_VIQMEL-ZQMTXT  IS NOT INITIAL.
        SPLIT LS_VIQMEL-ZQMTXT AT '-' INTO TABLE TEXT_TAB.
        DELETE  TEXT_TAB FROM 5 TO 99999.
        LV_ZONE  =  REDUCE #( INIT TEXT = `` FOR <LINE1> IN TEXT_TAB
                        NEXT  TEXT = TEXT && '-' &&  <LINE1>  ).
        SHIFT LV_ZONE LEFT DELETING LEADING  '-'.

        FUNCTLOCATION = LV_ZONE.
        CALL FUNCTION 'BAPI_FUNCLOC_GETDETAIL'
          EXPORTING
            FUNCTLOCATION             = FUNCTLOCATION
            REQUEST_INSTALLATION_DATA = 'X'
          IMPORTING
            DATA_GENERAL_EXP          = DATA_GENERAL_EXP
            DATA_SPECIFIC_EXP         = DATA_SPECIFIC_EXP
            RETURN                    = RETURN_ZONE
            DATA_INSTALLATION         = DATA_INSTALLATION
          TABLES
            EXTENSIONOUT              = EXTENSIONOUT_ZONE.
        GS_MAIN-MOV_LOC = DATA_INSTALLATION-FUNCLOCSTRUCIDENTIFYINGOBJDES2.
      ENDIF.
      "GS_MAIN-MOV_LOC = VALUE #( LT_T001W[ WERKS = LS_IFLO-IWERK ]-NAME1 OPTIONAL ).
      IF NOTIFHEADER_EXPORT-MAINTPLANT <> LS_IFLO-SWERK.
        GS_MAIN-CONCESSION = 'INTRA CONCESSION'.
      ELSE.
        GS_MAIN-CONCESSION = 'INTER CONCESSION'.
      ENDIF.
    ENDIF.

*For From Zone
    READ TABLE LT_IFLO INTO LS_IFLO WITH KEY TPLNR = LS_VIQMEL-TPLNR BINARY SEARCH.
    IF SY-SUBRC = 0.
      "  MOVE LS_IFLO-EQFNR TO GS_MAIN-FROM_ZONE.
      CLEAR GS_MAIN-CURR_LOC .
      FREE TEXT_TAB.
      FREE LV_ZONE.
      IF LS_VIQMEL-TPLNR  IS NOT INITIAL.
        SPLIT LS_VIQMEL-TPLNR AT '-' INTO TABLE TEXT_TAB.
        DELETE  TEXT_TAB FROM 5 TO 99999.
        LV_ZONE  =  REDUCE #( INIT TEXT = `` FOR <LINE1> IN TEXT_TAB
                        NEXT  TEXT = TEXT && '-' &&  <LINE1>  ).
        SHIFT LV_ZONE LEFT DELETING LEADING  '-'.

        FUNCTLOCATION = LV_ZONE.
        CALL FUNCTION 'BAPI_FUNCLOC_GETDETAIL'
          EXPORTING
            FUNCTLOCATION             = FUNCTLOCATION
            REQUEST_INSTALLATION_DATA = 'X'
          IMPORTING
            DATA_GENERAL_EXP          = DATA_GENERAL_EXP
            DATA_SPECIFIC_EXP         = DATA_SPECIFIC_EXP
            RETURN                    = RETURN_ZONE
            DATA_INSTALLATION         = DATA_INSTALLATION
          TABLES
            EXTENSIONOUT              = EXTENSIONOUT_ZONE.
        GS_MAIN-CURR_LOC = DATA_INSTALLATION-FUNCLOCSTRUCIDENTIFYINGOBJDES2.
      ENDIF.
      "  GS_MAIN-CURR_LOC = VALUE #( LT_T001W[ WERKS = LS_IFLO-IWERK ]-NAME1 OPTIONAL ).
    ENDIF.

*Read Movement Type Desc
    READ TABLE LT_T353I_T INTO DATA(LS_T353I_T) WITH KEY ILART = LS_VIQMEL-ILART BINARY SEARCH.
    IF SY-SUBRC = 0.
      MOVE LS_T353I_T-ILATX TO GS_MAIN-ILATX.
    ENDIF.

*Read Asset Condition
    READ TABLE LT_QPCT INTO DATA(LS_QPCT) WITH KEY KATALOGART = LS_VIQMEL-QMKAT
    CODEGRUPPE = LS_VIQMEL-QMGRP
    CODE = LS_VIQMEL-QMCOD
    BINARY SEARCH.
    IF SY-SUBRC = 0.
      MOVE LS_QPCT-KURZTEXT TO GS_MAIN-KURZTEXT.
    ENDIF.

*Movement Reason
    READ TABLE LT_T352R INTO DATA(LS_T352R) WITH KEY REVNR = LS_VIQMEL-REVNR
    IWERK = LS_VIQMEL-IWERK
    BINARY SEARCH.
    IF SY-SUBRC = 0.
      MOVE LS_T352R-REVTX TO GS_MAIN-MOVE_RES.
    ENDIF.

*Proposed By
    READ TABLE LT_USER_ADDR INTO DATA(LS_USER_ADDR) WITH KEY BNAME = LS_VIQMEL-QMNAM BINARY SEARCH.
    IF SY-SUBRC = 0.
      MOVE LS_USER_ADDR-NAME_TEXTC TO GS_MAIN-PROPOSED_BY.
    ENDIF.


*For Reviewed By:Approved By:Authorized By:
    FIELD-SYMBOLS:<FS> TYPE ANY.
    DATA:LV_FIELD TYPE STRING.
    ""break-POINT.

*Transferring Facility Representative:
    LOOP AT LT_JCDS INTO DATA(LS_JCDS)
      WHERE OBJNR = LS_VIQMEL-OBJNR.
      CLEAR LS_TJ02T.
      READ TABLE LT_TJ30T INTO DATA(LS_TJ30T) WITH KEY ESTAT = LS_JCDS-STAT." BINARY SEARCH.
      IF SY-SUBRC = 0.
        IF LS_TJ30T-TXT04 = 'RVWD'.
          LV_FIELD = 'GS_MAIN-REVIEWED_BY'.
        ELSEIF LS_TJ30T-TXT04 = 'APPR'.
          LV_FIELD = 'GS_MAIN-APPROVED_BY'.
        ELSEIF LS_TJ30T-TXT04 = 'CNRD'.
          LV_FIELD = 'GS_MAIN-TRANSFERRING_FACI'.
          GS_MAIN-TRANSFERRING_FACI_DATE = LS_JCDS-UDATE.
        ELSEIF LS_TJ30T-TXT04 = 'EXEC'.
          LV_FIELD = 'GS_MAIN-RECEIVING_FAC'.
          GS_MAIN-RECEIVING_FAC_DATE = LS_JCDS-UDATE.
        ELSEIF LS_TJ30T-TXT04 = 'ATHZ'.
          LV_FIELD = 'GS_MAIN-AUTHORIZED_BY'.

        ENDIF.

        ASSIGN (LV_FIELD) TO <FS>.
        IF <FS> IS ASSIGNED.
          READ TABLE LT_USER_ADDR INTO DATA(LS_USER_ADDR_FS) WITH KEY BNAME = LS_JCDS-USNAM BINARY SEARCH.
          IF SY-SUBRC = 0.
            MOVE LS_USER_ADDR_FS-NAME_TEXTC TO <FS>.
          ENDIF.
        ENDIF.
        CLEAR LV_FIELD.
      ENDIF.
    ENDLOOP.

*RReceiving Facility Representative:
    READ TABLE LT_AUFK INTO DATA(LS_AUFK) WITH KEY AUFNR = LS_VIQMEL-AUFNR.
    LOOP AT LT_JCDS_ORDER_REC_FAC INTO DATA(LS_JCDS_REC)
      WHERE OBJNR = LS_AUFK-OBJNR AND STAT = 'E0003'.
      CLEAR LS_TJ02T.
      LV_FIELD = 'GS_MAIN-RECEIVING_FAC'.
      GS_MAIN-RECEIVING_FAC_DATE = LS_JCDS-UDATE.

      ASSIGN (LV_FIELD) TO <FS>.
      IF <FS> IS ASSIGNED.
        READ TABLE LT_USER_ADDR INTO DATA(LS_USER_ADDR_FS_AUFK) WITH KEY BNAME = LS_JCDS_REC-USNAM BINARY SEARCH.
        IF SY-SUBRC = 0.
          MOVE LS_USER_ADDR_FS_AUFK-NAME_TEXTC TO <FS>.
        ENDIF.
      ENDIF.
      CLEAR LV_FIELD.
    ENDLOOP.

*For rority
    IF LS_VIQMEL-PRIOK = '1'.
      GS_MAIN-PRIOK = 'Urgent-(7 Days)'.
    ELSEIF LS_VIQMEL-PRIOK = '2'.
      GS_MAIN-PRIOK = 'Planned-(30 Days)'.
    ENDIF.

*For Pernr
*    "break-POINT.
    IF LS_VIQMEL-AUFNR IS NOT INITIAL.
      DATA: IAFVGD  TYPE STANDARD TABLE OF AFVGD,
            WCAUFVD LIKE  CAUFVD.
      CALL FUNCTION 'PM_ORDER_DATA_READ'
        EXPORTING
          ORDER_NUMBER    = LS_VIQMEL-AUFNR
*         CALL_FROM_NOTIF = 'X'
        IMPORTING
          WCAUFVD         = WCAUFVD
        TABLES
          IAFVGD          = IAFVGD
        EXCEPTIONS
          ORDER_NOT_FOUND = 1.
      DATA P_PERNR     TYPE PRELP-PERNR.
      CLEAR P_PERNR.
      GS_MAIN-IDAT2 = WCAUFVD-IDAT2.
      P_PERNR = VALUE #( IAFVGD[ VORNR = '0010' ]-PERNR OPTIONAL ).

*For Emp Name

*DATA P_DATE      TYPE D.
      DATA P_EMPLOYEE  TYPE PFRL0_EMPLOYEE.
      DATA P_TAB_ERROR TYPE P99SF_TAB_ERROR.
*DATA T0001       TYPE STANDARD TABLE OF P0001.
*DATA T0002       TYPE STANDARD TABLE OF P0002.
*DATA T0006       TYPE STANDARD TABLE OF P0006.
*DATA T0064       TYPE STANDARD TABLE OF P0064.
*DATA T0217       TYPE STANDARD TABLE OF P0217.

      IF P_PERNR IS NOT INITIAL.
        CALL FUNCTION 'HR_FR_GET_EMPLOYEE'
          EXPORTING
            P_PERNR     = P_PERNR
            P_DATE      = '99991231'
          IMPORTING
            P_EMPLOYEE  = P_EMPLOYEE
            P_TAB_ERROR = P_TAB_ERROR
*          TABLES
*           T0001       = T0001
*           T0002       = T0002
*           T0006       = T0006
*           T0064       = T0064
*           T0217       = T0217
          EXCEPTIONS
            ERROR       = 1.

        IF P_EMPLOYEE-SNAME IS NOT INITIAL.
          GS_MAIN-PERNR = P_EMPLOYEE-PERNR.
          GS_MAIN-NAME = P_EMPLOYEE-SNAME.
        ENDIF.
      ENDIF.
    ENDIF.

***    WHERE KATALOGART = @LT_VIQMEL-QMKAT
***     AND  CODEGRUPPE = @LT_VIQMEL-QMGRP
***     AND  CODE = @LT_VIQMEL-QMCOD
***      AND SPRACHE = @SY-LANGU.

    DELETE NOTLONGTXT INDEX 1.
    GS_MAIN-TDLINE = REDUCE STRING( INIT LV_WHERE_CLAUSE TYPE STRING
                               FOR LS_WERKS  IN NOTLONGTXT
                               NEXT LV_WHERE_CLAUSE = LV_WHERE_CLAUSE && LS_WERKS-TEXT_LINE ).


    APPEND GS_MAIN TO GT_MAIN.
    FREE:GS_MAIN.

  ENDLOOP.


ENDFORM.

*&---------------------------------------------------------------------*
*& Include          ZFI_VOID_CHECK_REGISTER_F01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  SET_OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

FORM SET_OUTPUT .

  DATA: FM_NAME         TYPE RS38L_FNAM,
        FP_DOCPARAMS    TYPE SFPDOCPARAMS,
        FP_OUTPUTPARAMS TYPE SFPOUTPUTPARAMS.



  CALL FUNCTION 'FP_JOB_OPEN'
    CHANGING
      IE_OUTPUTPARAMS = FP_OUTPUTPARAMS
    EXCEPTIONS
      CANCEL          = 1
      USAGE_ERROR     = 2
      SYSTEM_ERROR    = 3
      INTERNAL_ERROR  = 4
      OTHERS          = 5.

  IF SY-SUBRC <> 0.
    " MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CALL FUNCTION 'FP_FUNCTION_MODULE_NAME'           "& Form Processing Generation
    EXPORTING
      I_NAME     = 'ZPM_EQUIPMENT_TRANSFER_FORM'
    IMPORTING
      E_FUNCNAME = FM_NAME.

  CALL FUNCTION FM_NAME
    EXPORTING
      /1BCDWB/DOCPARAMS = FP_DOCPARAMS
*     REPORT_DATE       = REPORT_DATE
*     PERIOD_FROM       = PERIOD_FROM
*     PERIOD_TO         = PERIOD_TO
*     BANKA             = BANKA
*     BANKN             = BANKN
*     BRNCH             = BRNCH
*     WAERS             = WAERS
*     TOTAL             = TOTAL
      GT_MAIN           = GT_MAIN
*    IMPORTING
*     /1BCDWB/FORMOUTPUT       =
    EXCEPTIONS
      USAGE_ERROR       = 1
      SYSTEM_ERROR      = 2
      INTERNAL_ERROR    = 3.

  IF SY-SUBRC <> 0.
    "MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CALL FUNCTION 'FP_JOB_CLOSE'
*    IMPORTING
*     E_RESULT             =
    EXCEPTIONS
      USAGE_ERROR    = 1
      SYSTEM_ERROR   = 2
      INTERNAL_ERROR = 3
      OTHERS         = 4.

  IF SY-SUBRC <> 0.
    " MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.
