*&---------------------------------------------------------------------*
*& Include          ZPM_EMAIL_INTIMATION_RPT_F01
*&---------------------------------------------------------------------*
FORM GET_DATA.
  CLEAR LV_CHK_DATA.
  BREAK AC_ADNAN..
*  SY-DATUM = SY-DATUM - 1.
  SELECT SINGLE
  OBJECT,
  EXTNUMBER,
  ALDATE,
  PROBCLASS,
  ALPROG,
  ALTCODE
  INTO  @DATA(LT_DATA)
        FROM BALHDR
        WHERE ALDATE = @SY-DATUM
*        WHERE ALDATE = @SY-DATUM
        AND ( ALTCODE EQ  'IP30'  OR   ALPROG = 'RISTRA20' ).
  IF LT_DATA IS NOT INITIAL.
    DATA(LV_DATE) = SY-DATUM .

    DATA MESSAGES           TYPE STANDARD TABLE OF BALM..

    CALL FUNCTION 'APPL_LOG_READ_DB'
      EXPORTING
        OBJECT           = LT_DATA-OBJECT
        SUBOBJECT        = '*'
        EXTERNAL_NUMBER  = LT_DATA-EXTNUMBER
        DATE_FROM        = LT_DATA-ALDATE
        DATE_TO          = LT_DATA-ALDATE
        TIME_FROM        = '000000'
        TIME_TO          = '000000'
        LOG_CLASS        = LT_DATA-PROBCLASS
        PROGRAM_NAME     = LT_DATA-ALPROG
        TRANSACTION_CODE = LT_DATA-ALTCODE
        USER_ID          = ' '
        MODE             = '+'
        PUT_INTO_MEMORY  = ' '
      TABLES
        MESSAGES         = MESSAGES.

    LT_TEMP_MESSAGES = MESSAGES.

    RANGES: MSGID FOR BALM-MSGID.
    MSGID-SIGN = 'I'.
    MSGID-OPTION = 'EQ'.
    MSGID-HIGH = 'IM'.
    MSGID-LOW = 'IM'.
    APPEND MSGID.

    MSGID-SIGN = 'I'.
    MSGID-OPTION = 'EQ'.
    MSGID-HIGH = 'IW'.
    MSGID-LOW = 'IW'.
    APPEND MSGID.

    DELETE LT_TEMP_MESSAGES WHERE MSGID NOT IN MSGID.
    DELETE MESSAGES WHERE MSGTY NE 'A'.


    DELETE LT_TEMP_MESSAGES WHERE MSGV1 IS INITIAL AND MSGV2 IS INITIAL.


*BOC by adnan khan to remove duplication notification based on order notification and fill ranges of Notifcation and Order
    DATA   R_NOTI   TYPE RANGE OF BALM-MSGV2.
    R_NOTI = VALUE #( FOR LS_NOTI IN LT_TEMP_MESSAGES
                  ( SIGN = 'I'
                    OPTION = 'EQ'
                    LOW = LS_NOTI-MSGV2 )
                  ).
    DELETE LT_TEMP_MESSAGES WHERE MSGV1 IN R_NOTI.

    DATA   R_AUFNR   TYPE RANGE OF BALM-MSGV1.
    R_AUFNR = VALUE #( FOR LS_NOTI IN LT_TEMP_MESSAGES
                  ( SIGN = 'I'
                    OPTION = 'CP'
                    LOW = '*' && LS_NOTI-MSGV1 && '*' )
                  ).


*EOC by adnan khan to remove duplication notification based on order notification


    BREAK AC_ADNAN.
    IF LT_TEMP_MESSAGES IS NOT INITIAL.

      SELECT * FROM VIAUFKST
        INTO TABLE @DATA(LT_VIAUFKST)
              WHERE AUFNR  IN @R_AUFNR .

      SELECT * FROM VIAUFKST
             APPENDING CORRESPONDING FIELDS OF TABLE @LT_VIAUFKST
                   WHERE  QMNUM IN @R_NOTI.
      .

      SELECT  *  FROM EQUZ
      INTO TABLE @DATA(LT_EQUZ)
            FOR ALL ENTRIES IN @LT_VIAUFKST
            WHERE EQUNR  EQ @LT_VIAUFKST-EQUNR.
      DELETE LT_EQUZ WHERE TIDNR EQ ' '.
    ENDIF.



    LOOP AT LT_TEMP_MESSAGES INTO DATA(LS_MESSAGES) .
      CLEAR  LV_CHK_DATA_DOC.
      LV_CHK_DATA = 'X'.
      IF LS_MESSAGES-MSGID EQ 'IM' .
        GS_MAIN-QMNUM = LS_MESSAGES-MSGV1.
        UNPACK GS_MAIN-QMNUM TO GS_MAIN-QMNUM.

        READ TABLE LT_VIAUFKST INTO DATA(LS_VIAUFKST_NOTIFICATIONS) WITH KEY QMNUM  = GS_MAIN-QMNUM. "LS_MESSAGES-MSGV1.
        IF SY-SUBRC = 0.
          LV_CHK_DATA_DOC = 'X'.
          GS_MAIN-GLTRP = LS_VIAUFKST_NOTIFICATIONS-GLTRP.
          GS_MAIN-IWERK = LS_VIAUFKST_NOTIFICATIONS-IWERK.
          GS_MAIN-WORK_CENTER = LS_VIAUFKST_NOTIFICATIONS-VAPLZ.
          GS_MAIN-PM_NO = LS_VIAUFKST_NOTIFICATIONS-WARPL.
          LV_CHK        = LS_VIAUFKST_NOTIFICATIONS-EQUNR.
          READ TABLE LT_EQUZ INTO DATA(LS_EQUZ_NOTIFICATION) WITH KEY EQUNR  = LV_CHK. "LS_MESSAGES-MSGV1.
          IF SY-SUBRC = 0.
            GS_MAIN-TECHNICAL_ID = LS_EQUZ_NOTIFICATION-TIDNR.
          ENDIF.
          CLEAR LV_CHK.
        ENDIF.
      ELSEIF LS_MESSAGES-MSGID EQ 'IW'." AND LS_MESSAGES-MSGV2 is NOT INITIAL.
        GS_MAIN-AUFNR = LS_MESSAGES-MSGV1.
        GS_MAIN-QMNUM = LS_MESSAGES-MSGV2.
        UNPACK GS_MAIN-AUFNR TO GS_MAIN-AUFNR.
        READ TABLE LT_VIAUFKST INTO DATA(LS_VIAUFKST_ORDER) WITH KEY AUFNR  = GS_MAIN-AUFNR.
        IF SY-SUBRC = 0.
          LV_CHK_DATA_DOC = 'X'.
          GS_MAIN-GLTRP = LS_VIAUFKST_ORDER-GLTRP.
          GS_MAIN-IWERK = LS_VIAUFKST_ORDER-IWERK.
          GS_MAIN-WORK_CENTER = LS_VIAUFKST_ORDER-VAPLZ.
          GS_MAIN-PM_NO = LS_VIAUFKST_ORDER-WARPL.
          LV_CHK        = LS_VIAUFKST_ORDER-EQUNR.
          READ TABLE LT_EQUZ INTO DATA(LS_EQUZ_ORDER) WITH KEY EQUNR  = LV_CHK. "LS_MESSAGES-MSGV1.
          IF SY-SUBRC = 0.
            GS_MAIN-TECHNICAL_ID = LS_EQUZ_ORDER-TIDNR.
          ENDIF.
          CLEAR LV_CHK.
        ENDIF.

      ENDIF.
      SHIFT GS_MAIN-PM_NO LEFT DELETING LEADING '0'.
      IF LV_CHK_DATA_DOC  = 'X'.
        APPEND GS_MAIN TO GT_MAIN.
      ENDIF.
      CLEAR GS_MAIN.

    ENDLOOP.
    LOOP AT MESSAGES INTO DATA(LS_MESSAGES_ERROR).

      DATA E_MESSAGE_TEXT(100) TYPE C.

      CALL FUNCTION 'BAL_DSP_TXT_MSG_READ'
        EXPORTING
          I_LANGU        = SY-LANGU
          I_MSGID        = LS_MESSAGES_ERROR-MSGID
          I_MSGNO        = LS_MESSAGES_ERROR-MSGNO
          I_MSGV1        = LS_MESSAGES_ERROR-MSGV1
          I_MSGV2        = LS_MESSAGES_ERROR-MSGV2
          I_MSGV3        = LS_MESSAGES_ERROR-MSGV3
          I_MSGV4        = LS_MESSAGES_ERROR-MSGV4
        IMPORTING
          E_MESSAGE_TEXT = E_MESSAGE_TEXT.
      MOVE E_MESSAGE_TEXT TO GS_MAIN-ERROR.
      APPEND GS_MAIN TO GT_MAIN.
    ENDLOOP.
  ENDIF.

  DELETE GT_MAIN WHERE AUFNR IS INITIAL AND QMNUM IS INITIAL AND ERROR IS INITIAL.



ENDFORM.
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  SET_OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

FORM SET_OUTPUT .

  DATA:ODATA TYPE REF TO ZCL_SEND_OO_EMAIL.
  CREATE OBJECT ODATA.

  DATA: LO_DATA_REF TYPE REF TO	DATA,
        LT_BODY     TYPE BCSY_TEXT,
        EMAIL       TYPE  CHAR50,
        NAME        TYPE  SO_OBJ_DES.


  GET REFERENCE OF GT_MAIN INTO LO_DATA_REF.


  LT_BODY = VALUE BCSY_TEXT(
                    ( LINE = 'Dear Recipient,' ) ( )
                    ( LINE = 'Attached file is IP30 Log' ) ( )
                    ( LINE = 'Thank You' )
                  ).
  DATA:FCAT        TYPE  LVC_T_FCAT,
       LS_FIELDCAT LIKE LINE OF FCAT.
  CLEAR FCAT.
  CREATE DATA LR_DATA LIKE LINE OF GT_MAIN.
*Create Field Cathlog From Internal Table
  LR_TABDESCR ?= CL_ABAP_STRUCTDESCR=>DESCRIBE_BY_DATA_REF( LR_DATA ).
  LT_DFIES = CL_SALV_DATA_DESCR=>READ_STRUCTDESCR( LR_TABDESCR ).

  LOOP AT LT_DFIES INTO LS_DFIES.
    CLEAR LS_FIELDCAT.
    MOVE-CORRESPONDING LS_DFIES TO LS_FIELDCAT.
    LS_FIELDCAT-REPTEXT   = LS_DFIES-FIELDTEXT.
    LS_FIELDCAT-SCRTEXT_S = LS_DFIES-FIELDTEXT.
    LS_FIELDCAT-SCRTEXT_L = LS_DFIES-FIELDTEXT.
    LS_FIELDCAT-SCRTEXT_M = LS_DFIES-FIELDTEXT.
    APPEND LS_FIELDCAT TO FCAT.
    CLEAR: LS_FIELDCAT,LS_DFIES.
  ENDLOOP.

  SELECT * FROM ZPM_EMAIL INTO TABLE @DATA(LT_EMAIL).

  LOOP AT LT_EMAIL INTO DATA(LS_EMAIL).

    EMAIL = LS_EMAIL-EMAIL.
    ODATA->SEND_EMAIL(
      LO_DATA_REF = LO_DATA_REF
      LT_BODY     = LT_BODY
      EMAIL       = EMAIL
      NAME        = 'IP30_LOG'
      FCAT        = FCAT
      SUBJECT     = 'IP30 Creation Log'
    ).

  ENDLOOP..


ENDFORM.

FORM SET_EMAIL."  USING    P_DATA  LIKE LINE OF GT_MAIN.
*  FREE GT_MAIN.
*  MOVE-CORRESPONDING P_DATA TO GS_MAIN.
*  APPEND GS_MAIN TO GT_MAIN.
*  CLEAR GS_MAIN.

  DATA: FM_NAME         TYPE RS38L_FNAM,
        FP_DOCPARAMS    TYPE SFPDOCPARAMS,
        FP_OUTPUTPARAMS TYPE SFPOUTPUTPARAMS.


  FP_OUTPUTPARAMS-NODIALOG = ABAP_TRUE.
  FP_OUTPUTPARAMS-NOPREVIEW = ABAP_TRUE.
  FP_OUTPUTPARAMS-DEST     = 'LP01'.
  FP_OUTPUTPARAMS-CONNECTION = 'ADS'.
  FP_OUTPUTPARAMS-GETPDF = 'X'.

  CALL FUNCTION 'FP_JOB_OPEN'
    CHANGING
      IE_OUTPUTPARAMS = FP_OUTPUTPARAMS
    EXCEPTIONS
      CANCEL          = 1
      USAGE_ERROR     = 2
      SYSTEM_ERROR    = 3
      INTERNAL_ERROR  = 4
      OTHERS          = 5.

  IF SY-SUBRC <> 0.
    " MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
  DATA:LV_FNAME TYPE FPNAME.
  CLEAR LV_FNAME.

  LV_FNAME = 'ZPM_EMAIL_INTIMATION_FORM'.


  CALL FUNCTION 'FP_FUNCTION_MODULE_NAME'           "& Form Processing Generation
    EXPORTING
      I_NAME     = LV_FNAME
    IMPORTING
      E_FUNCNAME = FM_NAME.

  CALL FUNCTION FM_NAME
    EXPORTING
      /1BCDWB/DOCPARAMS  = FP_DOCPARAMS
      GT_MAIN            = GT_MAIN
    IMPORTING
      /1BCDWB/FORMOUTPUT = W_OTF
    EXCEPTIONS
      USAGE_ERROR        = 1
      SYSTEM_ERROR       = 2
      INTERNAL_ERROR     = 3.

  IF SY-SUBRC <> 0.
    "MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
*Send Email


  SELECT * FROM ZPM_EMAIL INTO TABLE @DATA(LT_EMAIL).

  LOOP AT LT_EMAIL INTO DATA(LS_EMAIL) WHERE EMAIL NE ''.
    PERFORM F_SEND_MAIL USING LS_EMAIL-EMAIL.
  ENDLOOP.
*  IF LV_USRID IS NOT INITIAL.
*    PERFORM F_SEND_MAIL USING LV_USRID.
*  ENDIF.
  CLEAR W_OTF.
  CALL FUNCTION 'FP_JOB_CLOSE'
*    IMPORTING
*     E_RESULT             =
    EXCEPTIONS
      USAGE_ERROR    = 1
      SYSTEM_ERROR   = 2
      INTERNAL_ERROR = 3
      OTHERS         = 4.

  IF SY-SUBRC <> 0.
    " MESSAGE 'Abode Form Server Error' TYPE 'E'.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
                            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.

FORM F_SEND_MAIL USING P_USRID TYPE PA0105-USRID_LONG .
  BREAK-POINT.
  DATA: LV_ADRNR   TYPE KNA1-ADRNR,
        LV_NAME1   TYPE KNA1-NAME1,
        L_SUB      TYPE SO_OBJ_DES,
        L_INVOICE  TYPE VBELN_VF,
        P_RECEIVER TYPE SO_RECNAME.

  CALL METHOD CL_DOCUMENT_BCS=>XSTRING_TO_SOLIX
    EXPORTING
      IP_XSTRING = W_OTF-PDF
    RECEIVING
      RT_SOLIX   = G_OBJCONT.


  CLASS CL_BCS DEFINITION LOAD.
  SEND_REQUEST = CL_BCS=>CREATE_PERSISTENT( ).
  FREE MESSAGE_BODY.
  CONCATENATE 'Dear Sir/Madam,' LV_NAME1  INTO LV_NAME1.
*    * Create message body and name of the attachment

  APPEND LV_NAME1 TO MESSAGE_BODY.
  APPEND INITIAL LINE TO MESSAGE_BODY.
  APPEND 'Please find the attached file of Email Intimation' TO MESSAGE_BODY.
  APPEND INITIAL LINE TO MESSAGE_BODY.
  APPEND 'With Regards,' TO MESSAGE_BODY.
*  APPEND 'HR.' TO MESSAGE_BODY.
  CONCATENATE 'Email Intimation' ''  INTO L_SUB.
*    * Email Body
  DOCUMENT = CL_DOCUMENT_BCS=>CREATE_DOCUMENT(
    I_TYPE    = 'RAW'
    I_TEXT    = MESSAGE_BODY
    I_SUBJECT = L_SUB ).
  TRY.
      W_SUBJECT = 'Email Intimation'.
      CALL METHOD DOCUMENT->ADD_ATTACHMENT
        EXPORTING
          I_ATTACHMENT_TYPE    = 'PDF'
          I_ATTACHMENT_SUBJECT = W_SUBJECT
          I_ATT_CONTENT_HEX    = G_OBJCONT.
    CATCH CX_DOCUMENT_BCS .
  ENDTRY.
*    * Pass the document to send request

  CALL METHOD SEND_REQUEST->SET_DOCUMENT( DOCUMENT ).

*    * Create recipient
  GV_SEND = P_USRID.
  RECIPIENT = CL_CAM_ADDRESS_BCS=>CREATE_INTERNET_ADDRESS( GV_SEND ).

*    *Set recipient

  CALL METHOD SEND_REQUEST->ADD_RECIPIENT
    EXPORTING
      I_RECIPIENT = RECIPIENT
      I_EXPRESS   = 'X'.
  TRY.
      CALL METHOD SEND_REQUEST->SET_SEND_IMMEDIATELY
        EXPORTING
          I_SEND_IMMEDIATELY = 'X'.
      .
    CATCH CX_SEND_REQ_BCS .
  ENDTRY.

  TRY.
      CALL METHOD SEND_REQUEST->SEND
        EXPORTING
          I_WITH_ERROR_SCREEN = 'X' "SPACE
        RECEIVING
          RESULT              = LV_SENT_TO_ALL.
    CATCH CX_SEND_REQ_BCS .
  ENDTRY.

  IF LV_SENT_TO_ALL = 'X'.
    MESSAGE 'Email sent succesfully'TYPE 'S'.
  ELSEIF LV_SENT_TO_ALL IS INITIAL.
    MESSAGE I000(8I) WITH 'Email not send'.
  ENDIF.
  COMMIT WORK.
ENDFORM.                    " F_SEND_MAIL
