"Name: \PR:RIQMEL20\EX:RIQMEL20_20\EI
ENHANCEMENT 0 ZPM_IW29.
*
    """""""""""""""""""""""""""""""""""""""""" Selection SCREEN IW29 CUSTOM
    TABLES: TJ30T, AFVC,PA0001 .

*  DATA: TEXT_001 TYPE String.
    SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE ZZTITLE1."ZZTITLE1.
      SELECTION-SCREEN BEGIN OF LINE.
        SELECTION-SCREEN COMMENT 1(20) PERNR FOR FIELD S_PERNR.
        SELECT-OPTIONS: S_PERNR FOR PA0001-PERNR.
      SELECTION-SCREEN END OF LINE.

      SELECTION-SCREEN BEGIN OF LINE.
        SELECTION-SCREEN COMMENT 1(20) ZMETER FOR FIELD S_METER.
        SELECT-OPTIONS: S_METER FOR RIHQMEL_LIST-ZZMETER_UPDATE.
      SELECTION-SCREEN END OF LINE.

      SELECTION-SCREEN BEGIN OF LINE.
        SELECTION-SCREEN COMMENT 1(20) ZUSTXT FOR FIELD S_USTXT.
        SELECT-OPTIONS: S_USTXT FOR RIHQMEL_LIST-USTXT NO INTERVALS.
      SELECTION-SCREEN END OF LINE.

      SELECTION-SCREEN BEGIN OF LINE.
        SELECTION-SCREEN COMMENT 1(20) ZZTEXT4 FOR FIELD S_ZZTEXT.
        SELECT-OPTIONS: S_ZZTEXT FOR RIHQMEL_LIST-ZZTEXT4 NO INTERVALS.
      SELECTION-SCREEN END OF LINE.
*      SELECTION-SCREEN BEGIN OF LINE.
*        SELECTION-SCREEN COMMENT 1(20) ZZLTRMN FOR FIELD S_LTRMN.
*        SELECT-OPTIONS: S_LTRMN FOR VIQMEL-LTRMN.
*      SELECTION-SCREEN END OF LINE.
*      SELECTION-SCREEN BEGIN OF LINE.
*        SELECTION-SCREEN COMMENT 1(20) ZTXT30 FOR FIELD S_TXT30.
*        SELECT-OPTIONS: S_TXT30 FOR TJ30T-TXT30 NO INTERVALS.
*      SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN END OF BLOCK B1.
ENDENHANCEMENT.
