*&---------------------------------------------------------------------*
*& Include          ZFI_VOID_CHECK_REGISTER_T01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Include          ZFI_VOID_CHECK_REGISTER_T01
*&---------------------------------------------------------------------*
*DATA:GT_MAIN TYPE STANDARD TABLE OF  RIHAUFK_LIST.


DATA: BEGIN OF OBJECT_TAB OCCURS 1.
INCLUDE STRUCTURE RIHAUFK_LIST AS RIHAUFK_LIST.
INCLUDE STRUCTURE EAML_S_LFE_DATA_ALV.
INCLUDE STRUCTURE EAMS_S_ORDER_MCALL.
DATA:  PPSID LIKE VIAUFKST-PPSID.
DATA:  IGEWRK LIKE VIAUFKST-GEWRK.          "Int Verant.Arbeitsplatz
DATA:  AUFPT  LIKE VIAUFKST-AUFPT.          "Int Netzwerknummer
DATA:  APLZT  LIKE VIAUFKST-APLZT.          "Int Netzwerkvorgang
DATA:  ADRNR_ILOA  LIKE VIAUFKST-ADRNR_ILOA."Adresse Bezugsobjekt
DATA:  TPLNR_INT   LIKE VIAUFKST-TPLNR.     "T.Platz int. Format
DATA:  NO_DISP    LIKE VIAUFKST-NO_DISP.    "Dispokennzeichen Datenb.
DATA: SELECTED,
      LIGHTS,
      PM_SELECTED TYPE PM_SELECTED,
      ROW_COUNT   TYPE SY-TABIX.
***********************************************
DATA: SERVICE_DOC_ID      TYPE AFIH-SERVICE_DOC_ID,
      SERVICE_DOC_ITEM_ID LIKE AFIH-SERVICE_DOC_ITEM_ID,
      IS_BILLABLE         LIKE AFIH-IS_BILLABLE,
      ORDERED_PROD        TYPE CRMS4_SERV_I_SEARCH-ORDERED_PROD,
      SALES_ORG_SD        TYPE CRMS4_SERV_I_SEARCH-SALES_ORG_SD,
      DIS_CHANNEL         TYPE CRMS4_SERV_I_SEARCH-DIS_CHANNEL,
      DIVISION            TYPE CRMS4_SERV_I_SEARCH-DIVISION,
      SOLD_TO_PARTY       TYPE CRMS4_SERV_I_SEARCH-SOLD_TO_PARTY.
      INCLUDE STRUCTURE EAM_S_IDMS_LACD_DATE.
DATA END OF OBJECT_TAB.

*Dynamic Call
DATA: LS_DATA TYPE REF TO DATA.
DATA: GV_FLAG TYPE CHAR1..
FIELD-SYMBOLS: <LT_DATA> TYPE ANY TABLE.

DATA:REPORT_DATE TYPE DATS,
     PERIOD_FROM TYPE DATS,
     PERIOD_TO   TYPE DATS,
     BANKA       TYPE BNKA-BANKA,
     BANKN       TYPE T012K-BANKN,
     BRNCH       TYPE BNKA-BRNCH,
     WAERS       TYPE T012K-WAERS,
     TOTAL       TYPE FAGL_CURRVAL_10.

*For ALV
DATA: IT_FIELDCAT TYPE LVC_T_FCAT,
      LS_FIELDCAT TYPE LVC_S_FCAT.
DATA:V_FIELDNAME TYPE FIELDNAME,
     V_SELTEXT   TYPE SCRTEXT_L,
     LR_DATA     TYPE REF TO DATA,
     LR_TABDESCR TYPE REF TO CL_ABAP_STRUCTDESCR,
     LT_DFIES    TYPE DDFIELDS,
     LS_DFIES    TYPE DFIES,
     LS_VARIANT  TYPE DISVARIANT...
