*&---------------------------------------------------------------------*
*& Include          ZPM_ASSITMENT_MANAGER_T01
*&---------------------------------------------------------------------*

TYPES:BEGIN OF TY_MAIN,
        CHK(1),
        ORDERID       TYPE BAPI_ALM_ORDER_HEADER_E-ORDERID,
        ACTIVITY      TYPE BAPI_ALM_ORDER_OPERATION_E-ACTIVITY,
        DESCRIPTION   TYPE BAPI_ALM_ORDER_OPERATION_E-DESCRIPTION,
        LACD_DATE     TYPE BAPI_ALM_ORDER_HEADER_E-LACD_DATE,
        PERS_NO       TYPE BAPI_ALM_ORDER_OPERATION_E-PERS_NO,
        EQUIPMENT     TYPE BAPI_ALM_ORDER_HEADER_E-EQUIPMENT,
        EQUIDESCR     TYPE BAPI_ALM_ORDER_OBJECTLIST-EQUIDESCR,
        ORDER_TYPE    TYPE BAPI_ALM_ORDER_HEADER_E-ORDER_TYPE,
        ABCINDIC      TYPE BAPI_ALM_ORDER_HEADER_E-ABCINDIC,
        PRIORITY      TYPE BAPI_ALM_ORDER_HEADER_E-PRIORITY,
        PRIOKX        TYPE T356_T-PRIOKX,
        FINISH_DATE   TYPE BAPI_ALM_ORDER_HEADER_E-FINISH_DATE,
        SYS_STATUS    TYPE BAPI_ALM_ORDER_HEADER_E-SYS_STATUS,
        MESSAGE       TYPE STRING,
        EQUIPMENT_SUP TYPE BAPI_ALM_ORDER_HEADER_E-EQUIPMENT,
        EQUIDESCR_SUP TYPE BAPI_ALM_ORDER_OBJECTLIST-FUNCLDESCR,
        WORK_DURATION TYPE AFVV-ARBEI,
        FUNCT_LOC     TYPE BAPI_ALM_ORDER_HEADER_E-FUNCT_LOC,
        FUNCLDESCR    TYPE BAPI_ALM_ORDER_OBJECTLIST-FUNCLDESCR,
        MAINTROOM     TYPE ILOA-MSGRP,
        REVISION      TYPE AFIH-REVNR,
        SORTFIELD     TYPE ILOA-EQFNR,
        MN_WK_CTR     TYPE CAUFVD-VAPLZ,
        ZREMARKS      TYPE AUFK-ZREMARKS,
      END OF TY_MAIN.

DATA:GT_MAIN TYPE STANDARD TABLE OF TY_MAIN,
     GS_MAIN LIKE LINE OF GT_MAIN.

*For ALV
DATA: IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      LS_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
      LS_LAYO     TYPE SLIS_LAYOUT_ALV.
DATA:V_FIELDNAME TYPE FIELDNAME,
     V_SELTEXT   TYPE SCRTEXT_L,
     LR_DATA     TYPE REF TO DATA,
     LR_TABDESCR TYPE REF TO CL_ABAP_STRUCTDESCR,
     LT_DFIES    TYPE DDFIELDS,
     LS_DFIES    TYPE DFIES,
     LS_VARIANT  TYPE DISVARIANT...

DATA: ET_PARTNER          TYPE STANDARD TABLE OF BAPI_ALM_ORDER_PARTNER,
      ET_OPERATIONS       TYPE STANDARD TABLE OF ZPM_ASSISTMENT_MANAGER_ST,
      ET_OPERATIONS_FIELD TYPE STANDARD TABLE OF ZPM_ASSISTMENT_MANAGER_ST,
      ET_COMPONENTS       TYPE STANDARD TABLE OF BAPI_ALM_ORDER_COMPONENT_E,
      ET_OLIST            TYPE STANDARD TABLE OF BAPI_ALM_ORDER_OBJECTLIST,
*For Tmp Tables
      ET_PARTNER_TMP      TYPE STANDARD TABLE OF BAPI_ALM_ORDER_PARTNER,
      ET_OPERATIONS_TMP   TYPE STANDARD TABLE OF BAPI_ALM_ORDER_OPERATION_E,
      ET_COMPONENTS_TMP   TYPE STANDARD TABLE OF BAPI_ALM_ORDER_COMPONENT_E,
      ET_OLIST_TMP        TYPE STANDARD TABLE OF BAPI_ALM_ORDER_OBJECTLIST,
*For Tmp Tables
      RETURN              TYPE STANDARD TABLE OF BAPIRET2,
      NUMBER              TYPE BAPI_ALM_ORDER_HEADER_E-ORDERID,
      ES_HEADER           TYPE BAPI_ALM_ORDER_HEADER_E,
      ET_HEADER           TYPE TABLE OF BAPI_ALM_ORDER_HEADER_E,
      LS_OPT              TYPE ZPM_ASSISTMENT_MANAGER_ST.



*For Update Declaration
DATA: LT_HEADER        TYPE TABLE OF BAPI_ALM_ORDER_HEADERS_I,
      LT_HEADER_UP     TYPE TABLE OF BAPI_ALM_ORDER_HEADERS_UP,
      LT_HEADER_SRV    TYPE TABLE OF BAPI_ALM_ORDER_SRVDAT_E,
      LT_HEADER_SRV_UP TYPE TABLE OF BAPI_ALM_ORDER_SRVDAT_UP,
      LT_PARTNER       TYPE TABLE OF BAPI_ALM_ORDER_PARTN_MUL,
      LT_OPERATION     TYPE TABLE OF BAPI_ALM_ORDER_OPERATION,
      LT_OPERATION_UP  TYPE TABLE OF BAPI_ALM_ORDER_OPERATION_UP,
      LT_METHODS       TYPE TABLE OF BAPI_ALM_ORDER_METHOD,
      LT_OBJECTLIST    TYPE TABLE OF BAPI_ALM_ORDER_OBJECTLIST,
      LT_NUMBERS       TYPE TABLE OF BAPI_ALM_NUMBERS,
      LT_RETURN        TYPE TABLE OF BAPIRET2.

"WORK Areas Declaration
DATA: LS_METHODS       TYPE BAPI_ALM_ORDER_METHOD,
      LS_HEADER        TYPE BAPI_ALM_ORDER_HEADERS_I,
      LS_HEADER_UP     TYPE BAPI_ALM_ORDER_HEADERS_UP,
      LS_HEADER_SRV    TYPE BAPI_ALM_ORDER_SRVDAT_E,
      LS_HEADER_SRV_UP TYPE BAPI_ALM_ORDER_SRVDAT_UP,
      LS_PARTNER       TYPE BAPI_ALM_ORDER_PARTN_MUL,
      LS_OPERATION     TYPE BAPI_ALM_ORDER_OPERATION,
      LS_OBJECTLIST    TYPE BAPI_ALM_ORDER_OBJECTLIST,
      LS_OP_UP         TYPE BAPI_ALM_ORDER_OPERATION_UP.

"Internal Tables Declaration

DATA: LT_PART_GET TYPE TABLE OF BAPI_ALM_ORDER_PARTNER,
      LT_OP_GET   TYPE TABLE OF BAPI_ALM_ORDER_OPERATION_E,
      LT_OBJ_GET  TYPE TABLE OF BAPI_ALM_ORDER_OBJECTLIST.

DATA:LV_CHECK_DATE(1).
DATA:LV_CHECK_PERNR(1).


DATA:
*    LT_VALUES TYPE STANDARD TABLE OF ZPM_PERNR_VIEW,
  LT_VALUES       TYPE STANDARD TABLE OF OBJECT_PERSON_ASSIGNMENT,
  LT_RETURN_VALUE TYPE STANDARD TABLE OF DDSHRETVAL.
