FUNCTION ZTEST.
*"----------------------------------------------------------------------
*"*"Update Function Module:
*"
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(ES_DATA) LIKE  CAUFVD STRUCTURE  CAUFVD OPTIONAL
*"----------------------------------------------------------------------
  BREAK ac_Adnan.
  TYPES:BEGIN OF TY_MAIN,
          WF_TYPE  TYPE ZPM_WF_ORD-WF_TYPE,
          COUNTALL TYPE ZLEVEL,
*
*
*          ORDER    TYPE ZPM_WF_ORD_CRT-AUFNR,
**          EQFNR    TYPE ZPM_WF_ORD-EQFNR,
*          IWERK    TYPE ZPM_WF_ORD-IWERK,
*          INGRP    TYPE ZPM_WF_ORD-INGRP,
*          ARBPL    TYPE ZPM_WF_ORD-ARBPL,
*          WERGW    TYPE ZPM_WF_ORD-WERGW,
        END OF TY_MAIN.

  DATA:L_OBJKEY         TYPE SWR_STRUCT-OBJECT_KEY,
       LS_MAIN          TYPE TY_MAIN,
       L_EVENT          TYPE SWR_STRUCT-EVENT,
       L_EVENTID        TYPE SWR_STRUCT-EVENT_ID,
       RETURN_CODE      LIKE  SY-SUBRC,
       countAll         TYPE  ZLEVEL,
       LS_PM_WF_ORD_CRT TYPE ZPM_WF_ORD_CRT..

*For WorkCenter
  SELECT SINGLE ARBPL FROM CRHD
    INTO @DATA(LV_ARBPL)
    WHERE OBJID = @ES_DATA-GEWRK
    AND ENDDA = '99991231'.

*For Total Count
  SELECT MAX( LEVELS ) INTO @DATA(LV_COUNT)
     FROM ZPM_WF_ORD
    WHERE WF_TYPE   = @ES_DATA-AUART .
**    AND
***          EQFNR     = ES_DATA-AUFNR AND
**          IWERK     = @ES_DATA-IWERK AND
**          INGRP     = @ES_DATA-INGPR AND
**          ARBPL     = @LV_ARBPL AND
**          WERGW     = @ES_DATA-WERKS.
  LS_MAIN-WF_TYPE = ES_DATA-AUART.
  LS_MAIN-COUNTALL = LV_COUNT.
*  LS_MAIN-ORDER   = ES_DATA-AUFNR.

**  LS_MAIN-EQFNR   = ES_DATA-EQFNR.
*  LS_MAIN-IWERK   = ES_DATA-IWERK.
*  LS_MAIN-INGRP   = ES_DATA-INGPR.
*  LS_MAIN-ARBPL   = LV_ARBPL.
*  LS_MAIN-WERGW   = ES_DATA-WERKS.

*      LS_MAIN-WFType = '6.1'.
*  LS_MAIN-PlanningPlant = ES_DATA-IWERK.
*  LS_MAIN-MaintPlannerGroup = ES_DATA-INGPR.
*  LS_MAIN-WorkCenter = ES_DATA-VAPLZ.
*  LS_MAIN-MaintPlannerGroup = ES_DATA-VAWRK.

  L_OBJKEY = LS_MAIN.

  L_EVENT = 'CREATED'."Give the event name which u want to trigger of ur Business object



  DATA :INPUT_CONTAINE TYPE TABLE OF SWR_CONT,
        X_CONT         TYPE SWR_CONT.

  X_CONT-ELEMENT = 'WF_TYPE'.
  X_CONT-VALUE = ES_DATA-AUART..

  APPEND X_CONT TO INPUT_CONTAINE.
  CLEAR X_CONT..


  X_CONT-ELEMENT = 'COUNTALL'.
  X_CONT-VALUE = LS_MAIN-COUNTALL ..

  APPEND X_CONT TO INPUT_CONTAINE.
  CLEAR X_CONT..


*  X_CONT-ELEMENT = 'AUFNR'.
*  X_CONT-VALUE = ES_DATA-AUFNR..
*
*  APPEND X_CONT TO INPUT_CONTAINE.
*  CLEAR X_CONT..


*  X_CONT-ELEMENT = 'EQFNR'.
*  X_CONT-VALUE = ES_DATA-EQFNR..
*
*  APPEND X_CONT TO INPUT_CONTAINE.
*  CLEAR X_CONT.

*  X_CONT-ELEMENT = 'IWERK'.
*  X_CONT-VALUE = ES_DATA-IWERK..
*
*  APPEND X_CONT TO INPUT_CONTAINE.
*  CLEAR X_CONT.
*
*  X_CONT-ELEMENT = 'INGRP'.
*  X_CONT-VALUE = ES_DATA-INGPR ..
*
*  APPEND X_CONT TO INPUT_CONTAINE.
*  CLEAR X_CONT.
*
*  X_CONT-ELEMENT = 'ARBPL'.
*  X_CONT-VALUE = LV_ARBPL ..
*
*  APPEND X_CONT TO INPUT_CONTAINE.
*  CLEAR X_CONT.
*
*  X_CONT-ELEMENT = 'WERGW'.
*  X_CONT-VALUE = ES_DATA-WERKS ..
*
*  APPEND X_CONT TO INPUT_CONTAINE.
*  CLEAR X_CONT.

***
***  X_CONT-ELEMENT = 'WFType'.
***  X_CONT-VALUE = '6.1'..
***
***  APPEND X_CONT TO INPUT_CONTAINE.
***  CLEAR X_CONT..
***
***  X_CONT-ELEMENT = 'MaintPlannerGroup'.
***  X_CONT-VALUE = ES_DATA-VAWRK.
***
***  APPEND X_CONT TO INPUT_CONTAINE.
***  CLEAR X_CONT.
***
***  X_CONT-ELEMENT = 'PlanningPlant'.
***  X_CONT-VALUE = ES_DATA-IWERK.
***
***  APPEND X_CONT TO INPUT_CONTAINE.
***  CLEAR X_CONT.
***
***  X_CONT-ELEMENT = 'PlantForWorkCenter'.
***  X_CONT-VALUE = ES_DATA-VAPLZ.
***
***  APPEND X_CONT TO INPUT_CONTAINE.
***  CLEAR X_CONT.


  CALL FUNCTION 'SAP_WAPI_CREATE_EVENT' DESTINATION 'NONE'
    EXPORTING
      OBJECT_TYPE     = 'ZPM_ORD_WF'
      OBJECT_KEY      = L_OBJKEY
      EVENT           = L_EVENT
*     COMMIT_WORK     = 'X'
*     EVENT_LANGUAGE  = SY-LANGU
*     LANGUAGE        = SY-LANGU
*     USER            = SY-UNAME
*     IFS_XML_CONTAINER =
    IMPORTING
      RETURN_CODE     = RETURN_CODE
      EVENT_ID        = L_EVENTID
    TABLES
      INPUT_CONTAINER = INPUT_CONTAINE
*     MESSAGE_LINES   =
*     MESSAGE_STRUCT  =
    .
  IF RETURN_CODE = 0.

    MOVE-CORRESPONDING LS_MAIN TO LS_PM_WF_ORD_CRT.
    LS_PM_WF_ORD_CRT-CRT_DATE =  SY-DATUM.
    LS_PM_WF_ORD_CRT-CRT_TIME =  SY-UZEIT.
    LS_PM_WF_ORD_CRT-STATUS =  'C'.
    INSERT INTO ZPM_WF_ORD_CRT VALUES LS_PM_WF_ORD_CRT..



  ENDIF.





ENDFUNCTION.
