*&---------------------------------------------------------------------*
*& Include          ZPM_CLASS_IMPLT
*&---------------------------------------------------------------------*
CLASS EVENT_HANDLER DEFINITION.
  PUBLIC SECTION.

    METHODS TOOLBAR_FUNCTION_SELECTED
      FOR EVENT FUNCTION_SELECTED OF IF_SALV_GUI_TOOLBAR_IDA
      IMPORTING EV_FCODE.
    METHODS CONSTRUCTOR IMPORTING IO_ALV_DISPLAY TYPE REF TO IF_SALV_GUI_TABLE_IDA.
  PRIVATE SECTION.
    DATA MO_ALV_DISPLAY TYPE REF TO IF_SALV_GUI_TABLE_IDA.
*    DATA M_LESS_THAN_10 TYPE ABAP_BOOL VALUE ABAP_FALSE. "toggle state
*    METHODS SET_SELECTION_FROM_TOGGLE_STAT.
ENDCLASS.

CLASS EVENT_HANDLER IMPLEMENTATION.
  METHOD TOOLBAR_FUNCTION_SELECTED.
    DATA: LR_ALV    TYPE REF TO CL_SALV_TABLE.
    DATA: LS_WA     TYPE SFLIGHT.

    CASE EV_FCODE.
      WHEN 'DETAIL_SCREEN'.
        O_DATA->REFRESH( ).
    ENDCASE.

  ENDMETHOD.
  METHOD CONSTRUCTOR.
    MO_ALV_DISPLAY = IO_ALV_DISPLAY.
  ENDMETHOD.
ENDCLASS.
