"Name: \PR:RIAUFK20\EX:RIAUFK20_02\EI
ENHANCEMENT 0 ZPM_IW39_SELECTION_SCREEN.
*
  TABLES: VIQMEL, TJ30T, AFVC.
  SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE ZZTITLE.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(20) ZLTRMN FOR FIELD S_LTRMN.
      SELECT-OPTIONS: S_LTRMN FOR VIQMEL-LTRMN.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(20) ZPERNR FOR FIELD S_PERNR.
      SELECT-OPTIONS: S_PERNR FOR AFVC-PERNR.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(20) ZTXT30 FOR FIELD S_TXT30.
      SELECT-OPTIONS: S_TXT30 FOR TJ30T-TXT30 NO INTERVALS.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(20) ZMETER FOR FIELD S_METER.
      SELECT-OPTIONS: S_METER FOR RIHAUFK_LIST-ZZMETER_UPDATE.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(20) ZZTEXT FOR FIELD S_ZZTEXT.
      SELECT-OPTIONS: S_ZZTEXT FOR RIHAUFK_LIST-ZZTEXT4 NO INTERVALS.
    SELECTION-SCREEN END OF LINE.

*    SELECTION-SCREEN BEGIN OF LINE.
*      SELECTION-SCREEN COMMENT 1(20) GLTRP FOR FIELD S_GLTRP.
*      SELECT-OPTIONS: S_GLTRP FOR RIHAUFK_LIST-GLTRP.
*    SELECTION-SCREEN END OF LINE.



  SELECTION-SCREEN END OF BLOCK B1.
ENDENHANCEMENT.
