*&---------------------------------------------------------------------*
*& Include          ZPM_JOB_CARD_REPORT_T01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
DATA:GT_MAIN TYPE ZPM_EQUIPMENT_TRANSFER_TT,
     GS_MAIN LIKE LINE OF GT_MAIN.


*Dynamic Call
DATA: LS_DATA TYPE REF TO DATA.
DATA: GV_FLAG TYPE CHAR1..
FIELD-SYMBOLS: <LT_DATA> TYPE TABLE.

*Global Parameter

DATA:REPORT_DATE TYPE DATS,
     PERIOD_FROM TYPE DATS,
     PERIOD_TO   TYPE DATS,
     BANKA       TYPE BNKA-BANKA,
     BANKN       TYPE T012K-BANKN,
     BRNCH       TYPE BNKA-BRNCH,
     WAERS       TYPE T012K-WAERS,
     TOTAL       TYPE FAGL_CURRVAL_10.


*For Bapi
DATA NUMBER             TYPE BAPI2080_NOTHDRE-NOTIF_NO.
DATA CLEAR_BUFFER       TYPE BAPI2080_NOTHDRE-DELETE_FLAG.
DATA NOTIFHEADER_EXPORT TYPE BAPI2080_NOTHDRE.
DATA NOTIFHDTEXT        TYPE BAPI2080_NOTHDTXTE.
DATA MAINTACTYTYPE      TYPE ILA.
DATA NOTLONGTXT         TYPE STANDARD TABLE OF BAPI2080_NOTFULLTXTE.
DATA NOTITEM            TYPE STANDARD TABLE OF BAPI2080_NOTITEME.
DATA NOTIFCAUS          TYPE STANDARD TABLE OF BAPI2080_NOTCAUSE.
DATA NOTIFACTV          TYPE STANDARD TABLE OF BAPI2080_NOTACTVE.
DATA NOTIFTASK          TYPE STANDARD TABLE OF BAPI2080_NOTTASKE.
DATA NOTIFPARTNR        TYPE STANDARD TABLE OF BAPI2080_NOTPARTNRE.
DATA RETURN             TYPE STANDARD TABLE OF BAPIRET2.
DATA EXTENSIONOUT       TYPE STANDARD TABLE OF BAPIPAREX.



*For Zone Location Text
DATA: FUNCTLOCATION             TYPE BAPI_ITOB_PARMS-FUNCLOC_INT,
      REQUEST_INSTALLATION_DATA TYPE XFELD,
      DATA_GENERAL_EXP          TYPE BAPI_ITOB,
      DATA_SPECIFIC_EXP         TYPE BAPI_ITOB_FL_ONLY,
      RETURN_ZONE               TYPE BAPIRET2,
      DATA_INSTALLATION         TYPE BAPI_ITOB_INSTALLATION_DETAILS,
      EXTENSIONOUT_ZONE         TYPE STANDARD TABLE OF BAPIPAREX,
      LV_ZONE                   TYPE STRING.
