"Name: \PR:SAPLIQS0\FO:TZONE_CONVERT2SESS_MZEIT\SE:BEGIN\EI
ENHANCEMENT 0 ZPM_REPORTED_BY_LOGON_USER.

IF SY-TCODE = 'IW21' OR SY-TCODE = 'IW31' OR SY-TCODE = 'IP30'   OR SY-TCODE = 'IP41' OR SY-TCODE = 'IP10'.
  VIQMEL-QMNAM = SY-UNAME.
ENDIF.
ENDENHANCEMENT.
