"Name: \PR:RIQMEL20\FO:SELECTION_L\SE:END\EI
ENHANCEMENT 0 ZPM_IW29.
*
  """""""""""""""""""""""""""""""""""""""""CODE IW29
  DATA: LV_LEN TYPE I,
        LV_FL3 TYPE IFLO-TPLNR,
        LV_FL4 TYPE IFLO-TPLNR.
  DATA EQUIPMENT     TYPE BAPI_ITOB_PARMS-EQUIPMENT.

  DATA SYSTEM_STATUS TYPE STANDARD TABLE OF BAPI_ITOB_STATUS.
  DATA USER_STATUS   TYPE STANDARD TABLE OF BAPI_ITOB_STATUS.
  DATA: LV_ROOT(1), LV_HEQUI TYPE EQUZ-HEQUI, LV_EQUNR TYPE EQUZ-EQUNR.

  DATA MEASUREMENT_POINT_OBJECT TYPE IMPT-MPOBJ.
  DATA IMPT_TAB                 TYPE STANDARD TABLE OF IMPT.

*Split Fuction location DataDeclaration
  DATA:LV_FUNC_CHK_3 TYPE STRING,
       LV_FUNC_CHK_4 TYPE STRING,
       S1            TYPE STRING,
       S2            TYPE STRING,
       S3            TYPE STRING,
       S4            TYPE STRING,
       S5            TYPE STRING,
       S6            TYPE STRING.


  ""Code change value
  BREAK AC_OWAIS.
  IF OBJECT_TAB[] IS NOT INITIAL.
    SELECT DISTINCT EQUNR, OBJNR FROM EQUI
      FOR ALL ENTRIES IN @OBJECT_TAB
      WHERE EQUNR EQ @OBJECT_TAB-EQUNR
      INTO TABLE @DATA(LT_EQUI).

    SELECT DISTINCT EQUNR, EQART, PROID FROM ITOB FOR ALL ENTRIES IN @OBJECT_TAB
      WHERE EQUNR EQ @OBJECT_TAB-EQUNR
      AND DATBI = ( SELECT MAX( DATBI ) FROM ITOB WHERE EQUNR EQ @OBJECT_TAB-EQUNR )
      INTO TABLE @DATA(LT_EQART).

    SELECT A~AUFNR, A~GLTRS, B~PERNR INTO TABLE @DATA(LT_AFKO_AFVC) FROM AFKO AS A
      INNER JOIN AFVC AS B ON A~AUFPL = B~AUFPL
      FOR ALL ENTRIES IN @OBJECT_TAB
      WHERE A~AUFNR EQ @OBJECT_TAB-AUFNR.

    SELECT EQUNR, HEQUI
      FROM EQUZ
      INTO TABLE @DATA(LT_ROOT)
*      FOR ALL ENTRIES IN @OBJECT_TAB
*      WHERE EQUNR EQ @OBJECT_TAB-EQUNR
      WHERE DATBI EQ '99991231'.
*      AND DATBI EQ '99991231'.

    SELECT QMNUM, FEGRP FROM VIQMFE FOR ALL ENTRIES IN @OBJECT_TAB
        WHERE QMNUM EQ @OBJECT_TAB-QMNUM
        AND FEGRP NE ''
        INTO TABLE @DATA(LT_VIQMFE) .

    SELECT AUFNR, ERDAT FROM AUFK
        FOR ALL ENTRIES IN @OBJECT_TAB
        WHERE AUFNR = @OBJECT_TAB-AUFNR
        INTO TABLE @DATA(LT_AUFK).

    SELECT IWERK, REVNR, REVTX FROM T352R FOR ALL ENTRIES IN @OBJECT_TAB
        WHERE IWERK EQ @OBJECT_TAB-IWERK AND REVNR EQ @OBJECT_TAB-REVNR
        INTO TABLE @DATA(LT_T352R).

    SELECT * FROM TQ80_T FOR ALL ENTRIES IN @OBJECT_TAB
      WHERE SPRAS EQ 'E'
      AND QMART EQ @OBJECT_TAB-QMART
      INTO TABLE @DATA(LT_TQ80_T).

    SELECT QMNUM,ZQMTXT FROM QMEL INTO TABLE @DATA(LT_QMEL)
      FOR ALL ENTRIES IN @OBJECT_TAB
      WHERE QMNUM = @OBJECT_TAB-QMNUM.

    IF LT_QMEL[] IS NOT INITIAL.

      SELECT * FROM IFLOTX
          INTO TABLE  @DATA(LT_FLTXT)
        FOR ALL ENTRIES IN @LT_QMEL
          WHERE TPLNR = @LT_QMEL-ZQMTXT(30)
          AND SPRAS = @SY-LANGU.

    ENDIF.

  ENDIF.
  IF LT_EQART[] IS NOT INITIAL  .
    SELECT * FROM T370K_T INTO TABLE @DATA(LT_EARTX) FOR ALL ENTRIES IN @LT_EQART
      WHERE SPRAS EQ 'E' AND EQART EQ @LT_EQART-EQART.
  ENDIF.

  LOOP AT OBJECT_TAB INTO DATA(LS_TAB).
    LOOP AT LT_EQART INTO DATA(LS_EQART) WHERE EQUNR EQ LS_TAB-EQUNR.
      LS_TAB-ZZEQART = LS_EQART-EQART.
      LS_TAB-ZZPROID = LS_EQART-PROID.
    ENDLOOP.
    LOOP AT LT_EARTX INTO DATA(LS_EARTX) WHERE EQART EQ LS_TAB-ZZEQART.
      LS_TAB-ZZEARTX = LS_EARTX-EARTX.
    ENDLOOP.
    LOOP AT LT_AFKO_AFVC INTO DATA(LS_AFKO_AFVC) WHERE AUFNR EQ LS_TAB-AUFNR.
      LS_TAB-ZZGLTRS = LS_AFKO_AFVC-GLTRS.
      LS_TAB-ZZPERNR = LS_AFKO_AFVC-PERNR.
    ENDLOOP.
    IF LS_TAB-EQUNR IS NOT INITIAL.
      CLEAR: SYSTEM_STATUS[], EQUIPMENT.
      EQUIPMENT = LS_TAB-EQUNR.
      CALL FUNCTION 'BAPI_EQUI_GETSTATUS'
        EXPORTING
          EQUIPMENT     = EQUIPMENT
          LANGUAGE      = SY-LANGU
        TABLES
          SYSTEM_STATUS = SYSTEM_STATUS
          USER_STATUS   = USER_STATUS.
      LOOP AT SYSTEM_STATUS INTO DATA(LS_STATUS).
        LS_TAB-ZZTEXT4 = LS_STATUS-TEXT.
      ENDLOOP.

    ENDIF.
    CLEAR: LV_LEN,LV_FL3,LV_FL4.
    LV_LEN = STRLEN( LS_TAB-TPLNR ).

*For split function location
    IF LV_LEN IS NOT INITIAL AND LV_LEN GE 12.
*      LV_FL3 = LS_TAB-TPLNR+0(12).
      SPLIT LS_TAB-TPLNR AT '-' INTO S1 S2 S3 S4 S5 S6.
      CONCATENATE S1 S2 S3 INTO LV_FUNC_CHK_3 SEPARATED BY '-'.
      SELECT SINGLE PLTXU INTO  LS_TAB-ZZFL3 FROM IFLO WHERE TPLNR = LV_FUNC_CHK_3 AND SPRAS EQ 'E'.
*      SELECT SINGLE PLTXT INTO LS_TAB-ZZFL3 FROM IFLO WHERE TPLNR EQ LV_FL3 AND SPRAS EQ 'E'.

      IF LV_LEN GE 17.
*        LV_FL4 = LS_TAB-TPLNR+0(17).
        CONCATENATE S1 S2 S3 S4 INTO LV_FUNC_CHK_4 SEPARATED BY '-'.
        SELECT SINGLE PLTXU INTO  LS_TAB-ZZFL4 FROM IFLO WHERE TPLNR = LV_FUNC_CHK_4 AND SPRAS EQ 'E'.
*        SELECT SINGLE PLTXT INTO LS_TAB-ZZFL4 FROM IFLO WHERE TPLNR EQ LV_FL4 AND SPRAS EQ 'E'.
      ENDIF.

    ENDIF.
    """ROOT
    CLEAR: LV_ROOT, LV_HEQUI, LV_EQUNR.
    LV_EQUNR = LS_TAB-EQUNR.
    IF LV_EQUNR IS NOT INITIAL.
      WHILE ( LV_ROOT NE 'X' ).

        LOOP AT LT_ROOT INTO DATA(LS_ROOT) WHERE EQUNR EQ LV_EQUNR.
          IF LS_ROOT-HEQUI EQ ''.
            LV_ROOT = 'X'.
          ELSE.
            LV_EQUNR = LS_ROOT-HEQUI.
          ENDIF.
        ENDLOOP.
        IF SY-SUBRC NE 0.
          LV_ROOT = 'X'.
        ENDIF.
*              read table lt_root into data(ls_root) WITH TABLE KEY equnr
      ENDWHILE.


      CLEAR: SYSTEM_STATUS[], EQUIPMENT.
      LS_TAB-ZZROOT = LV_EQUNR.
*      SELECT SINGLE TIDNR, SHTXT INTO ( @LS_TAB-ZZROOT, @LS_TAB-ZZROOT_DES ) FROM ITOB WHERE EQUNR = @LS_TAB-ZZROOT AND DATBI EQ '99991231'.
      SELECT SINGLE SHTXT INTO ( @LS_TAB-ZZROOT_DES ) FROM ITOB WHERE EQUNR = @LS_TAB-ZZROOT AND DATBI EQ '99991231'.
*      EQUIPMENT = LV_EQUNR.
*      CALL FUNCTION 'BAPI_EQUI_GETSTATUS'
*        EXPORTING
*          EQUIPMENT     = EQUIPMENT
*          LANGUAGE      = SY-LANGU
*        TABLES
*          SYSTEM_STATUS = SYSTEM_STATUS
*          USER_STATUS   = USER_STATUS.
*      LOOP AT SYSTEM_STATUS INTO LS_STATUS.
*        LS_TAB-ZZROOT_DES = LS_STATUS-DESCRIPTION.
*      ENDLOOP.
      SHIFT LS_TAB-ZZROOT LEFT DELETING LEADING '0'.

    ENDIF.

    """""""""""""""""""""""""""""""""""""""""METER READING

    READ TABLE LT_EQUI INTO DATA(LS_EQUI) WITH KEY EQUNR = LS_TAB-EQUNR.
    IF SY-SUBRC EQ 0.
      CLEAR: MEASUREMENT_POINT_OBJECT.
      MEASUREMENT_POINT_OBJECT = LS_EQUI-OBJNR.

********      CALL FUNCTION 'MEASUREM_POINTS_READ_TO_OBJECT'
********        EXPORTING
********          MEASUREMENT_POINT_OBJECT = MEASUREMENT_POINT_OBJECT
********        TABLES
********          IMPT_TAB                 = IMPT_TAB
********        EXCEPTIONS
********          NO_ENTRY_FOUND           = 1.
********
********      SORT IMPT_TAB DESCENDING BY POINT.
********      READ TABLE IMPT_TAB INTO DATA(LS_IMPT) INDEX 1.
********      IF SY-SUBRC EQ 0.
********      LS_TAB-ZZMETER_READING = LS_IMPT-POINT.
********      LS_TAB-ZZMETER_DESC = LS_IMPT-PTTXT.
********      LS_TAB-ZZMETER_UPDATE = LS_IMPT-ERDAT.
*********      LS_TAB-ZZMETER_NAME = LS_IMPT-POINT.
********      LS_TAB-ZZMETER_NAME = LS_IMPT-PSORT.
********      CONDENSE LS_TAB-ZZMETER_NAME.
********      SHIFT LS_TAB-ZZMETER_NAME LEFT DELETING LEADING '0'.
********
********
********      SELECT SINGLE RECDV INTO @DATA(LS_RECDV) FROM IMRG WHERE POINT EQ @LS_IMPT-POINT AND MDOCM = ( SELECT MAX( MDOCM ) FROM IMRG WHERE POINT = @LS_IMPT-POINT  ).
********      ENDIF.
********      DATA I_NUMBER_OF_DIGITS       TYPE CHA_CLASS_DATA-STELLEN.
********      DATA I_FLTP_VALUE             TYPE CHA_CLASS_DATA-SOLLWERT.
********      DATA I_VALUE_NOT_INITIAL_FLAG TYPE CHA_CLASS_DATA-SOLLWNI.
********      DATA I_SCREEN_FIELDLENGTH     TYPE ICON-OLENG.
********      DATA E_CHAR_FIELD             TYPE CHA_CLASS_VIEW-SOLLWERT.
********      I_NUMBER_OF_DIGITS = 2.
********      CALL FUNCTION 'QSS0_FLTP_TO_CHAR_CONVERSION'
********        EXPORTING
********          I_NUMBER_OF_DIGITS = I_NUMBER_OF_DIGITS
********          I_FLTP_VALUE       = LS_RECDV
*********         I_VALUE_NOT_INITIAL_FLAG       = 'X'
*********         I_SCREEN_FIELDLENGTH           = 16
********        IMPORTING
********          E_CHAR_FIELD       = E_CHAR_FIELD.
********      LS_TAB-ZZMETER_READING = E_CHAR_FIELD.



      CLEAR: IMPT_TAB[], LS_EQUI, IMPT_TAB, MEASUREMENT_POINT_OBJECT."LS_IMPT
    ENDIF.

    READ TABLE LT_T352R INTO DATA(LS_T352R1) WITH KEY IWERK = LS_TAB-IWERK REVNR = LS_TAB-REVNR.
    IF SY-SUBRC EQ 0.
      LS_TAB-ZZREVTX = LS_T352R1-REVTX.
    ENDIF.

    READ TABLE LT_TQ80_T INTO DATA(LS_TQ80_T) WITH KEY QMART = LS_TAB-QMART.
    IF SY-SUBRC EQ 0.
      CONCATENATE LS_TQ80_T-QMART LS_TQ80_T-QMARTX INTO LS_TAB-ZZWORK_TYPE SEPARATED BY '-'.
    ENDIF.

    READ TABLE LT_VIQMFE INTO DATA(LS_VIQMFE) WITH KEY QMNUM = LS_TAB-QMNUM.
    IF SY-SUBRC EQ 0.
      LS_TAB-ZZFEGRP = LS_VIQMFE-FEGRP.
    ENDIF.
    READ TABLE LT_AUFK INTO DATA(LS_AUFK) WITH KEY AUFNR = LS_TAB-AUFNR.
    IF SY-SUBRC EQ 0.
      LS_TAB-ZZREPORT_DATE = LS_AUFK-ERDAT.
    ENDIF.
    LS_TAB-ZZSUPERVISOR = LS_TAB-ARBPL.
    CLEAR: LS_VIQMFE.

    READ TABLE LT_QMEL ASSIGNING FIELD-SYMBOL(<FS_QMEL>) WITH KEY QMNUM = LS_TAB-QMNUM.
    IF SY-SUBRC = 0.
      LS_TAB-ZZTARFL = <FS_QMEL>-ZQMTXT.
      READ TABLE LT_FLTXT ASSIGNING FIELD-SYMBOL(<FS_FLTXT>) WITH KEY TPLNR = LS_TAB-ZZTARFL.
      IF SY-SUBRC = 0.
        LS_TAB-ZZTARFLTXT = <FS_FLTXT>-PLTXT.
      ENDIF.
    ENDIF.

    MODIFY OBJECT_TAB FROM LS_TAB.
    CLEAR: IMPT_TAB[], LS_EQUI, IMPT_TAB, MEASUREMENT_POINT_OBJECT.
  ENDLOOP.
  CLEAR: IMPT_TAB[], LS_EQUI, IMPT_TAB, MEASUREMENT_POINT_OBJECT.

  DELETE OBJECT_TAB WHERE ZZPERNR NOT IN S_PERNR.
  DELETE OBJECT_TAB WHERE ZZMETER_UPDATE NOT IN S_METER.
  DELETE OBJECT_TAB WHERE USTXT NOT IN S_USTXT.
  DELETE OBJECT_TAB WHERE ZZTEXT4 NOT IN S_ZZTEXT.


ENDENHANCEMENT.
