"Name: \FU:CALCULATE_PRIORITY_2\SE:BEGIN\EI
ENHANCEMENT 0 ZPM_REMOVE_POPUP_PRIO.
  if I_FLG_POPUP = 'X' and ( sy-TCODE = 'IW22' or sy-TCODE = 'IW21' ).
    clear I_FLG_POPUP.
    endif.
ENDENHANCEMENT.
