*&---------------------------------------------------------------------*
*& Include          ZPM_CRF_UPDATION_FORM_T01
*&---------------------------------------------------------------------*
TYPES:BEGIN OF TY_MAIN,
        RSNUM            TYPE MSEG-RSNUM,
        MATNR            TYPE MARA-MATNR,
        MAKTX            TYPE MAKT-MAKTX,
        CHARG            TYPE MSEG-CHARG,
        AUFNR            TYPE AUFNR,
        LIFNR            TYPE AUFK-ZLIFNR,
        NAME1            TYPE LFA1-NAME1,
        UNIT_COST        TYPE P DECIMALS 3,
        PLANNED_QTY      TYPE P DECIMALS 3,
        ISSUED_QTY       TYPE P DECIMALS 3,
        RETURN_QTY       TYPE P DECIMALS 3,
        BALANCE_QTY      TYPE P DECIMALS 3,
        ASBUILT_QTY      TYPE ZPM_BUILT-ASBUILT_QTY,
        ASBUILT_DATE     TYPE ZPM_BUILT-ASBUILT_DATE,
        ASBUILT_COST     TYPE P DECIMALS 3,
        OUTSTANDING_QTY  TYPE P DECIMALS 3,
        OUTSTANDING_COST TYPE P DECIMALS 3,
        WAERS            TYPE TCURR_CURR,
        UNAME            TYPE UNAME,
        CPUDT            TYPE ZPM_BUILT-CPUDT,
        CPUTM            TYPE ZPM_BUILT-CPUTM,
      END OF TY_MAIN.

DATA:GT_MAIN     TYPE STANDARD TABLE OF TY_MAIN,
     GT_MAIN_TMP TYPE STANDARD TABLE OF TY_MAIN,
     GS_MAIN     LIKE LINE OF GT_MAIN,
     GT_PM_BUILT TYPE STANDARD TABLE OF ZPM_BUILT,
     GS_PM_BUILT TYPE ZPM_BUILT.

*FOR ALV

DATA: IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      LS_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
      LS_LAYO     TYPE SLIS_LAYOUT_ALV.
DATA:V_FIELDNAME TYPE FIELDNAME,
     V_SELTEXT   TYPE SCRTEXT_L,
     LR_DATA     TYPE REF TO DATA,
     LR_TABDESCR TYPE REF TO CL_ABAP_STRUCTDESCR,
     LT_DFIES    TYPE DDFIELDS,
     LS_DFIES    TYPE DFIES,
     LS_VARIANT  TYPE DISVARIANT...
