*&---------------------------------------------------------------------*
*& Include          ZPM_ASSITMENT_MANAGER_S01
*&---------------------------------------------------------------------*
TABLES:VIAUFKST,MSEG.
SELECT-OPTIONS:S_WERKS FOR MSEG-WERKS  NO INTERVALS NO-EXTENSION  ,
               S_VAPLZ FOR VIAUFKST-VAPLZ MATCHCODE OBJECT CRAM NO INTERVALS  NO-EXTENSION,
               S_EQUNR FOR VIAUFKST-EQUNR NO INTERVALS  NO-EXTENSION MATCHCODE OBJECT ZPARNT_EQUNR_SH  ,
               S_TPLNR FOR VIAUFKST-TPLNR NO INTERVALS  NO-EXTENSION  ,
               S_AUFNR FOR VIAUFKST-AUFNR NO INTERVALS  NO-EXTENSION  ,
               S_AUART FOR VIAUFKST-AUART NO INTERVALS  NO-EXTENSION  ,
               S_PRIOK FOR VIAUFKST-PRIOK NO INTERVALS  NO-EXTENSION  ,
               S_GLTRP FOR VIAUFKST-GLTRP NO-EXTENSION.

PARAMETERS:P_FDATE TYPE DATS .
PARAMETERS:P_PERNR TYPE PERNR_D." MATCHCODE OBJECT ZPM_PERNR .


***AT SELECTION-SCREEN OUTPUT .
AT SELECTION-SCREEN OUTPUT .

  IF S_WERKS-LOW IS INITIAL.
    LOOP AT SCREEN.
      IF SCREEN-NAME = 'S_VAPLZ-LOW'.
        SCREEN-INPUT = '0'.
        SCREEN-INVISIBLE = '0'.
        SCREEN-REQUIRED = '0'.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
  ENDIF.

  SET PARAMETER ID 'WRK' FIELD S_WERKS-LOW.
*SET PARAMETER ID 'VAP' FIELD S_VAPLZ-LOW.


AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_PERNR.
  SELECT SINGLE * FROM CRHD
    INTO @DATA(LS_CRHD)
    WHERE ARBPL = @S_VAPLZ-LOW.
  IF SY-SUBRC = 0.
    DATA ARBPL       TYPE CRHD-ARBPL.
    DATA WERKS       TYPE CRHD-WERKS.
    DATA DATE        TYPE TIMELIST-DATE.
    DATA OUT_PERSONS TYPE STANDARD TABLE OF OBJECT_PERSON_ASSIGNMENT.

    CALL FUNCTION 'CR_PERSONS_OF_WORKCENTER'
      EXPORTING
        ARBPL                       = S_VAPLZ-LOW
        WERKS                       = S_WERKS-LOW
        DATE                        = SY-DATUM
      TABLES
        OUT_PERSONS                 = OUT_PERSONS
      EXCEPTIONS
        INVALID_OBJECT              = 1
        INVALID_HR_PLANNING_VARIANT = 2
        OTHER_ERROR                 = 3.

    DELETE OUT_PERSONS WHERE OTYPE <> 'KA'.

  ENDIF.

  CALL FUNCTION 'F4IF_INT_TABLE_VALUE_REQUEST'
    EXPORTING
      RETFIELD        = 'PERNR'    " Name of field in VALUE_TAB
      VALUE_ORG       = 'S'        " Value return: C: cell by cell, S: structured
    TABLES
      VALUE_TAB       = OUT_PERSONS  " Table of values: entries cell by cell
      RETURN_TAB      = LT_RETURN_VALUE  " Return the selected value
    EXCEPTIONS
      PARAMETER_ERROR = 1          " Incorrect parameter
      NO_VALUES_FOUND = 2          " No values found
      OTHERS          = 3.

  IF SY-SUBRC NE 0.
    RETURN.
  ENDIF.

  READ TABLE LT_RETURN_VALUE INTO DATA(LS_RETURN) INDEX 1.
  P_PERNR = LS_RETURN-FIELDVAL.

*
*  LOOP AT SCREEN.
*    IF SCREEN-NAME = 'S_VAPLZ-LOW' .
*      SCREEN-REQUIRED = 1.
*      MODIFY SCREEN.
*    ENDIF.
*  ENDLOOP.
