**&---------------------------------------------------------------------*
**& Include          ZXBS1U01
**&---------------------------------------------------------------------*
SYSTEM_STATUS_LINE_EXP = SYSTEM_STATUS_LINE.
USER_STATUS_LINE_EXP = USER_STATUS_LINE.

FREE MEMORY ID 'SYSTEM_STATUS_LINE'.
EXPORT SYSTEM_STATUS_LINE TO MEMORY ID 'SYSTEM_STATUS_LINE'.

FREE MEMORY ID 'SYSTEM_STATUS_LINE_ORD'.
EXPORT SYSTEM_STATUS_LINE TO MEMORY ID 'SYSTEM_STATUS_LINE_ORD'.

IF OBJECT_NUMBER CS 'OR'.
  FREE MEMORY ID 'SYSTEM_STATUS_ORDER'.
  EXPORT SYSTEM_STATUS_LINE TO MEMORY ID 'SYSTEM_STATUS_ORDER'.
ENDIF.
